### ISSUE TITLE
Metal Gear Acid 2 Special Card Videos Can Crash PPSSPP

### ISSUE THREAD

**Issue by TideGear** [hrydgard/ppsspp#10906]
I'm playing GIT v1.5.4-889-g26f5b5b93 on a Galaxy S9+. This problem appears in both Vulkan and OpenGL modes. The videos that play when special cards are used can crash PPSSPP.

![ulus10077_1 00_1](https://user-images.githubusercontent.com/16357059/38668227-8483143c-3df8-11e8-9bfd-d629f9afc510.jpg)

If you use the Cyborg Ninja card (and let the video play), then use The Fury card, PPSSPP will crash when it tries to play the second video. You can do it in reverse order (use Fury then Ninja), and it will still crash on the second card video. 

I think I've also seen this happen with the first play of a card video, but I can't 100% recall.

Here's the savestate where you can replicate this...
[MGA2 Card Videos Crash.zip](https://github.com/hrydgard/ppsspp/files/1902346/MGA2.Card.Videos.Crash.zip)

**Comment by hrydgard** [comment]
That change fixed a little issue where we could forget to set stencil state but use it anyway. I can imagine that it could cause crashes here, and loading the savestate it doesn't seem to happen for me anymore. Can you test on your S9?

**Comment by weihuoya** [comment]
invalid access, turn off fast memory will ignore error.
```
40:32:566 Main         E[G3D]: GPUCommon.cpp:651 sceGeListEnqueue: can't enqueue, stack address 08A8858C already used
40:32:567 Main         W[MEMMAP]: MemmapFunctions.cpp:91 ReadFromHardware: Invalid address 00000008
40:32:567 Main         W[MEMMAP]: MemmapFunctions.cpp:127 WriteToHardware: Invalid address 00000000
40:32:567 Main         W[MEMMAP]: MemmapFunctions.cpp:127 WriteToHardware: Invalid address 00000008
40:32:567 Main         W[MEMMAP]: MemmapFunctions.cpp:127 WriteToHardware: Invalid address 00000004
40:32:567 Main         W[MEMMAP]: MemmapFunctions.cpp:127 WriteToHardware: Invalid address 00000008
```

**Comment by hrydgard** [comment]
Huh. If that kind of error happens, it feels like it's on the CPU side rather than the GPU side. Maybe another ARM64 JIT bug...

**Comment by weihuoya** [comment]
Interpreter error log:
```
55:23:580 Main         E[G3D]: GPUCommon.cpp:651 sceGeListEnqueue: can't enqueue, stack address 08A8858C already used
55:23:620 Main         W[MEMMAP]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000008 PC 089c07a4 LR 089c0790
55:23:620 Main         W[MEMMAP]: MemmapFunctions.cpp:129 WriteToHardware: Invalid address 00000000     PC 089c07dc LR 089c0790
55:23:620 Main         W[MEMMAP]: MemmapFunctions.cpp:129 WriteToHardware: Invalid address 00000008     PC 089c07e8 LR 089c0790
55:23:620 Main         W[MEMMAP]: MemmapFunctions.cpp:129 WriteToHardware: Invalid address 00000004     PC 089c07ec LR 089c0790
55:23:620 Main         W[MEMMAP]: MemmapFunctions.cpp:129 WriteToHardware: Invalid address 00000008     PC 089c07f0 LR 089c0790
55:23:622 Main         W[MEMMAP]: MemmapFunctions.cpp:129 WriteToHardware: Invalid address 00000048     PC 089c19c0 LR 089ae568
55:23:622 Main         W[MEMMAP]: MemmapFunctions.cpp:129 WriteToHardware: Invalid address 0000004c     PC 089c19d0 LR 089ae570
55:23:622 Main         W[MEMMAP]: MemmapFunctions.cpp:129 WriteToHardware: Invalid address 00000050     PC 089c19e0 LR 089ae578
55:23:622 Main         W[MEMMAP]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000018 PC 089c2dc0 LR 089c1a00
55:23:622 Main         W[MEMMAP]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 0000004c PC 089c2dc4 LR 089c1a00
55:23:622 Main         W[MEMMAP]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000050 PC 089c2dcc LR 089c1a00
55:23:622 Main         W[MEMMAP]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000048 PC 089c2dd0 LR 089c1a00
55:23:622 Main         W[MEMMAP]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000008 PC 089c2e00 LR 089c1a00
55:23:622 Main         W[MEMMAP]: MemmapFunctions.cpp:129 WriteToHardware: Invalid address 00000000     PC 089c2e30 LR 089c1a00
55:23:622 Main         W[MEMMAP]: MemmapFunctions.cpp:129 WriteToHardware: Invalid address 00000004     PC 089c2e38 LR 089c1a00
55:23:622 Main         W[MEMMAP]: MemmapFunctions.cpp:129 WriteToHardware: Invalid address 00000008     PC 089c2e44 LR 089c1a00
```

IR Interpreter losing some function, can not play

**Comment by weihuoya** [comment]
sorry, with this code
```
gstate_c.Dirty(DIRTY_VIEWPORTSCISSOR_STATE | DIRTY_DEPTHSTENCIL_STATE | DIRTY_BLEND_STATE | DIRTY_RASTER_STATE);
```
vulkan work well, but opengl has similar error log

**Comment by TideGear** [comment]
By the way, is the super brief graphical glitch before the videos load a known issue?

**Comment by hrydgard** [comment]
Weird. The error that's being logged should have nothing to do with the little vulkan problem I fixed so there may have been two different crashes here? 

Dunno about the glitch.

**Comment by hrydgard** [comment]
Debugging crashes is super boring so I fixed the performance instead: https://github.com/hrydgard/ppsspp/pull/10911     It makes a pretty major change to the Vulkan stuff so not sure about merging before 1.6.

**Comment by TideGear** [comment]
Oh wow, so does it no longer crash then?

**Comment by hrydgard** [comment]
No, I just said that I worked on perf instead :P haven't fixed any crash bugs

**Comment by hrydgard** [comment]
You guys should try the latest build now, let me know what performance you get on your devices :)  The speedup is Vulkan-only for now.

Now, the crash.. I'll try to look into it later but it looks tricky :(

**Comment by hrydgard** [comment]
If you got acceptable performance out of this game, you had "slow buffer effects" disabled, didn't you? No (or less) need for that now!

**Comment by hrydgard** [comment]
Seriously? I got like 10 fps on S8 before my fixes. Do you have a US S9 (Adreno) or a international (Mali)?

My S8 now is full frame rate with hw splines.

**Comment by TideGear** [comment]
A US S9+ from Verizon.

**Comment by TideGear** [comment]
I found a weird graphics glitch almost immediately in v1.5.4-905-g21b2cbc81. it happens when I fire the AKM at the boss...

![ulus10077_1 00_2](https://user-images.githubusercontent.com/16357059/38765884-90a064c2-3f7e-11e8-8f63-9469cbb34dc9.jpg)

[MGA2 Weird Graphics Glitch On Bullet Hit.zip](https://github.com/hrydgard/ppsspp/files/1910139/MGA2.Weird.Graphics.Glitch.On.Bullet.Hit.zip)

Note: I changed splines back to high.

**Comment by hrydgard** [comment]
OK, maybe the old method isn't as slow on Adreno as on Mali. Because it was barely playable.

Huh, that's a weird one...

**Comment by hrydgard** [comment]
Fixed it.

**Comment by TideGear** [comment]
Yup, thanks! Crashes remain for now.

**Comment by TideGear** [comment]
Just donated as promised!

**Comment by TideGear** [comment]
Here's something that might help diagnose the crashing. I unlocked a card movie viewer and the crash still happens in that after two views...
[Card Movie Viewer.zip](https://github.com/hrydgard/ppsspp/files/1937447/Card.Movie.Viewer.zip)

**Comment by chiffon-rouge** [comment]
I don't know if this is of any help (it probably isn't) but I had the same problem using the latest dev on macOS. After turning off "fast memory" (which I remembered helped dealing with crashes in MGA 1) PPSSPP doesn't seem to crash anymore, though now I sometimes have graphical glitches after using certain cards/videos, which stay on the screen as green lines, forcing me to quit (though the games seems to keep running, I hear the sound notifications of commands I choose etc., though I can't see what happens anymore).

**Comment by TideGear** [comment]
@chiffon-rouge Thanks, CR, but at least on Android, the crashes still happen with fast memory disabled.

Still, it might be a clue for the devs?

**Comment by chiffon-rouge** [comment]
To be more precise, whenever I use a special card that triggers a video sequence for a second time (it doesn't need to be the same card, it seems) I get the graphical glitches, with the screen turning into green lines, while the game continues to play. So for example this happens when I play the Cyborg Ninja card first and then the same card again or the Fury. Before switching off 'Fast Memory' PPSSPP, following the same scenario, would crash. A workaround would be disabling videos (which, as I believe, is an in game option) I guess, but I haven't tested this yet.

**Comment by TideGear** [comment]
Just tested in v1.6.3-536-g7b34eaa1f, and this issue remains.

**Comment by hookaffy** [comment]
Having the same issue on 1.6.3 (whatever newest version on Play is), disabling Fast Memory fixes the crashes but usually after a character card video plays i get some sort of flickering screen, usually red/green glitched graphics or the loading screen. Game continues to run in background but nothing seems to revert the screen to normal.

**Comment by JMC47** [comment]
What happens if you turn off fast memory but *uncheck* ignore invalid read/writes.

**Comment by hookaffy** [comment]
I can't seem to find the option for 'ignore invalid read/writes,' is it in the nightly version?

**Comment by unknownbrackets** [comment]
There's no UI for that outside desktop.

On Android, you can change the setting by editing the ini file and looking for "IgnoreBadMemAccess = True".

-[Unknown]

**Comment by chiffon-rouge** [comment]
As of 1.8.0 (Play Store) this bug still exists (on Android Honor 6X, Android 7, I guess on macOS as well) – playing a second "cinematic card" crashes PPSSPP (with fast memory enabled) or continues the game with graphical glitches (with fast memory disabled).

**Comment by TideGear** [comment]
@chiffon-rouge Have you tried the latest build?

**Comment by spookyUnknownUser** [comment]
This doesn't really fix the issue, but for other googlers you can disable card videos through the in game settings, which seems to stop the videos playing altogether.

![image](https://user-images.githubusercontent.com/16196262/64078829-1646f380-cce0-11e9-8a6a-4ca8240e6814.png)

**Comment by hookaffy** [comment]
@spookyUnknownUser Indeed, disabling the card movies is the solution that I and probably most players of this game opted for, it's inelegant but works nonetheless. The card movies are a really cool part of the game imho, so finding a way to get them to play without crashing or soft locking the emulation would be pretty neat.

**Comment by spookyUnknownUser** [comment]
@hookaffy yeah totally agree. The card movies are awesome! Would be cool if this is fixed eventually 😎

**Comment by matoro** [comment]
I would also like to tack on that I am still seeing this issue on both v1.9.4 tagged and v1.9.3-642-g7d3552ae3 on Linux x86_64, so it does not seem to be a platform-specific issue.

**Comment by Panderner** [comment]
Still crashing on latest build?

**Comment by Gamemulatorer** [comment]
Anyone just try to add this game id to [MpegAvcWarmUp] compat.ini and see if it's help this issue.

**Comment by spookyuser** [comment]
> Anyone just try to add this game id to [MpegAvcWarmUp] compat.ini and see if it's help this issue.

Just tried and it doesn't seem to have fixed it.

**Comment by sum2012** [comment]
Anyone can retest the game with
v1.13.2-1366-g360eab321 or newer git version ?

**Comment by TideGear** [comment]
Tested on both v1.13.2-1635 for Windows 64-bit and v1.13.2-1630 for Android. Both still crash.

Regardless, thank you for your continued efforts, everyone.

**Comment by sum2012** [comment]
@TideGear Can you share the save states in here (zip first ,then upload in here) or https://www.mediafire.com ?

**Comment by sum2012** [comment]
Using old  save states in
https://github.com/hrydgard/ppsspp/issues/10906#issuecomment-383512322
Crash when see two times of video
ppsspp-v1.13.2-1635-gbd81aa328 log: 
https://gist.github.com/sum2012/7d320724b1457ea3e45b2201017752e9

**Comment by sum2012** [comment]
> Using old save states in [#10906 (comment)](https://github.com/hrydgard/ppsspp/issues/10906#issuecomment-383512322) Crash when see two times of video ppsspp-v1.13.2-1635-gbd81aa328 log: https://gist.github.com/sum2012/7d320724b1457ea3e45b2201017752e9
Game save
[ULUS10077001.zip](https://github.com/hrydgard/ppsspp/files/9996759/ULUS10077001.zip)

**Comment by unknownbrackets** [comment]
Maybe this is a timing issue or something.  It'd probably be useful to see all the sceGe* related calls right up to the crash.  Maybe something is making it enqueue the next list earlier than it should?

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets log: https://gist.githubusercontent.com/sum2012/5d6560519c4b85139cda5b46b9470f5d/raw/600e5833bfd2b1e909a923b0358294e80f0a0176/gistfile1.txt

**Comment by unknownbrackets** [comment]
Interesting, what are the commands in the display list at 48a7c884 - 48a7c88c at that point?  You'd think that after sceGeDrawSync() the display list would be done so there'd be no duplicate.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets Do you mean it ? (In the bluescreen)
![1](https://user-images.githubusercontent.com/2177532/201666405-4828c1c5-bb3a-43dd-87c0-1d031bf824b5.png)

**Comment by hrydgard** [comment]
No you have to use the GE debugger to view the display list, viewing it as MIPS code isn't very meaningful as you can see (bunch of totally bogus branches...)

**Comment by sum2012** [comment]
@hrydgard It is nothing in the bluescreen
![2](https://user-images.githubusercontent.com/2177532/201730799-c184ed8a-29bb-4d6a-b6ca-20cbf76ec47c.png)

**Comment by Revengeic3** [comment]
Still this issue, @hrydgard not sure how I can provide any valuable information on my crash? MacBook Pro 16" 32GB M1 Pro running Ventura 13.2.1 with latest MacOS PPSSPP version

**Comment by suggfudge** [comment]
Same issue here

device: edge 20
ppsspp ver: 1.18.1 non gold
backend: vulkan
which iso: literally all USA and europe versions that I could find in the last month act the same way
android ver: 13
oneUI ver (idfk): 5.1
accessibility settings turned on: none

~attached is~ it wont let me upload the zip of my stuff

**Comment by Panderner** [comment]
Tested on latest build: still crashes if i play special card video twice.

**Comment by Panderner** [comment]
Tested on interpreter: The game freezes after second video except can hear a sound and videos are repeatable.

https://github.com/user-attachments/assets/8db13b93-3cec-4e8a-9b9a-ec85860f64e2

**Comment by TideGear** [comment]
Just tried the new 1.19.3, and this bug remains.

Any hope of this being fixed someday?

**Comment by hrydgard** [comment]
I was hoping the PSMF change would have fixed issues like this, but apparently this is something different.

Everything to do with the details of video playback is very difficult to debug, but of course, I hope to find a fix at some point...

**Comment by Pliskin-Hunter** [comment]
Videos were working fine on earliers versions, each PPSSPP update brings new glitchs and bugs to MGA². It's really annoying 😞

**Comment by TideGear** [comment]
@Pliskin-Hunter It's not that the videos don't work. It's that the first video works, then it crashes on the second. The work-around is to skip videos, but that's hardly ideal.

**Comment by Pliskin-Hunter** [comment]
Yes, I know. This bug wasn't occurring on older versions, before the network implementation. I'll try to dig a bit around that and see if this can be fixed.
________________________________
De : TideGear ***@***.***>
Envoyé : vendredi 25 juillet 2025 07:15
À : hrydgard/ppsspp ***@***.***>
Cc : Pliskin-Hunter ***@***.***>; Mention ***@***.***>
Objet : Re: [hrydgard/ppsspp] Metal Gear Acid 2 Special Card Videos Can Crash PPSSPP (#10906)

[https://avatars.githubusercontent.com/u/16357059?s=20&v=4]TideGear left a comment (hrydgard/ppsspp#10906)<https://github.com/hrydgard/ppsspp/issues/10906#issuecomment-3116420721>

@Pliskin-Hunter<https://github.com/Pliskin-Hunter> It's not that the videos don't work. It's that the first video works, then it crashes on the second. The work-around is to skip videos, but that's hardly ideal.

**Comment by Toybasher** [comment]
Seems #16277 is a workaround/fix for the crashing from FMV cards are used. No idea of potential side effects given it's a PR from 2022, but maybe the method used can be examined, and fixed up for the current version of PPSSPP if it ends up breaking something as-is?

**Comment by TideGear** [comment]
Good looking out!

**Comment by sum2012** [comment]
Wait my 21012 pull request merged, I may try AI solve

**Comment by lilecto1** [comment]
> Wait my 21012 pull request merged, I may try AI solve

Sorry for creating the duplicate. I haven’t tried emulating this (my favorite PSP game) since probably 2019-2020 and was surprised to see it was still causing problems. 

What’s the AI solve involved?

**Comment by sum2012** [comment]
@lilecto1 play zip save status , then upload in here.

**Comment by lilecto1** [comment]
> [@lilecto1](https://github.com/lilecto1) play zip save status , then upload in here.

[mgs_acid2.zip](https://github.com/user-attachments/files/23918153/mgs_acid2.zip)

From the save State you should be able to equip or use the shiny cards and after two of them you will see the crash following the FMVs.

**Comment by sum2012** [comment]
@lilecto1 Can you upload to youtube to how to reproduce the crash ?

**Comment by lilecto1** [comment]
Here you go, sorry for the delay! [MGS Acid 2 crash](https://youtube.com/shorts/CssT1XojIVg?si=ecqL8YOwecxQHu7O)

> [@lilecto1](https://github.com/lilecto1) Can you upload to youtube to how to reproduce the crash ?

**Comment by sum2012** [comment]
> Here you go, sorry for the delay! [MGS Acid 2 crash](https://youtube.com/shorts/CssT1XojIVg?si=ecqL8YOwecxQHu7O)
> 
> > [@lilecto1](https://github.com/lilecto1) Can you upload to youtube to how to reproduce the crash ?

I cannot reproduce it. please try https://www.ppsspp.org/devbuilds/ .You need to backup game save

**Comment by lilecto1** [comment]
> > Here you go, sorry for the delay! [MGS Acid 2 crash](https://youtube.com/shorts/CssT1XojIVg?si=ecqL8YOwecxQHu7O)
> > > [@lilecto1](https://github.com/lilecto1) Can you upload to youtube to how to reproduce the crash ?
> 
> I cannot reproduce it. please try https://www.ppsspp.org/devbuilds/ .You need to backup game save

Problem solved with the newest Beta builds v1.19.3-1201 and the even newer v1.19.3-1203. Any FMV shown after the first still diplays the glitch of garbled video data for a few frames just before the FMV starts as mentioned in an above commment by TideGear back in 2018 - but it's barely noticeable. I wonder that the difference is between the build I was on (PPSSPP Gold 1.19.3 PS) and the beta?

Thanks so much for the help!

**Comment by Jigsy1** [comment]
I just want to point out this happened on the latest (1.20.3) Android version from the Play Store as well using Vulkan.

**Comment by Risae** [comment]
Also just happened with PPSSPP 1.20.4 on Windows 11

**Comment by Toybasher** [comment]
So it seems the bug was fixed then regressed due to a later update? Anyone know if it works alright in the current build?

**Comment by sum2012** [comment]
After LLE of sceMpeg , the hack may can be removed

**Comment by hrydgard** [comment]
Please re-test with v1.20.4-1845 or later (#22309).

**Comment by sum2012** [comment]
ppsspp_win_v1.20.4-1845-g99fecc1874d1 still need that compat.ini
v1.20.4-1845-g99fecc1874d1  disable that compat.ini crash log:
https://gist.github.com/sum2012/631c64ddfdec30b729c0e38302c30f52

**Comment by hrydgard** [comment]
Ah ok, makes sense, the crash is related to sceGe queue handling, not sceMpeg, even though it happens in association with a video. We'll keep the hack around for now, of course.

**Comment by hrydgard** [comment]
#22327 might have fixed it. However the fix can't be reliably tested by savestate (as it will go by the old HLE path instead of sceMpeg LLE). Can someone try it without loading a savestate after disabling the compat.ini option "IgnoreEnqueue"?

**Comment by sum2012** [comment]
Using Game save in my floor  https://github.com/hrydgard/ppsspp/files/9996759/ULUS10077001.zip ,  edit: disabling the compat.ini option "IgnoreEnqueue" 
v1.20.4-1913-gab6ccbd08c
 Fixed, Need remove the hack before close this
