### ISSUE TITLE
Pursuit Force graphic issues

### ISSUE THREAD

**Issue by weihuoya** [hrydgard/ppsspp#11216]
### What happens?
car run under road in some place, test on android, PC seem doesn't has this issues.
![1](https://user-images.githubusercontent.com/3827333/41832534-1158e2b8-787f-11e8-983b-88cf85371b28.jpg)
![screen1](https://user-images.githubusercontent.com/3827333/41832580-35114b8c-787f-11e8-90c4-791d78e8b174.png)

another issue, graphic glitches vulkan backend only. opengl and direct3d work ok.
![screen2](https://user-images.githubusercontent.com/3827333/41832594-3e11ece6-787f-11e8-9c63-04872f67eb8d.png)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP version:
ppsspp-v1.6.3-248-g098a7ffea-windows-amd64.7z
ppsspp-v1.6.3-248-g098a7ffea-android.apk

this game use hundreds of bezier lines.  like Acid 2 use hundreds of splines.

**Comment by unknownbrackets** [comment]
So there are two separate issues here - do they both happen only on Vulkan?  Or does the mobile issue happen on OpenGL and Vulkan both, and the other issue happen only on Vulkan?

-[Unknown]

**Comment by xebra** [comment]
We can avoid this bug(maybe second issue only) using the following fix.

StateMappingVulkan.cpp

```
key.depthClampEnable = gstate.isClippingEnabled() && gstate_c.Supports(GPU_SUPPORTS_DEPTH_CLAMP);

to

key.depthClampEnable = false;
```

Probably, the same issue as D3D11.
D3D11: Specify DepthClipEnable = TRUE when creating rasterizer states…  480a05d

**Comment by unknownbrackets** [comment]
Hmm, but if the game specified that flag, it indicates to clamp depth to the [0, 65535] range.  Maybe the flag is ignored when drawing beziers or something?

-[Unknown]

**Comment by leopard20** [comment]
Weird. I don't have this problem on my phone using Vulkan. Instead I get a weird "mirroring" effect when I enable "Hardware Tessellation". The game is not playable on Vulkan without this option. The opposite is true with OpenGL. If I enable this option the game becomes super slow!
![screenshot_2018-06-25-18-14-33-569_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/41854025-715b46c2-78a4-11e8-96f6-be599d342952.png)

**Comment by unknownbrackets** [comment]
@leopard20 check the features tab in system information - your device may not even support depth clamping.

-[Unknown]

**Comment by weihuoya** [comment]
unchecked simulate block transfer, the game is running smoother.
when use **low** spline/bezier curves quality, car run under road in some place.

**Comment by xebra** [comment]
Ah, low quality is not spline/bezier. It's just drawing control mesh(no curve tessellation/evaluation). So it's just specification(not bug). However I fixed it and I will commit later.

@unknownbrackets Vulkan depth clamp issue is related to Vulkan driver bug or unsupported feature maybe.

**Comment by unknownbrackets** [comment]
Is v1.6.3-323-g945eab6fe the first build that stopped working?  What's the last build that works?

Also - which positioning of the yellow is "correct"?

Can you try that same exact scene in the software renderer?  It might be that we need to clamp depth at the fragment level to be correct (which is unfortunate.)  It will help to know if the software renderer has the same glitch.

-[Unknown]

**Comment by Anuskuss** [comment]
### Before yellow roadblock (depth map)
#### OpenGL
![before_ogl_depth](https://user-images.githubusercontent.com/7157389/43819036-a2da81d6-9ae1-11e8-8e13-7e61caafb520.png)
#### Vulkan
![before_vk_depth](https://user-images.githubusercontent.com/7157389/43819047-aba7e6c8-9ae1-11e8-8fde-5d9ef06fae73.png)

### After
#### OpenGL
![after_ogl_depth](https://user-images.githubusercontent.com/7157389/43819069-bb80a602-9ae1-11e8-85cc-6abef2272576.png)

#### Vulkan
![after_vk_depth](https://user-images.githubusercontent.com/7157389/43819076-c28b7c1a-9ae1-11e8-92cf-d3919ba3f320.png)

**Comment by unknownbrackets** [comment]
I wonder if that error is caused by KhronosGroup/glslang#1418, if it's happening on PC.

What does depth look like using the software renderer?  In theory, that's the correct depth.

-[Unknown]

**Comment by Anuskuss** [comment]
#### Before
![before](https://user-images.githubusercontent.com/7157389/43999157-1222c7f6-9e07-11e8-85ed-2fee31b50595.png)
#### After
![after](https://user-images.githubusercontent.com/7157389/43999158-154f3aa4-9e07-11e8-8f98-3ab610feaf26.png)

**Comment by unknownbrackets** [comment]
Okay, then probably OpenGL is correct.  Since it seems like it renders mostly right in the software renderer, can you try making a GE debugger dump?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

I can even try running this on a real PSP to compare (that's still experimental, though.)  Then I could see what depth /should/ be for sure.

-[Unknown]

**Comment by Anuskuss** [comment]
So I have to switch to Software Renderer, click _Step Tex_ in the GE Debugger until the texture appears in the preview window, then _Record_ and then _Resume_?
[UCES00019_0001.zip](https://github.com/hrydgard/ppsspp/files/2281563/UCES00019_0001.zip)

**Comment by Anuskuss** [comment]
**Backend:** Vulkan
**Software Renderer:** off

Again, I waited for the yellow roadblock to appear in the texture preview, _Record_ -> _Resume._ This time theres actually stuff in the file.

[UCES00019_0001.zip](https://github.com/hrydgard/ppsspp/files/2282651/UCES00019_0001.zip)

**Comment by unknownbrackets** [comment]
Hmm, it seems to heavily use minz/maxz and viewport z params.  Maybe something isn't dirtying properly, or else there's somewhere we're handling these depth params wrong.

Most of the drawing is done with the viewport centered on the first 50% of depth (0 - 16383), and with a maxz of 16383.

-[Unknown]

**Comment by Anuskuss** [comment]
Do note that this is working fine with earlier builds.
**Last good:** `v1.5.4-189-gc1a23658d`
**First bad:** `v1.5.4-197-gea50561c8`

**Comment by unknownbrackets** [comment]
Right, so that points to depth clamping - #10454.  But the question is, why.  The PSP definitely clamps depth, but maybe we need to do it in the fragment shader for it to be accurate.

I think right now, we're deforming polygons when it clamps, perhaps, which is only okay in flat or mostly-flat cases.

-[Unknown]

**Comment by unknownbrackets** [comment]
How does this look with recent changes now?

-[Unknown]

**Comment by weihuoya** [comment]
test latest dev build, vulkan still have graphic issues.

use **low** spline/bezier curves quality, car run under road in some place, but not worse than before.

**Comment by Anuskuss** [comment]
Everything is fine for me again. I couldn't test it since the [Lost the Vulkan device!](https://github.com/hrydgard/ppsspp/issues/11216#issuecomment-410902422) error but as of `v1.6.3-482-g025e478d2` (last bad: `v1.6.3-479-g637a17a66`) it's all working again and the graphics are correct.

**Comment by hrydgard** [comment]
I believe this is fixed, closing. Please reopen if not.

**Comment by hrydgard** [comment]
Apparently not, reopening.

**Comment by hrydgard** [comment]
Apparently still an issue, from Dakile on Discord, with GTX 980m:

https://cdn.discordapp.com/attachments/480103153803460614/551370781482024961/unknown.png

**Comment by unknownbrackets** [comment]
I assume this is caused by #11399, and doesn't fall into the simple case 9859827 handles.

See here for a possible workaround (might break other games, I think I ran across one it would, but still might break less):
https://github.com/hrydgard/ppsspp/issues/11399#issuecomment-423394932

-[Unknown]

**Comment by MojoJojoDojo** [comment]
Yeah this is still a thing even on the current git versions and the latest stable version.
Tried out Pursuit Force Extreme Justice and the graphics are messed up all over the place.

**Comment by unknownbrackets** [comment]
A GE frame dump of an issue currently happening would be helpful.  The previous frame dump still seems to work fine.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Vertex cache + HW Tessellation make this game faster on my phone R9 Mali-G52 GPU
![Screenshot_2021-09-23-00-49-29-607_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/134387320-f79da871-fe15-4ad4-a27e-e5c85b583bf0.jpg)

Vertex cache and HW Tessellation is off
![Screenshot_2021-09-23-00-49-55-479_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/134387397-e04f5357-5391-45e1-acee-cbac3e7d8283.jpg)

I also notice some rendering issue the road sometimes is flickering?
[Pursuit Force.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7212530/Pursuit.Force.ppdmp.zip)

**Comment by Anuskuss** [comment]
There are multiple issues in this thread:
1. ~~https://github.com/hrydgard/ppsspp/issues/11216#issue-335271262 (top)~~: *Spline/bezier curve quality* set to *Low* / not a bug
2. https://github.com/hrydgard/ppsspp/issues/11216#issue-335271262 (bottom): Probably related to #11399 / fixed by #14833
3. ~~https://github.com/hrydgard/ppsspp/issues/11216#issuecomment-399958757~~: Missing hardware feature / not a bug
4. ~~https://github.com/hrydgard/ppsspp/issues/11216#issuecomment-410902422 (top)~~: Fixed as of `v1.6.3-482-g025e478d2`
5. ~~https://github.com/hrydgard/ppsspp/issues/11216#issuecomment-410902422 (bottom)~~: Fixed as of `v1.6.3-482-g025e478d2`
6. ~~https://github.com/hrydgard/ppsspp/issues/11399#issuecomment-539200059~~: Fixed by #14833
7. https://github.com/hrydgard/ppsspp/issues/11216#issuecomment-468913595: Probably missing hardware feature / not a bug
8. ~~https://github.com/hrydgard/ppsspp/issues/11216#issuecomment-925107278~~: Related to #11399 / fixed by #14833

**Comment by Saramagrean** [comment]
v1.12.3-232-gb6e7fe1aa still happen (All backends). 

![PF-E0](https://user-images.githubusercontent.com/26355472/142432483-4d74ebc2-c085-43b0-b37f-0d03d5dc99fe.png)
![PF-E1](https://user-images.githubusercontent.com/26355472/142432777-1a58eab3-8ad0-4941-89c6-ef74c073c1bf.png)

GE Dump.
[DUMP.zip](https://github.com/hrydgard/ppsspp/files/7563492/DUMP.zip)

**Comment by unknownbrackets** [comment]
Right, that's #11399.  As noted there, clamping against the wrong boundary is still not worked around.

-[Unknown]

**Comment by Panderner** [comment]
Desktop OpenGL is broken:
![PPSSPP v1 12 3-990-gb631ace6d - UCUS98703 _ Pursuit Force™_ Extreme Justice 3_16_2022 1_57_43 PM](https://user-images.githubusercontent.com/37503397/158526330-41877cc2-3535-42df-9962-346d0eb80515.png)

Mobile OpenGL is ok:
![Screenshot_2022-03-16-13-55-42-956_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/158526614-56bcdaa3-e774-45e3-8d38-b976c364506c.jpg)

**Comment by jy95** [comment]
For me, OpenGL / Vulan / Direct3D 9 / Direct3D 11 are both broken

**Comment by Gamemulatorer** [comment]
@weihuoya what about this now.

**Comment by flexxarnnn** [comment]
I looked through previous versions of ppsspp and for me atleast the newest version to work right was ppsspp v1.11.3 when using the OpenGL renderer. 
![image](https://user-images.githubusercontent.com/112896249/188495423-4e030ea3-efdb-4ebc-85b6-15f16fc3fb32.png)

**Comment by jy95** [comment]
Confirmed - I tried on several versions but it only works on v1.1.3 with OpenGL renderer

**Comment by unknownbrackets** [comment]
#16049 will make this work on most devices other than those using Mali GPUs.

-[Unknown]

**Comment by Panderner** [comment]
Still has issue:
https://streamable.com/60wkiq

**Comment by Gamemulatorer** [comment]
> Still has issue: https://streamable.com/60wkiq

Can you upload your savestate in that area?

**Comment by Panderner** [comment]
> Can you upload your savestate in that area?

At the beginning of the game.

**Comment by unknownbrackets** [comment]
Thanks, I think I fixed the issue in the latest git - if not #16069 should mean less precision issues.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Confirm fixed via https://github.com/hrydgard/ppsspp/pull/16069/commits/f8d29fdc1a8b4b703ee9466e1127b9b571e4c64a
![Screenshot_2022-09-21-16-49-31-39](https://user-images.githubusercontent.com/37603562/191460128-4dcadec8-9492-4a2b-9953-595d976ad74b.png)

The performance is so slow...

**Comment by hrydgard** [comment]
@Gamemulatorer Did the performance slow down with the fix, or was it already slow?

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer Did the performance slow down with the fix, or was it already slow?

It was already slow :(
Maybe Snapdragon 450 is not good enough for this game.
![Screenshot_2022-09-21-17-02-45-19](https://user-images.githubusercontent.com/37603562/191463053-42f8d68b-e041-4ad0-b35a-c628f94b3b73.png)

**Comment by hrydgard** [comment]
Alright, that's good to know.

Yeah the game makes extremely heavy use of tessellation for the road surface, which is not fast in PPSSPP unfortunately.

Probably need to take another look at figuring out a way to make hardware tessellation work better and go fast. Using compute shaders instead of the wacky instancing trick we're currently using might help. Maybe some dynamic detail adjustment, too.

**Comment by unknownbrackets** [comment]
Note for any Mali users looking at the above and confused why it's still happening for you: this is only fixed on devices that support a hardware feature called "clip distance", which some GPUs (i.e. Mali) don't.

-[Unknown]
