### ISSUE TITLE
"Load state. Saved in game. Quit and restart for less bugs" message in Raspberry PI 3

### ISSUE THREAD

**Issue by luizthiagor** [hrydgard/ppsspp#11268]
### What happens?

In any game i wish to play , when i use load state this message appears indicanting to quit game, restart and load again for less bugs .... sometimes, in saveStates game stop works and savegame corrupts (Ratchet and clank , for example) - Only in ppsspp 1.6.3

### What *should* happen?

Onle save stated and Load state messages and not corrupt my saves - In version 1.5.4 this issue does not occur

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Raspberry Pi 3, Batocera Linux 5.16 with 1.6.3 version of ppsspp. In 1.5.4 this message does not appears and savestates works faster and better ....

**Comment by LunaMoo** [comment]
The message is not corrupting savestates, it's just informing that savestates aren't perfectly safe which is a lie to shorten a longer thought about playing the game for a very long time makes it unstable and abusing savestates as the only means to save IS simulating such situation. Abusing savestates between different emulator versions might not be perfectly safe either and should not be abused for the sake of laziness either.

 Save normally via in-game save system, restart emulation and reload the game from that normal save, it should then work fine as long as you stop loading older savestates.

**Comment by luizthiagor** [comment]
I give a try this , but, as far as i remember i've not used old save states from another version of PPSSPP in this new version ..but i can do this : save in game , delete all savestates in folder (all or only of this game specific to test[ backap before]) and do a new test to view if this message dissapear ....

Thank you for your help , i can go here again to report if it worked for me ! Thanks

**Comment by luizthiagor** [comment]
in 1.5.4 this message not appear and savestates work very well on RPI3

**Comment by unknownbrackets** [comment]
The message is new, but save states have not changed - they are not slower or differently designed.  It's just that before you were under the false impression that they were perfectly safe, and now the message has told you that isn't true.

Save states were equally unsafe in v1.5.4, and even v1.6.3 actually, but the message did not show in either version.

The message was introduced after v1.6.3 was released.  There was a bug in a git build that showed the message too often, incorrectly.  That bug has been fixed for a month (1d430ff) and is fixed in the latest git build.

I'm guessing you are using a git build from before 2018-07-04, but after 2018-06-22.

If there's some actions you can take to corrupt a save game in Rachet and Clank, what are they specifically?  Do you have a working and a broken save game that you can upload in a zip file?  Which git build specifically started causing corruption to in game saves (you can test by halves to find it the quickest)?

-[Unknown]

**Comment by luizthiagor** [comment]
i believ this issue is related to this specific version of ppsspp compilation into my batocera linux for testes .... because i have deleted all my save states , loaded the game by an saved in game feature and, i i save stated and load it, the message still showing the same ....

probably this is related to this problematic issue in versions you related above ! Thanks for explain

**Comment by unknownbrackets** [comment]
Is there any update now - is this still happening?

If it's just from an old build, perhaps we should close.

-[Unknown]

**Comment by luizthiagor** [comment]
I have to test new builds to can see if the erros solved ...but in the new versions of ppsspp after the commit https://github.com/hrydgard/ppsspp/commit/c404214042718b648cc23bfaea46e25ce589f130 (updated the gslang)

the compitalion has ok, but when run emulator, it does not find the file libSPIRV.so.

After this compitation , after we updated the gslang this problem occrus in my emulator ... (infos from the dev of batocera Linux)

so, i can not test if this problem is solved ...

**Comment by unknownbrackets** [comment]
@hrydgard that's strange - shouldn't we be compiling in all the needed parts?

-[Unknown]

**Comment by unknownbrackets** [comment]
Should probably create a separate issue about the startup failure.

-[Unknown]

**Comment by luizthiagor** [comment]
The main problem of this toppic "SaveStates" has solved in new commit testesd yesterday ...so, i will close this toppic and waiting for developer of my sistem used open a topic specific for problems in compilattion of new commits after the c404214
