### ISSUE TITLE
MGS PW: Physics issues during LAV-G boss battle (Windows 10 64-bit)

### ISSUE THREAD

**Issue by Inglorii** [hrydgard/ppsspp#11817]
Hello everyone, I'm having a Metal Gear Solid: Peace Walker physics issue.

The armored vehicle tilts to the air like it was stuck on an invisible hill. When soldiers jump from it, they may slowly disappear into the ground.
![image](https://user-images.githubusercontent.com/47834642/53128305-de0e6d80-3564-11e9-998a-3f1d976b21f0.png)
![image](https://user-images.githubusercontent.com/47834642/53128469-2f1e6180-3565-11e9-88c1-c8e6330974b2.png)

The vehicle should remain close to the ground instead of doing crazy stuff like that.

I'm playing on a Windows 10 64-bit laptop
Intel Core i7 5700-HQ
8,00 Go RAM
Nvidia GTX 960M

PPSSPP version: v. 1.7.4.

Thanks in advance for your help

**Comment by AkiraJkr** [comment]
Does this issue still occur in the latest git version of PPSSPP? Could you try to pinpoint what was the last build to have this issue if the latest is working? Could you find which version caused this issue otherwise?

**Comment by hrydgard** [comment]
This is another one where the new JIT debug options could potentially figure out what's wrong.  See https://github.com/hrydgard/ppsspp/wiki/How-to-find-JIT-bugs,-the-easy-way

**Comment by Inglorii** [comment]
I've reloaded my save on the latest git version, and I'm glad to say that it worked perfectly fine! I'll try different builds later. And I'll mess around with the check boxes. Do you suggest I should stick with the latest git build, if no other bugs appear? Thank you very much!

**Comment by hrydgard** [comment]
Yeah, I'd recommend you stick to that build and then upgrade to 1.8.0 when it becomes available.

**Comment by unknownbrackets** [comment]
If you end up having the time, I'd be really curious what change in PPSSPP fixed this (meaning, which git build.)

You can find it by going by halves (e.g. from 400 -> 200 -> 300 -> 250, etc.), which will take the least number of tries.  No worries if you don't have time, just didn't realize we fixed something that could cause this.

-[Unknown]

**Comment by Orikoin** [comment]
While the problem still persists on 1.8, i followed the steps to find the problem.
It appears that VFPU_VEC in the JIT section is the cause of this and to any with the same problem this will help out, i dont know of any other effects desabling this will have though.

sorry for my ramble hope this helps someone out.
-Dan

**Comment by hrydgard** [comment]
@Orikoin  wait, so it's not fixed in the latest git build for you? https://buildbot.orphis.net/ppsspp/

**Comment by Orikoin** [comment]
ah i think this is where my confusion lays, i was meaning for the 1.8.0 download on the ppsspp site, whichever one that would go to on that list is probably not the latest im guessing.

chances are that it would have been fixed then, when i get the chance i will upgrade to the latest but for now i will run with that compiler section turned off

sorry im sorta new here
-Dan

**Comment by hrydgard** [comment]
Cool, thanks for letting me know.
