### ISSUE TITLE
[Vulkan] anv_bind_buffer_memory: Assertion (...) failed.

### ISSUE THREAD

**Issue by 5schatten** [hrydgard/ppsspp#11882]
Looks like this https://github.com/hrydgard/ppsspp/issues/10886 is still not resolved. Other emulators like Dolphin work flawless with Vulkan.

### What happens?
PPSSPP won't start if Vulkan is set as renderer.

`PPSSPPSDL: ../src/intel/vulkan/anv_device.c:2901: anv_bind_buffer_memory: Assertion (buffer->usage & mem->type->valid_buffer_usage) == buffer->usage' failed.
Aborted`

log: http://ix.io/1DqS

### What *should* happen?
PPSSPP should work with Vulkan.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP v1.7.5
Intel i3-6100 & IGP
LibreELEC 9.x | Kernel 4.19.28 | Mesa 19.0.0
dmesg: http://ix.io/1DqW

Package:
https://github.com/5schatten/LibreELEC.tv/blob/libreelec-9.x-rr-working-tree/packages/5schatten/emulation-standalone/ppsspp/package.mk

**Comment by hrydgard** [comment]
How up to date are your graphics drivers / mesa? Again, as described in #10886 I believe this is a bug in the driver, not PPSSPP. I guess those other emulators don't happen to exercise that code path.

**Comment by 5schatten** [comment]
As stated it's Mesa 19.0 so should be "pretty much" up to date. Since LibreELEC is an embedded Distribution I've no debugger to run it straight the device.

PPSSPP worked in the past with Mesa 18.x something I'm not sure which version in particular but the last bug report stated 18.1 which is quite possible.

After 18.1 they've changed the code how the assertion is handled from https://github.com/mesa3d/mesa/blob/18.1/src/intel/vulkan/anv_device.c#L2435 to https://github.com/mesa3d/mesa/blob/19.0/src/intel/vulkan/anv_device.c#L2901 so it could be a reintroduced mesa bug too.

**Comment by hrydgard** [comment]
Can you please run in a debugger and get the call stack so I can see the chain of events where this happened?

**Comment by hrydgard** [comment]
Hm, I think I see how we might end up here from VulkanQueueRunner::ResizeReadbackBuffer if there's no appropriate memory type. Besides, I think we might be using a suboptimal memory type there, but whatever.

Can you confirm that this is the source of the trouble by running in a debugger as described previously?

**Comment by unknownbrackets** [comment]
Maybe this was fixed by some of the buffer selection changes in the latest git?

-[Unknown]

**Comment by 5schatten** [comment]
@hrydgard 
As I said it's an embedded distro so I would have to create a gdb package first to run it on this htpc device. Unfortunately does my x220 Thinkpad lack Vulkan support & my workstation comes with a Nvidia card.
But I've asked the LE devs if there is a way to include / run gdb on LE.

@unknownbrackets 
Quite possible but after the last pre 1.8 commits were broken on my S905 based system I reverted the package to 1.7.5 because this runs on Generic, RPi & AML flawless.

**Comment by hrydgard** [comment]
Thanks, okay, I see what we're doing wrong, it's very similar to the problem we had with images on PowerVR. I'll whip up a fix shortly.

**Comment by hrydgard** [comment]
I merged what I believe to be a fix. If that doesn't do it, it's definitely a driver bug.

**Comment by 5schatten** [comment]
I've already pulled the patch & will test it afterwards.

**Comment by mrcmunir** [comment]
Working fine for me with latest 19.x mesa3d devel + intel 6006u + 520 IGP can't reproduce this error .

**Comment by 5schatten** [comment]
Well still fails for me. I've tested 1.7.5+cherry picked patch & 1.8.0-dev

**Comment by hrydgard** [comment]
If not you should report this bug to the Mesa project. I'm sure we're not doing anything else wrong with this buffer.

**Comment by 5schatten** [comment]
Well I've tried https://github.com/mesa3d/mesa/commit/19ab08200179e71af42ce6e1b91f502e50f915b3 so Mesa 19.1.0-devel but still fails for me:

`PPSSPPSDL: ../src/intel/vulkan/anv_device.c:3121: anv_bind_buffer_memory: Assertion (buffer->usage & mem->type->valid_buffer_usage) == buffer->usage' failed.
Aborted`

**Comment by unknownbrackets** [comment]
We cache the result of `vkGetPhysicalDeviceMemoryProperties`, so whether we cache the result of `MemoryTypeFromProperties` or call `MemoryTypeFromProperties` every time shouldn't change anything, unless we're asking for specific usage types (#11884) - right?

I mean, the input parameters are fixed (`0xFFFFFFFF, VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT`) so the outputs should be fixed right?  Sorry - what am I missing?

-[Unknown]

**Comment by hrydgard** [comment]
Argh, I made a mistake. Instead of 0xFFFFFFFF we should use reqs.memoryTypeBits, which makes it make sense.

**Comment by hrydgard** [comment]
@5schatten  Please test with that latest commit as well.

**Comment by 5schatten** [comment]
Already building 👍

**Comment by 5schatten** [comment]
1.7.5 + the patch set runs but only the upper left quadrant is rendered.

**Comment by hrydgard** [comment]
Why would you run 1.7.5 and the patch set? Just run master and see if that works better for you.

**Comment by 5schatten** [comment]
Because 1.8.0 is broken for my Khadas Vim (AML S905X) based system so I prefer to iron out one problem after another.
