### ISSUE TITLE
amd 7970 wont load program, instant ctd

### ISSUE THREAD

**Issue by 43q63w45634w56** [hrydgard/ppsspp#12006]
**### What happens?**
crashes on opening exe

**load1 log:**
`
57:26:058 NativeApp.cpp:384 E[LOADER]: Failed graphics backends: 0
57:26:058 Config.cpp:557 E[LOADER]: Graphics backend failed for 0, trying another
57:26:058 NativeApp.cpp:389 W[LOADER]: Failed graphics backend switched from 0 to 3
`

**load2 log:**
`
20:28:851 NativeApp.cpp:384 E[LOADER]: Failed graphics backends: 3,2,0,1,ALL,ALL,ALL
20:28:851 Config.cpp:557 E[LOADER]: Graphics backend failed for 0, trying another
20:28:851 Config.cpp:582 E[LOADER]: All graphics backends failed3
`

### **load3 log:** **### _game actually started and crashed after i hit start ingame_**
file too big for pastebin and to paste in code here apparently 
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/3125626/ppsspplog.txt)

**### What *should* happen?**
it should work

**### What hardware**
windows764bit
all versions of ppsspp i tried newest git all the way back to 1.5.0
amd radeon hd 7970

**opengl tests:**
![DCCDefh](https://user-images.githubusercontent.com/49365256/56871491-adc3cf00-69ec-11e9-84c0-29a1794af881.png)

**Comment by ahegaofish** [comment]
works fine with ppsspp core in retroarch, im just going to assume its a shotty client.
![SytmsAt](https://user-images.githubusercontent.com/49365256/56872010-385afd00-69f2-11e9-971b-42c745e85b8d.png)

**Comment by unknownbrackets** [comment]
Normally, failed graphics backends are only logged during initial PPSSPP startup.  You said it's crashing in game though - how are you starting PPSSPP?

If you start PPSSPP, don't start any game, and switch between backends - do they all load successfully?  If PPSSPP just closes when you restart it to select a certain backend, it means that your driver is crashing when we try to setup that graphics backend.

Retroarch supports afaik a more limited set of graphics backends and more limited settings.  Be warned: you'll get crashes on resize and you may get crashes on creating/loading save states.  There are several bugs/problems unique to the libretro port of PPSSPP.

If it only crashes once you actually start the game, this shouldn't be logged as a failed backend.  Are you starting PPSSPP with the game directly (as a shortcut, etc.)?

Lunar specifically uses fonts.  You may be interested in #2788, and if you're trying to run PPSSPP without all its proper files (including either the uglier open source fonts, or the copyrighted fonts from a PSP), the game might be crashing.  It shows a message loading the font files early on, and probably won't take kindly to them being missing.

-[Unknown]

**Comment by ahegaofish** [comment]
i know about the fonts thanks
i said it was crashing on loading the exe period, i only got into game once and then it crashes for whatever reason but that never happened since, the first two is what happens when i click the EXE period.

**Comment by ahegaofish** [comment]
i may want to add some filters or shaders
but i think you get the point
![0oPbD38](https://user-images.githubusercontent.com/49365256/56873001-013e1900-69fd-11e9-9735-a8910c2572e1.jpg)

**Comment by ahegaofish** [comment]
i can go into and out of exclusive fullscreen with (f) without crash
![3AfCnq6](https://user-images.githubusercontent.com/49365256/56873062-a78a1e80-69fd-11e9-9756-74e3f6964074.png)

**Comment by unknownbrackets** [comment]
Are your graphics drivers all up to date?

If you've had a different video card (such as Intel or NVIDIA) before the AMD one in the same computer, you might have old drivers laying around.  Sometimes these can cause problems too, so it'd be best to remove or update them too.

That said, the latest git should be working around the crash we know about with old AMD drivers.

Do you possibly have GeDoSaTo installed?  I believe this is also known to cause crashes.  It's a tool that helps improve graphics in certain games, but it interferes with PPSSPP's startup.

-[Unknown]

**Comment by ahegaofish** [comment]
no i dont have gedosato
ive tried multiple driver versions of amd
dont have different video card
dont have old drivers, i clean up my system and it wouldnt make a difference i can bet on that

i tried beta and stable amd drivers
and retroarch ppsspp works, its clearly an issue with the ppsspp client, i left my logs, if _they_ wanna fix it

i have done everything i can possibly do

**Comment by LunaMoo** [comment]
Typically if one person suffers from issue nobody else can reproduce, it's caused by something in that person's system and without wanting to get involved in solving it, you might as well close the issue.

 I'm not familiar with recent amd gpu drivers, but I have very big steam collection and know there are games which still crash on anything newer from 16.11 from few years ago and those were already worse from oldest pre-crimson drivers at least on older gpu's. Other software might work in a way that avoids your system specific bugs and PPSSPP might need a workaround, but it will be impossible to even understand what's happening by a log that says everything failed. Every pc is different, it's not really a software bug when it fails to work on a single pc.

**Comment by acemod13** [comment]
Now, I can't say that it's 100% true (since the support on driver level may have changed since last time I heard about it) but OpenGL support on Windows isn't stellar on the driver side. Try to run PPSSPP with the DirectX 9 or 11 backend.

**Comment by orbea** [comment]
> There are several bugs/problems unique to the libretro port of PPSSPP.

This is true for every version of ppsspp...

**Comment by ahegaofish** [comment]
I shrinked my windows 7 partition a little bit and installed windows 10
I booted into it and downloaded ppsspp, it runs no problems.
yall might wanna look into this

**Comment by CatKasha** [comment]
@43q63w45634w56 do you still have Windows 7 installed?

Can you check on Windows 7 through app GPU-Z (“Advanced” tab, select DirectX 11 from the list) which version of DirectX 11 is supported? Only DirectX 11.0 or DirectX 11.0 and DirectX 11.1?

If only DirectX 11.0, i have an assumption that you have not installed a patch for support Direct3D 11.1 (KB2670838)
I had the same problem on Windows 7 without updates, #11914

**Comment by unknownbrackets** [comment]
Any feedback on those questions?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
