### ISSUE TITLE
Ace Combat titles needing specific I/O Timing Method to prevent cutscene softlocks

### ISSUE THREAD

**Issue by Abbanon** [hrydgard/ppsspp#12434]
This has been a known issue for a long time, and there _is_ an existing workaround, but I noticed there was no existing report for this in particular.
So I'm throwing one up in hopes it will eventually be fixed.

Basically, the I/O Timing Method needs to be set to "Host (Bugs, less lag)" - otherwise both of the Ace Combat titles will softlock with a black screen during any FMV cutscenes. 
If you listen closely at this black screen softlock, you can hear a constant loop of the FMV sequence's first split second of audio. Almost like it's trying to play, but loops back to the beginning immediately.
You don't need to restart the game to fix this, because this softlock immediately goes away when the I/O Timing Method is changed to Host, allowing you to watch the cutscene just fine and resume normal gameplay.

**Comment by LunaMoo** [comment]
It had an issue in #5545 but it was reported fixed.
For sure "host" isn't needed at least on windows as I only use simulate UMD delays for everything and played through those games just fine sometime before pre-ordering AC7.;p

**Comment by unknownbrackets** [comment]
Have the async IO timing changes improved this at all?

-[Unknown]

**Comment by Abbanon** [comment]
Strange. As of `1.9.3-287-g25726deb4` the issue is fixed for Ace Combat X, but persists for Ace Combat Joint Assault.

An addendum: I've noticed here and there that the issue doesn't happen for everyone. So it's some sort of dependency on system specs/hardware/software.

Debug console shows nothing of this occurrence for either game, but for ACJA it does have some interesting information regarding other things.

When you first launch the game (ACJA), it displays this:
![acja-game launch](https://user-images.githubusercontent.com/37251822/75126915-1a017480-568a-11ea-82e1-ac2cbf0dbd50.png)

After the splash screens, etc., you reach the "Press Start" screen. Once you press start, it displays this:
![acja-whenyoupressstart](https://user-images.githubusercontent.com/37251822/75126936-34d3e900-568a-11ea-9b18-570fdb9c21ee.png)

Are they perhaps related in any way? Or should this be a separate issue entirely?
ACX doesn't have anything in the logs at all by comparison.

**Comment by unknownbrackets** [comment]
Those are just logging the game calling some functions in incorrect ways, but it's not clear if they are specifically bugs or not.  The same errors may occur when playing on a real PSP.

-[Unknown]

**Comment by benderscruffy** [comment]
i have it set to Simulate UMD delay and have not had any problems so far with both games
can be closed

**Comment by Blackbird88** [comment]
Still happens to me on latest build. I need to use Host timing else the game freezes.

**Comment by LunaMoo** [comment]
@Blackbird88 did you tried "simulate umd delays"? The problem with "host" is it depends on your hardware as such it's different for everyone, other two choices should not depend on that.

**Comment by sum2012** [comment]
Using attach old save
the game black screen when FMV/cutscene in stage 13
need to use Host timing 

[NPJH50263USERID_0000.zip](https://github.com/hrydgard/ppsspp/files/13070192/NPJH50263USERID_0000.zip)
Hope will find out which commit break;
First known fixed v1.2.2-871-ge4b0f29

**Comment by sum2012** [comment]
@Blackbird88 Can you share your game save , my game is Ace Combat X2 NOT 
Ace Combat titles. (Zip the save, then upload in here )

**Comment by sum2012** [comment]
Here is Ace Combat titles save status of cutscene fetlock
, it lock after mission 2 finish,
log similar to Ace Combat X2
[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/13179758/PPSSPP_STATE.zip)
