### ISSUE TITLE
[Android][OpenGL][Graphic issue] Muso Orochi 2 Special (ULJM06097) 無双OROCHI2 Special

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#12626]
### What happens?
In the weapon shop.
OpenGL: Not appear the window.
Vulkan  : Appear the window.

### What *should* happen?
Appear the window correctly on OpenGL.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP Ver. : 1.9.3-282
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

I attached dump.
Please,check it.

[ULJM06097_0001.zip](https://github.com/hrydgard/ppsspp/files/4208552/ULJM06097_0001.zip)

![Screenshot_20200215-224903](https://user-images.githubusercontent.com/48179091/74589319-97eccc80-5047-11ea-8185-ddc98b203074.png)
Story mode > Shop

![Screenshot_20200215-224929](https://user-images.githubusercontent.com/48179091/74589341-d71b1d80-5047-11ea-84e8-8df2b4d6da48.png)
Select fusion weapon menu.

![Screenshot_20200215-224941](https://user-images.githubusercontent.com/48179091/74589363-0f226080-5048-11ea-8901-bf8075daea48.png)
Select the character.

![Screenshot_20200215-224956](https://user-images.githubusercontent.com/48179091/74589402-75a77e80-5048-11ea-88ae-e2a56b89efc1.png)
**Vulkan**

![Screenshot_20200215-225056](https://user-images.githubusercontent.com/48179091/74589432-a7b8e080-5048-11ea-8b0a-f3a6bd078251.png)
**OpenGL**

**Comment by unknownbrackets** [comment]
The dump seems to be from a different place (the character select):

![ULJM03050_00000](https://user-images.githubusercontent.com/191233/75747327-70e1fc00-5cd1-11ea-8f88-8ed6344a9029.png)

And it looks the same in both OpenGL and Vulkan for me.  Can you post a dump from the same place?  After selecting the character.

GE dumps are like screenshots, but they contain more information.  They don't show the future or past.  They only show that one moment.

-[Unknown]

**Comment by nassau-tk** [comment]
OK.
I got dump files.
Please chek it!

[OpneGL] ULJM06097_0002.zip
[ULJM06097_0002[1].zip](https://github.com/hrydgard/ppsspp/files/4279926/ULJM06097_0002.1.zip)

[Vulkan]   ULJM06097_0003.zip
[ULJM06097_0003[1].zip](https://github.com/hrydgard/ppsspp/files/4279929/ULJM06097_0003.1.zip)

![musoorochi2special_issue](https://user-images.githubusercontent.com/48179091/75753794-de903580-5d6e-11ea-8a4d-ca707503d07a.png)

**Comment by nassau-tk** [comment]
@unknownbrackets 
I tried testing on the Windows10(64-bit)&OpenGL.
Result: It's not happen the issue.
This issue will happen only Android or Adreno 540? 

PPSSPP Ver.：1.9.3-662
OS：Windows10 (64-bit) Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RX580
Resolution：2560×1440
RAM：16GB

**Comment by nassau-tk** [comment]
@unknownbrackets 
@hrydgard 

Would you reproduce or cheked the issue?
If you want another dump.
I will try it.
Thank you.

**Comment by nassau-tk** [comment]
@unknownbrackets 
@hrydgard 

It may be a problem of a specific device.

Test report...below.
SONY Xperia SO-02K (Snapdragon835&Adreno540) is not drawing the window.
HUAWEI Mediapad M5 Lite (Kirin710) is drawing the window.
And
Windows10(64-bit Ryzen3800X & RX5700XT)  is drawing the window.

But,Xperia SO-02K (Snpdragon835 & Adreno540) is drawing the window by backend of Vulkan.

**Comment by nassau-tk** [comment]
@unknownbrackets 
@hrydgard 

Oh....
@unknownbrackets  said "The dump seems to be from a different place (the character select):"

I understood it means **now**.

I don't know why it can't recording GE Dump the screen of issue point..
But,**SO-02K** can't recording the screen of issue point.
The dump will get screen of Just before one.
I will attached mp4 data.
If this can be helpful.
I'll be happy.

[2020-08-30-17-44-37_screenRecording.zip](https://github.com/hrydgard/ppsspp/files/5146527/2020-08-30-17-44-37_screenRecording.zip)

**Comment by nassau-tk** [comment]
This issue happen on Galaxy S20 too.

Android PPSSPP Ver.：1.10.3-1234
OS：Android 10.0
DeviceName：Samusung Galaxy S20 / SC-51A
CPU：Snapdragon865（Octa-core）
GPU：Adreno 650
Resolution：3200 x 1440 (Max)
RAM：12GB
ROM：128GB
ExternalStrage：microSDXC 512GB

**Comment by hrydgard** [comment]
This kind of thing is almost certainly some tiny difference in depth clipping or similar. 

I have some beginning plans to rework the depth stuff across all backends, but it won't happen before the release of 1.11. In the meantime, play with Vulkan I guess.

**Comment by nassau-tk** [comment]
! "Depth / Z" ! OK I See!

**Comment by hrydgard** [comment]
Well, doesn't mean it's depth-texture related - could be though, of course. If it's fixed in Vulkan and not in GL, it's likely indeed related to #13256 .

**Comment by nassau-tk** [comment]
@hrydgard 

This issue will solved by v1.10.3-1395-g1ba290a45.

[Window appear correctly on OpenGL]
![image](https://user-images.githubusercontent.com/48179091/103165429-21218200-485b-11eb-9a58-575069697b6c.png)

**Comment by hrydgard** [comment]
Oh, interesting...

**Comment by unknownbrackets** [comment]
I guess that means it was either related to the depth hack (wrong game id?) or fixed by some earlier change.

-[Unknown]

**Comment by nassau-tk** [comment]
@hrydgard 
@unknownbrackets 

Oooops!!
Sorry!!
I misstook setting to backend!!

It's not solved yet.

**Comment by unknownbrackets** [comment]
At draw 381/779, it clears depth to 65439 (0.998535), which is outside minz/maxz - but throughmode is enabled.

Then it turns clear off (through kept on) and starts drawing the things that are missing using a `>=` depth test.  It's using the same depth value, but not via a clear.

The problem is that mobile GPUs especially have a bad habit of translating depth values differently in clear vs in drawing.  Because of this, it doesn't equal.

-[Unknown]

**Comment by hrydgard** [comment]
Maybe we should just stop using explicit clears when we know the depth value isn't 0.0 or 1.0, and instead fall back to draws...

**Comment by unknownbrackets** [comment]
Does this work any better now on the latest git builds?  It does seem to work fine on an Adreno 620.

-[Unknown]

**Comment by nassau-tk** [comment]
Yes, It will solved but It became FPS goes down every loading time.

Galaxy S20 Android 12
OpenGL &  Vulkan
v1.13.2-1900-g7c5ddcecb

**Comment by unknownbrackets** [comment]
Was the FPS better in v1.13.2-1881-g818849c4b?  If not, it'd help to narrow it down.  If yes, does lower rendering resolution make it a lot faster?

-[Unknown]

**Comment by nassau-tk** [comment]
The result is same .
Latest build and v1.13.2-1881-g818849c4b is same result.
They are goes down the FPS at every loading time both.
And same as lower rendering resolution too. 

Low Resolution & Latest
https://user-images.githubusercontent.com/48179091/201501493-009d8771-db46-468c-a020-913f59d7cb7b.mp4

**Comment by nassau-tk** [comment]
Low Resolution & v1.13.2-1881-g818849c4b

https://user-images.githubusercontent.com/48179091/201501603-3df850b5-fd71-4cb2-b3a9-2c3f8b4335c4.mp4

**Comment by unknownbrackets** [comment]
Okay, so it's not because of the fix - must be caused by some earlier change.  I wonder if it's even just caused by Android scoped storage...

-[Unknown]

**Comment by nassau-tk** [comment]
My iso stay on external SD.
Scoped Storage Fix ver will goes down the FPS at any loading time.

But, This one is worst...
