### ISSUE TITLE
The first trip ppsspp project report error, do not know how to solve? Please advise me

### ISSUE THREAD

**Issue by 846524417** [hrydgard/ppsspp#13123]
Download the project from GIT. According to the instructions, python 3 and Android studio are the latest on the official website. Then the SDK and NDK are also up-to-date according to the instructions, and cmake is also installed. Then run the project and report the following error. Ask God to help solve. thank you
![image](https://user-images.githubusercontent.com/51825152/87227175-b3c48680-c3cb-11ea-929d-d1a0f6a999ac.png)

![image](https://user-images.githubusercontent.com/51825152/87226678-f4220580-c3c7-11ea-85f4-063dda6f4f0d.png)

**Comment by 846524417** [comment]
![image](https://user-images.githubusercontent.com/51825152/87227187-d787cc80-c3cb-11ea-8261-1e456c6dc956.png)
![image](https://user-images.githubusercontent.com/51825152/87227190-deaeda80-c3cb-11ea-8693-c6c60d59c909.png)

**Comment by 846524417** [comment]
executing external native build for cmake D:\PPSSPP\ppsspp\CMakeLists.txt
Affected Modules: android

**Comment by hrydgard** [comment]
Weird, can't think of anything in particular that could cause this.

Could you try typing "git submodule update --init" in the ppsspp directory, just to rule out that explanation?

**Comment by 846524417** [comment]
Yes, I've also used the replay download project. Then all are initialized.

**Comment by 846524417** [comment]
D:\PPSSPP\ppsspp\CMakeLists.txt : C/C++ normalOptimized|armeabi-v7a : CMake Error at C:/Users/XXXX/AppData/Local/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "3" (found
  C:/Users/XXXX/AppData/Local/Microsoft/WindowsApps/python3.exe)
Call Stack (most recent call first):
  C:/Users/XXXX/AppData/Local/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  C:/Users/XXXX/AppData/Local/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindPythonInterp.cmake:152 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  ext/glslang/CMakeLists.txt:172 (find_package)

**Comment by hrydgard** [comment]
Hm, maybe try installing Python 3.8 from python.org ?

**Comment by 846524417** [comment]
I don't think this is the reason why Python 3.8 has been successfully installed
Is this version number wrong, because I click the instructions to get here.
![image](https://user-images.githubusercontent.com/51825152/87330373-130ccd00-c56b-11ea-9d9d-39c0afd84df0.png)

![image](https://user-images.githubusercontent.com/51825152/87330338-08523800-c56b-11ea-8601-c743da4d4530.png)

**Comment by 846524417** [comment]
Can someone help me with this? thank you

**Comment by unknownbrackets** [comment]
The cmake version should be correct, but the last one I saw it working for on Windows was 3.14.5.  The version of Python you're using should be working (from the Microsoft Store), I'm not sure why it's saying it detected Python 1.4.  That's very odd.

This link says to remove the CMakeCache.txt - maybe after installing/updating Python this didn't happen?
https://github.com/YosysHQ/nextpnr/issues/214

https://github.com/ms-iot/ROSOnWindows/issues/124

Sounds like the "found" message from CMake can be a lie.

-[Unknown]

**Comment by 846524417** [comment]
Do you mean CMakeCache.txt Delete the file and update it again?

**Comment by unknownbrackets** [comment]
Yes.

-[Unknown]

**Comment by 846524417** [comment]
I'll do what you say CMakeLists.txt After the file is deleted again, download it from git, but it still doesn't work. The same mistake. I see a lot of people on the forum have this mistake. Did they solve it?

**Comment by unknownbrackets** [comment]
Are there still build issues here?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Comment by Hidte09** [comment]
In Android studio; 
![Uploading c++ error.png…]()
When trying to Change the build variant to "normalOptimized" then "c++ configuration error" occurred.
Like this:
C/C++ Configuration Problem

FRESH PSP IMPORT.android.main | vrDebug|

arm64-v8a

Compiler exited with error code 1:

C:\Users\hidte\AppData\Local\Android\Sdk\ndk\

21.4.7075529\toolchains\/lvm\prebuilt\windows-x

86_64\bin\clang++.exe -xc++ --target-aarch64-none-linux-android21

--gcc-toolchain= C:/Users/hidte/AppData/Local/A

ndroid/Sdk/ndk/21.4.7075529/toolchains/llvm/pre

built/windows-x86_64

**Comment by Hidte09** [comment]
FRESH_PSP_IMPORT.android.main | normalDebug | arm64-v8a Compiler exited with error code 1: C:\Users\hidte\AppData\Local\Android\Sdk\ndk\21.4.7075529\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe -xc++ --target=aarch64-none-linux-android21 --gcc-toolchain=C:/Users/hidte/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/hidte/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot "-DASSETS_DIR=\"C:/Program Files (x86)/PPSSPP/share/ppsspp/assets/\"" -DENABLE_OPT=0 -DGLSLANG_OSINCLUDE_UNIX -DMOBILE_DEVICE -DPNG_ARM_NEON_OPT=0 -DUSING_GLES2 -D__STDC_CONSTANT_MACROS "-ID:/FRESH PSP IMPORT/ext/glslang" "-ID:/FRESH PSP IMPORT/ext/glew" "-ID:/FRESH PSP IMPORT" "-ID:/FRESH PSP IMPORT/android/.cxx/Debug/c1t714x6/arm64-v8a/include" -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -std=gnu++17 -O0 -fno-limit-debug-info -g -D_DEBUG -fPIC -Wno-nullability-completeness -Wno-tautological-pointer-compare -Wno-deprecated-register -Wformat -Wno-multichar -fsigned-char -fno-strict-aliasing -Wall -Wuninitialized -Wunused -Wunused-local-typedefs -Wunused-parameter -Wunused-value -Wunused-variable -Wno-reorder -fno-rtti -fno-exceptions -std=c++11 -Winvalid-pch -Xclang -include-pch -Xclang "D:/FRESH PSP IMPORT/android/.cxx/Debug/c1t714x6/arm64-v8a/ext/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx.pch" -Xclang -include -Xclang "D:/FRESH PSP IMPORT/android/.cxx/Debug/c1t714x6/arm64-v8a/ext/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx" -fpch-preprocess -v -dD -E Android (7019983 based on r365631c3) clang version 9.0.9 (https://android.googlesource.com/toolchain/llvm-project a2a1e703c0edb03ba29944e529ccbf457742737b) (based on LLVM 9.0.9svn) Target: aarch64-none-linux-android21 Thread model: posix InstalledDir: C:\Users\hidte\AppData\Local\Android\Sdk\ndk\21.4.7075529\toolchains\llvm\prebuilt\windows-x86_64\bin Found candidate GCC installation: C:/Users/hidte/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/aarch64-linux-android\4.9.x Selected GCC installation: C:/Users/hidte/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/aarch64-linux-android/4.9.x Candidate multilib: .;@m64 Selected multilib: .;@m64 "C:\\Users\\hidte\\AppData\\Local\\Android\\Sdk\\ndk\\21.4.7075529\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++.exe" -cc1 -triple aarch64-none-linux-android21 -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name compiler-file3315035334730045207 -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -relaxed-aliasing -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu generic -target-feature +neon -target-abi aapcs -mllvm -aarch64-fix-cortex-a53-835769=1 -fallow-half-arguments-and-returns -dwarf-column-info -debug-info-kind=standalone -dwarf-version=4 -debugger-tuning=gdb -v -ffunction-sections -fdata-sections -resource-dir "C:\\Users\\hidte\\AppData\\Local\\Android\\Sdk\\ndk\\21.4.7075529\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\9.0.9" -D "ASSETS_DIR=\"C:/Program Files (x86)/PPSSPP/share/ppsspp/assets/\"" -D ENABLE_OPT=0 -D GLSLANG_OSINCLUDE_UNIX -D MOBILE_DEVICE -D PNG_ARM_NEON_OPT=0 -D USING_GLES2 -D __STDC_CONSTANT_MACROS -I "D:/FRESH PSP IMPORT/ext/glslang" -I "D:/FRESH PSP IMPORT/ext/glew" -I "D:/FRESH PSP IMPORT" -I "D:/FRESH PSP IMPORT/android/.cxx/Debug/c1t714x6/arm64-v8a/include" -D ANDROID -D _FORTIFY_SOURCE=2 -D _DEBUG -D ___CIDR_DEFINITIONS_END -isysroot C:/Users/hidte/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot -internal-isystem C:/Users/hidte/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1 -internal-isystem C:/Users/hidte/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/local/include -internal-isystem "C:\\Users\\hidte\\AppData\\Local\\Android\\Sdk\\ndk\\21.4.7075529\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\9.0.9\\include" -internal-externc-isystem C:/Users/hidte/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/aarch64-linux-android -internal-externc-isystem C:/Users/hidte/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include -internal-externc-isystem C:/Users/hidte/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include -O0 -Wformat -Wno-nullability-completeness -Wno-tautological-pointer-compare -Wno-deprecated-register -Wformat -Wno-multichar -Wall -Wuninitialized -Wunused -Wunused-local-typedefs -Wunused-parameter -Wunused-value -Wunused-variable -Wno-reorder -Winvalid-pch -std=c++11 -fdeprecated-macro -fdebug-compilation-dir "D:\\FRESH PSP IMPORT\\android\\.cxx\\Debug\\c1t714x6\\arm64-v8a" -ferror-limit 19 -fmessage-length 0 -stack-protector 2 -fno-rtti -fobjc-runtime=gcc -fdiagnostics-show-option -dD -include-pch "D:/FRESH PSP IMPORT/android/.cxx/Debug/c1t714x6/arm64-v8a/ext/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx.pch" -include "D:/FRESH PSP IMPORT/android/.cxx/Debug/c1t714x6/arm64-v8a/ext/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx" -o - -x c++ "C:\\Users\\hidte\\AppData\\Local\\Temp\\compiler-file3315035334730045207" clang -cc1 version 9.0.9 based upon LLVM 9.0.9svn default target x86_64-w64-windows-gnu error: unable to read PCH file D:/FRESH PSP IMPORT/android/.cxx/Debug/c1t714x6/arm64-v8a/ext/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx.pch: 'No such file or directory' ignoring nonexistent directory "C:/Users/hidte/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include" #include "..." search starts here: #include ...> search starts here: D:/FRESH PSP IMPORT/ext/glslang D:/FRESH PSP IMPORT/ext/glew D:/FRESH PSP IMPORT D:/FRESH PSP IMPORT/android/.cxx/Debug/c1t714x6/arm64-v8a/include C:/Users/hidte/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1 C:/Users/hidte/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/local/include C:\Users\hidte\AppData\Local\Android\Sdk\ndk\21.4.7075529\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\9.0.9\include C:/Users/hidte/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/aarch64-linux-android C:/Users/hidte/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include End of search list. 1 error generated. 
![IMG_20230223_162823](https://user-images.githubusercontent.com/124633547/220887837-9d3a87d3-3ae6-4c8d-b2c7-7a90bc96c3d0.png)
