### ISSUE TITLE
Buffered render issue with PowerVR SGX 540, (updated)

### ISSUE THREAD

**Issue by vontman** [hrydgard/ppsspp#1313]
let the screenshots describe the problem
off
![Buffered Render Off 2 ](https://f.cloud.github.com/assets/4175383/388847/31e02b96-a6e7-11e2-8654-4a07ceb9f9b5.png)

on
![Buffered Render On 2 ](https://f.cloud.github.com/assets/4175383/388849/31fc305c-a6e7-11e2-803c-7d3c505191a8.png)

off
![Buffered Render Off](https://f.cloud.github.com/assets/4175383/388848/31f27724-a6e7-11e2-9fec-99ff54d21445.png)

on
![Buffered Render On](https://f.cloud.github.com/assets/4175383/388857/32876636-a6e7-11e2-8b2e-74af47b68651.png)

off
![Buffered Render On 3 ](https://f.cloud.github.com/assets/4175383/388851/3232867a-a6e7-11e2-8a6f-b81f6591a90c.png)

on
![Buffered Render Off 3 ](https://f.cloud.github.com/assets/4175383/388853/32545296-a6e7-11e2-99f6-bcdfb120bdad.png)

other one i found Dissidia Final Fantasy, and dissidia 012

on
https://f.cloud.github.com/assets/4175383/429926/e3487bd8-ae56-11e2-9487-3f022301b81e.png

off
https://f.cloud.github.com/assets/4175383/429925/df73033e-ae56-11e2-9702-36ebc6720ef3.png

Tested on galaxy tab 2 7.0 and galaxy nexus
this is becoming really annoying @_@

**Comment by sum2012** [comment]
My friend still have problrem have this (PPSSPP v1.0-101-g1170331)
https://cloud.githubusercontent.com/assets/2177532/3868276/d6bf2a44-2031-11e4-877c-eb52858a9c9f.jpg

https://cloud.githubusercontent.com/assets/2177532/3471442/c4d9f0b6-02c2-11e4-886a-80959857c9fd.jpg

**Comment by unknownbrackets** [comment]
And that's definitely with all speedhacks off (disable alpha test and disable slower effects must not be on, buffered rendering must be used, block transfers on, etc.)?  Because that effect definitely requires all of that.

Even so, this is PowerVR 5, so I certainly don't trust it to be able to do the effects correctly in the shader anyway.

-[Unknown]

**Comment by sum2012** [comment]
He used Texture coord speedhack and Timer hack .
I have told him to re-test again

**Comment by sum2012** [comment]
He turn off that two hack still same picture.
PPSSPP version v1.0-101-g1170331

**Comment by unknownbrackets** [comment]
I would not be shocked if PowerVR 544 was not properly calculating the result of  `max(x, y)`, but don't have a device to verify this with.  That affect uses a max equation.

-[Unknown]

**Comment by unknownbrackets** [comment]
I noticed that SGX 540 devices, specifically, are giving us quite a lot of shader compilation failures even for simple (as well as complex) shaders, like this one:

```
#version 100
precision lowp float;
 varying vec4 v_color0;
 varying vec3 v_color1;
void main() {
  vec4 s = vec4(v_color1, 0.0);
  vec4 v = v_color0  + s;
  gl_FragColor = v;
}
```

This is already software transform, and there's no error detail - just "Compile failed."  My thought is, it may be simply running out of memory or something.  It should still be showing a message on screen, though.

I wonder if that's related.  We might even draw things wrong by not having space to upload the texture.

-[Unknown]

**Comment by sum2012** [comment]
Can we make this test shader program in the "developer tools" ?
Show in the screen of the error whether it compile failed

**Comment by unknownbrackets** [comment]
Well, the thing is, the UI basically already uses a shader that is very similar.  So my point is, it must not be that this shader *always* fails, but rather that it's failing *sometimes*.  And sometimes probably means memory/resources.

-[Unknown]

**Comment by sum2012** [comment]
I see

**Comment by shinemu** [comment]
Please forgive me, i didn't know about that :( btw i want to report that there's no animation ( black screen) on queen blade spectral chaos on dev working version but work fine on stable 1.0.1.0 and most of the game got sound glitch or unclear sometimes ( stable and dev )

**Comment by sum2012** [comment]
@shinemu 
Try to find out that which version start to broke (no animation)in  http://buildbot.orphis.net/ppsspp/

**Comment by shinemu** [comment]
@sum2012 i try all build from latest to build 1.1.123 and i found the problem start at build 1.1.158 but it was fine on 1.1.152

**Comment by shinemu** [comment]
Sorry typo..i mean i try all build from latest to build 1.0.1-123 and found the problem start at build 1.0.1-158 but works fine on 1.0.1-152

**Comment by sum2012** [comment]
That mean v1.0.1-152-g9db4c5f is good
v1.0.1-158-g33b291a bad

**Comment by sum2012** [comment]
@shinemu  I need you test 4 times build from my build to easier fix.
Does this work ?
https://drive.google.com/file/d/0B3OaSdeV0L8kVzYxU0tBOVFqczg/view?usp=sharing

**Comment by shinemu** [comment]
@sum2012 gladly ^_^ and i'll come back with the report right away

**Comment by shinemu** [comment]
![tmp_11300-screenshot_2015-07-09-17-58-40626649139](https://cloud.githubusercontent.com/assets/11956166/8605156/7f205a8c-26ad-11e5-89aa-b5c73e302e89.jpg)
![tmp_11300-screenshot_2015-07-09-17-58-57-883956894](https://cloud.githubusercontent.com/assets/11956166/8605168/8cf618ae-26ad-11e5-9313-d564441c2113.jpg)
![tmp_11300-screenshot_2015-07-09-17-57-19-183537329](https://cloud.githubusercontent.com/assets/11956166/8605176/9725bffa-26ad-11e5-9079-ddbf9dd0ecf0.jpg)
![tmp_11300-screenshot_2015-07-09-17-59-13-1859232061](https://cloud.githubusercontent.com/assets/11956166/8605179/9efb2a80-26ad-11e5-8b93-9b2cd624faa3.jpg)

**Comment by sum2012** [comment]
@shinemu I mean I will make 4 build then you need test them.
Anyway,seem bad last build.
Here is another build test.
https://drive.google.com/file/d/0B3OaSdeV0L8kTmxWRVQwX1pPWk0/view?usp=sharing

**Comment by shinemu** [comment]
@sum2012 aye aye sir ^_^ btw how bout super robot wars Z 1 and 2 ? Do we have a fix too?

**Comment by sum2012** [comment]
@shinemu No,we don't have a fix for super robot wars Z 1 and 2
Anyway , what is this build result ?
https://drive.google.com/file/d/0B3OaSdeV0L8kTmxWRVQwX1pPWk0/view?usp=sharing

**Comment by shinemu** [comment]
@sum2012 understood sir..second build have the same problem with first,okey i'll test the third ^_^

**Comment by sum2012** [comment]
@shinemu ok.How about this build ?
https://drive.google.com/file/d/0B3OaSdeV0L8kTnFkd2dhSjd6blU/view?usp=sharing

**Comment by shinemu** [comment]
@sum2012 the third have the same issue too sir,btw is there any connection with the gpu-blend Use framebuffer fetch more and on more devices that have been applied on ver 1.0.1-158-g33b291a sir? I'll test the fourth right away sir

**Comment by shinemu** [comment]
![tmp_16327-screenshot_2015-07-10-05-28-01-693328193](https://cloud.githubusercontent.com/assets/11956166/8608450/37d5b6e6-26c5-11e5-98d1-c3e3312cf4fb.jpg)

![Uploading tmp_16327-Screenshot_2015-07-10-05-30-431014147793.jpg…]()
The fourth working good sir! ^_^ even the sound are clearer than before

**Comment by shinemu** [comment]
![tmp_16327-screenshot_2015-07-10-05-30-43945491200](https://cloud.githubusercontent.com/assets/11956166/8608517/d647bad6-26c5-11e5-8c31-0f4ab827c703.jpg)

**Comment by shinemu** [comment]
![tmp_16327-screenshot_2015-07-10-05-30-28-401864585](https://cloud.githubusercontent.com/assets/11956166/8608525/f0b482fa-26c5-11e5-8d4c-44c5d963423b.jpg)

**Comment by sum2012** [comment]
I have some confuse.Please confirm again.Thanks.
good:
https://drive.google.com/file/d/0B3OaSdeV0L8kTnFkd2dhSjd6blU/view?usp=sharing 
bad:
https://drive.google.com/file/d/0B3OaSdeV0L8kTmxWRVQwX1pPWk0/view?usp=sharing

**Comment by shinemu** [comment]
@sum2012 confirm,the good one is your fourth upload ( ver 1.0.1-118 on your good upload https://drive.google.com/file/d/0B3OaSdeV0L8kTnFkd2dhSjd6blU/view?usp=sharing ) and the one that are have the issue or bad ( ver 1.0.1-119 on your bad upload ) btw can we have this fix on next dev update?

**Comment by unknownbrackets** [comment]
If #7567 is causing problems, it probably means EXT_shader_framebuffer_fetch is not working right on that device or driver, possibly only with certain blending modes.  We can blacklist older devices or something, but unfortunately this may break other effects that started working correctly due to that change on the same devices.

-[Unknown]

**Comment by shinemu** [comment]
@Unknownbrackets So that's why the same issue happen on ios device too..and that means no fix for the next dev updates sir unknown?

**Comment by sum2012** [comment]
@unknownbrackets git bisect result
![1](https://cloud.githubusercontent.com/assets/2177532/8617955/b4832a18-273b-11e5-95b6-a16778b930a0.png)
this commit https://github.com/unknownbrackets/ppsspp/commit/2344760018f995a4195d7d1daffd95995ac6828c

**Comment by hrydgard** [comment]
Seems clear we need to disable it on some devices. The question is which ones..

**Comment by sum2012** [comment]
EXT_shader_framebuffer_fetch is not PowerVR devices only ?

**Comment by hrydgard** [comment]
It's also available on Tegra 3 and Tegra 4, but not on X1/K1.

**Comment by unknownbrackets** [comment]
And also some newer Mali devices I believe.  And there's no reason to expect it doesn't work properly on PowerVR 6.

But I also just want to say again that people should not be surprised if disabling EXT_shader_framebuffer_fetch on PowerVR 5 devices also breaks a bunch of effects in some games.  I'm pretty sure I read reports of that change improving things.  There's probably some case the driver handles wrong or where overlap doesn't work the way we want.

-[Unknown]

**Comment by sum2012** [comment]
@shinemu I have tried disable EXT_shader_framebuffer_fetch.
Does this build ok ? (v1.01-733m)
https://drive.google.com/file/d/0B3OaSdeV0L8kcTYwV0J5ZS1qSmc/view?usp=sharing

**Comment by shinemu** [comment]
@sum2012 still have the issue sir..same with bad build

**Comment by shinemu** [comment]
![tmp_3877-screenshot_2015-07-11-05-54-39-77167313](https://cloud.githubusercontent.com/assets/11956166/8630556/76657550-2791-11e5-8303-81c89bef837b.jpg)
![tmp_3877-screenshot_2015-07-11-05-54-41579238891](https://cloud.githubusercontent.com/assets/11956166/8630557/82aefad4-2791-11e5-911b-22c5ef8a0b03.jpg)

**Comment by sum2012** [comment]
@shinemu Sorry,I forget another change.
Can you try again ? Thanks.(v1.0.1-733-m2)
https://drive.google.com/file/d/0B3OaSdeV0L8kZEtBV3JheDRxcEk/view?usp=sharing

**Comment by shinemu** [comment]
@sum2012 reporting,sorry sir but the problem still like v1.0.1-733m

**Comment by sum2012** [comment]
@shinemu I try to revert all code from #7567 
Can you try again ? Thanks. (ppssppv1.0.1-733m3)
https://drive.google.com/file/d/0B3OaSdeV0L8kMkdHdXpoZkVQYmM/view?usp=sharing

**Comment by shinemu** [comment]
@sum2012 reporting...it works sir! Good build ^_^ thank you sir

**Comment by sum2012** [comment]
@shinemu Thanks.Let me record what code I have changed.
https://github.com/sum2012/ppsspp/commit/47c9cf7a3ebd5ed3edfa125540b2b97e3ce2e22c

**Comment by sum2012** [comment]
@shinemu I try to just add back detection of EXT_shader_framebuffer_fetch
No other function change.
Does this still work ? Thanks. (ppssppv1.0.1-734-m1)
https://drive.google.com/file/d/0B3OaSdeV0L8kRVhSUWJJSWpMeUU/view?usp=sharing

**Comment by shinemu** [comment]
@sum2012 testing queen blade spectral chaos also whole bunch of heavy render games and it works without any problem sir,good build sir! ^_^

**Comment by sum2012** [comment]
Thanks,Now the code change
https://github.com/sum2012/ppsspp/commit/97ed2f5619feb0a9174663eb35483e8f6202bc33

**Comment by sum2012** [comment]
Hm,the last part of code should be safe
https://github.com/sum2012/ppsspp/commit/f97e07fc4e847e8ed32e9dee32dff922ba933c18

**Comment by sum2012** [comment]
@shinemu I try to enable back code in GE_DSTBLEND_DOUBLEINVSRCALPHA change
Does this still work ? Thanks.(ppssppv1.0.1-734-m2)
https://drive.google.com/file/d/0B3OaSdeV0L8kbFM2dFRRWnMxNmc/view?usp=sharing

**Comment by shinemu** [comment]
@sum2012 I'm sorry sir but it's not working also the sound a bit unclear

**Comment by sum2012** [comment]
@shinemu I try to enable back code in the middle change
 Does this work ? Thanks.(ppssppv1.0.1-734-m3)
https://drive.google.com/file/d/0B3OaSdeV0L8kVUp1OHpDNFNtX0U/view?usp=sharing

**Comment by shinemu** [comment]
@sum2012 it works sir ^_^

**Comment by sum2012** [comment]
Hm.Now the working code change is
https://github.com/sum2012/ppsspp/commit/3b1da697342ac46d003d5b75a4ef4534e8714021

**Comment by shinemu** [comment]
@sum2012 thank you sir for bringing the fix so we can follow the update without worries but if anything happen in the future may I still allowed to report? Also I would like to thanks to sir hrydgard for his awesome ppsspp emu and sir unknown too ^_^ cheerrss !

**Comment by sum2012** [comment]
@shinemu you are lucky to report the problem in time before the next major version

**Comment by sum2012** [comment]
@shinemu What is the game name in 
https://cloud.githubusercontent.com/assets/11956166/8630556/76657550-2791-11e5-8303-81c89bef837b.jpg ?

**Comment by shinemu** [comment]
@sum2012 actually I already report the issue on that game on iphone from cydia about update ver 1.0.1-411 if I not mistaken but no luck T_T and I change to android hoping that it will be reply and here it is...the game title is Queen Blade Spectral Chaos

**Comment by sum2012** [comment]
I take a search,I think the game name should be
Queen's Blade - Spiral Chaos but there is no that picture in the beginning.
Do the gameID is ULJS00190 ?

**Comment by shinemu** [comment]
Sorry my mistake,the title is queen gate spiral chaos ULJS00377000

**Comment by asbel123** [comment]
i got same problem differnce speed on gpu is mali and anderno look at tales of enternia on samsung galaxy s4 19005 is it too slow to play that game i tried huawei ascend g730 its fullspeed on that game with 2x uspscale maybe mail 400 good for tales of enternia. snapdragon has problems even new version of ppsspp. i tried huawei ascend g730  for tales of enternia u get black screen just world map u can see everything just only background is black its a problem is opengl 2.0 i tried new mail samsung galaxy s6 edge no black screen on my world map its a problem is opengl 2.0 not 3.0.

**Comment by sum2012** [comment]
@shinemu No problem on my phone
PowerVR Rougue G6430

**Comment by sum2012** [comment]
@shinemu Also no problem on my mother phone
Adrene (TM) 305

**Comment by shinemu** [comment]
@sum2012 same here sir ^_^ powerVR g6430

**Comment by shinemu** [comment]
@sum2012 i am sorry sir but why the fix haven't sign or applied on new update ver 1.0.1-757 if it concentrate on something more important and i will gladly wait

**Comment by unknownbrackets** [comment]
Might be an issue in a specific driver version then?  Does it show any useful version numbers in the GL info?

-[Unknown]

**Comment by hrydgard** [comment]
If even it's the same GPU but differently broken on different driver versions, getting it right will not be possible without buying one of every phone in the universe...  Quite hopeless.

I would like to know what games actually got fixed by this feature (that we are disabling here to get it to work on shinemu's phone) though, given the problems we've seen with it so far the benefits better be worth all the trouble....

**Comment by shinemu** [comment]
@sum2012 sir sum can you fix playing queen gate spiral chaos on latest
ppsspp version too? It was faster enough with just 1 frameskip on auto,i
use to set in 3 before...many thanks sir ^_^

**Comment by sum2012** [comment]
@shinemu  
https://drive.google.com/file/d/0B3OaSdeV0L8kNktZNHdaRk1XZTA/view?usp=sharing
The hack version based on v1.0.1-830-gc671b07

**Comment by shinemu** [comment]
@sum2012 good build as always sir ^_^ btw why can't i see your build on
orphis or why sir hrydgard or unknownbracket not implement the fix base on
yours ? Forgive me but i just want to participate too even just a tester,
i'm not touching anymore of computer language since 1990 ( turbo
pascal,cobol,dos era ) Lol...thanks sir sum and please do a fix too when
update reaching final stage,cheerss

**Comment by sum2012** [comment]
I find my code also fix graphic of "Tactics Ogre: Let Us Cling Together " of my phone
#7819

**Comment by shinemu** [comment]
@sum2012 is it the same build you gave me sir?

**Comment by sum2012** [comment]
@shinemu no, update a bit ( based on v1.0.1-865-g825662d)

**Comment by shinemu** [comment]
@sum2012 i see...can i try too?

**Comment by sum2012** [comment]
@shinemu  Here
https://drive.google.com/file/d/0B3OaSdeV0L8kdjBDUlZuZ0tKMkU/view?usp=sharing

**Comment by shinemu** [comment]
@sum2012 thanks you sir ^_^

**Comment by sum2012** [comment]
@shinemu you might be happy as my code has merged

**Comment by shinemu** [comment]
@sum2012 Awesome sir,it works! Thanks again sir sum and sir hrydgard ^_^ me
and other users owe you guys,god bless you sir

**Comment by shinemu** [comment]
@sum2012 reporting sir...ppsspp forced close and back to home screen while
loading naruto 3 save file,it only work from new game and i try both
install data and not but still have same result when continuing,the same
issue with srw Z 2 the app just forced close when i try opening game image..

**Comment by sum2012** [comment]
@shinemu 
For naruto 3
please zip the save folder,then upload to
http://drive.google.com/drive/

**Comment by shinemu** [comment]
It works with 1.0.1-865

**Comment by sum2012** [comment]
@shinemu What game do you talking "It works with 1.0.1-865" ?
Also ,what is last work version in http://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by shinemu** [comment]
Slow connection here sir,the save i use was a new save sir nothing unusual
i think

**Comment by shinemu** [comment]
Both game sir naruto heroes 3 and super robot wars z 2....ok sir i'll try
to found which the last update works ^_^

**Comment by shinemu** [comment]
@sum2012 i just try till 1.0.1 865 from orphis but the result is same also
cause com.ppsspp stop working so i install your 1.0.1 865m and then
overwrite with new install from latest update and it works..i don't know
how it can be but now works fine for naruto heroes 3 ^_^'

**Comment by sum2012** [comment]
@shinemu I want to clearify.
Do neweset version eg: v1.0.1-2790-g48db42b not work ?

**Comment by shinemu** [comment]
@sum2012 update ver 1.0.2790 working sir,i test without overwrite and doing
multiple fresh install..but other except 1.0.1 -865m not working

**Comment by sum2012** [comment]
@shinemu As I said before https://github.com/hrydgard/ppsspp/issues/1313#issuecomment-142915241
My code has merged in v1.0.1-2763-g5d7c4dd.
So that I think that no more issue ?

**Comment by shinemu** [comment]
@sum2012 no sir no issue playing queen gate and many other games only issue
on naruto 3 and srw z 2 but it already solved now with latest update ^_^
thanks again sir

**Comment by zminhquanz** [comment]
PowerVR issue aspect like Dissidia 012 Final Fantasy

**Comment by zminhquanz** [comment]
#7740

**Comment by unknownbrackets** [comment]
This is a pretty long issue - and I suspect some of the issues have been improved over time.  Is anyone able to summarize the major issues remaining with these GPUs?

-[Unknown]

**Comment by hrydgard** [comment]
Most likely the GPUs are getting rarer and rarer...

**Comment by unknownbrackets** [comment]
There haven't been any updated reports here in 2 years, so I'm closing this issue.  There have been a lot of changes in the way graphics are handled and things may have improved.  But also, these devices are getting rarer indeed.

-[Unknown]
