### ISSUE TITLE
[iOS13 -> iOS14] Some games display incorrectly in iOS14 but were perfect in iOS13 

### ISSUE THREAD

**Issue by junyang95** [hrydgard/ppsspp#13451]
### What happens?
After I upgrade to iOS14, I found some games can not display correctly, but were running perfectly on iOS13.

Here are some screenshots:

![WechatIMG1320](https://user-images.githubusercontent.com/28535071/93715407-af6ed380-fb9b-11ea-9c77-62c3b68add5f.jpeg)
![WechatIMG1319](https://user-images.githubusercontent.com/28535071/93715413-b72e7800-fb9b-11ea-9378-7f84d8036e8c.jpeg)
![WechatIMG1318](https://user-images.githubusercontent.com/28535071/93715419-bdbcef80-fb9b-11ea-982f-512fd000a5ea.jpeg)

### What *should* happen?
I used IR interpreter on both ios 13 and ios 14, as well as the same ppsspp version 1.10.3.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
iphone 8p, ios 14.0 and ios 13.7, 1.10.3-712

**Comment by yoshisuga** [comment]
Using the IR interpreter on iOS 14, I found that movies aren't playing correctly - might be an ffmpeg library issue?
![IMG_DD062D9A500A-1](https://user-images.githubusercontent.com/564774/93749106-0d4bed00-fb95-11ea-9ddb-329417637374.jpeg)

**Comment by sizmos** [comment]
I am also experiencing the same thing with gta vcs on iOS 14 where the mini map is not showing, making the game no longer playable
Using IR interpreter also as dynarec no longer working on iOS 14
Running on an iPad Pro 11 and have tried every combination of graphics settings
The map works when going inside a building as there is no base texture and it is transparent
![D689044E-E764-4C06-ADCA-DDA66B8CB971](https://user-images.githubusercontent.com/9097242/94914369-4158d380-04ee-11eb-8c94-0f959b8e9a7b.png)

**Comment by SwiftBMan** [comment]
iphone7 iOS 14   
Running game crashes
iOS 14   iOS 14    iOS 14    iOS 14    iOS 14    iOS 14    iOS 14

**Comment by SwiftBMan** [comment]
ERR  [MEMMAP] vm_remap failed (1) - could not remap from 10b074000 (offset 0) of size 4000 to 0x100010000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x100810000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x101010000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x101810000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x102010000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x102810000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x103010000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x103810000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x104010000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x104810000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x105010000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x105810000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x106010000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x106810000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x107010000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x107810000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x108010000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x108810000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b078000 (offset 4000) of size 200000 to 0x10d000000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b078000 (offset 4000) of size 200000 to 0x10d800000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x10a010000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x10a810000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x10b010000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x10b810000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x10c010000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x10c810000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x10d010000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x10d810000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x10e010000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x10e810000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x10f010000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x10f810000
ERR  [MEMMAP] vm_remap failed (3) - could not remap from 10b074000 (offset 0) of size 4000 to 0x110010000
ERR  [SYSTEM] Exception handler not implemented on this platform, can't install

**Comment by hrydgard** [comment]
My current theory on this is that iOS 14 might not work correctly with memory mirrors, which is how we implemented the PSP's uncached memory space, which many games use to upload textures. We might have to use MASKED_PSP_MEMORY, for a small performance impact...

**Comment by leegendary813** [comment]
What should I do about this problem. Other people say it’s an ios 14 issue, and I’m not sure what to do. As you can see in the picture below you can’t see the character portraits to the top right, so I cannot see the character’s hp and sp levels making it hard to play the game. Also the buttons to attack, defend, etc. are gone because of these annoying squares. If there are any solutions please let me know

**Comment by leegendary813** [comment]
What should I do about this problem. Other people say it’s an ios 14 issue, and I’m not sure what to do. As you can see in the picture below you can’t see the character portraits to the top right, so I cannot see the character’s hp and sp levels making it hard to play the game. Also the buttons to attack, defend, etc. are gone because of these annoying squares. If there are any solutions please let me know 
![Uploading 861D9EA7-185C-4A49-87BD-9C2BE79986A8.png…]()

**Comment by hrydgard** [comment]
I don't know where you are getting your iOS builds of PPSSPP, but I made a change that should appear in new builds that might fix it. Possibly. Not sure :)

**Comment by sizmos** [comment]
I have tried the latest being https://p.xx.wtf/PPSSPP_v1.10.3-988-g624998bec.ipa which seems to be after the commit to master. However I am facing the following error when trying to boot up all games.
![6753B259-39A2-4003-B23A-652902F531B7](https://user-images.githubusercontent.com/9097242/96941440-293d0880-151e-11eb-88f9-db74c76376a7.png)

**Comment by butstevetho** [comment]
![IMG_0275](https://user-images.githubusercontent.com/11230616/97853807-e850ab00-1cf8-11eb-8768-84b966ef972d.PNG)

Having the same issues with P3P, HUD/GUI elements and text do not load within battles (or any 3D scenes that contain a HUD). iOS14, latest build of ppsspp via p.xx.wtf (v1.10.3-1099-g085900adb from 2nd of November)

I can confirm like many others, using Dynarec (JIT) causes PPSSPP to crash when you attempt to launch any game, forcing you to use either Interpreter or IR interpreter as the CPU Core.

**Comment by hrydgard** [comment]
Yeah, dynarec will probably never work again on iOS. Blame Apple.

**Comment by butstevetho** [comment]
> Yeah, dynarec will probably never work again on iOS without jailbreaks. Blame Apple.

Never say never! There was a time when it was generally known that you can never install an emulator on iOS without jailbreaking, but here we are! Anyways, my point here is I have faith in you ;)

Is this error occurring directly because of not using JIT? Ultra bummer, I switched to apple just when the party ended lol

**Comment by hrydgard** [comment]
No, I think this is some other change they've made that's affecting the emulator weirdly. I posted my theory a few posts above, and I'm gonna try to get a workaround in sometime soon - but my theory might be wildly wrong, we'll see.

**Comment by butstevetho** [comment]
> Don't go with Apple if you wanna emulate ;)

Work is the reason I went Apple. Anyway this isn't entirely accurate because between PPSSPP, Delta and Provenance, I can emulate nearly every game I want.

P3P is the only game giving me trouble. If you have something that needs to be tested via-a-vis ios14 bugs, I would be happy to put my device to use.

**Comment by sizmos** [comment]
I have just tested the latest build for iOS on iPad with gta vice city stories and it seems to show the intro screen, though after that everything is black. From the opening cutscenes to the actual gameplay. I can hear the audio, though that’s about it. As for the settings, everything is set to default except for the cpu core which I set to IR interpreter (interpreter also acts the same)

**Comment by hrydgard** [comment]
Oops, didn't mean to close this issue.

**Comment by hrydgard** [comment]
So there's a difference from previous builds?

**Comment by sizmos** [comment]
Yes, the last build I tested just crashed when opening
https://github.com/hrydgard/ppsspp/issues/13451#issuecomment-714824055

**Comment by hrydgard** [comment]
I guess that's some kind of progress then .. And I believe more in my theory - though I would have thought things would work now.

**Comment by sizmos** [comment]
Persona shows the intro screen, though goes to a black screen once it reaches the menu. I can hear the sounds for the menu options though

**Comment by hrydgard** [comment]
Okay, apparently for others the whole game worked before except the UI in battle?

**Comment by adampapadopoulos** [comment]
Yes that is the one I tested, might be worth comparing the settings for those it worked for

**Comment by sizmos** [comment]
Yes that is the one I tested, might be worth comparing the settings for those it worked for

**Comment by butstevetho** [comment]
> 
> 
> Persona shows the intro screen, though goes to a black screen once it reaches the menu. I can hear the sounds for the menu options though

I can confirm this is what happens on persona 3 portable.

Is it worth mentioning that ios14 had a bugfix update yesterday?

**Comment by butstevetho** [comment]
> Okay, apparently for others the whole game worked before except the UI in battle? Talking about Persona 3, of course.

Before this update, persona 3 appeared to work fine until the first battle, which looked like this:

![image](https://user-images.githubusercontent.com/11230616/97996741-6c359080-1de8-11eb-9703-8b32659545cf.jpeg)

Now the entire game is a black screen but audio and input still works. I also see some weird artifacts from time to time.

**Comment by hrydgard** [comment]
Okay, I think I'm gonna revert. I don't understand at all what's going on but it has to have something to do with the memory mirrors.

Trying to revive my old iPad Air to see if I can get iOS 14 on it...

**Comment by MCJD931** [comment]
I can add a little to this issue: I first encountered this issue when trying to use the teleporter in Persona 3 Portable, and noticed the texture for Tartarus was missing, when I actually teleported, the game crashed. I switched from IR Interpreter to Interpreter, and it allowed me to use the teleporter, but walking around the dungeon was laggy, and when i started a battle, the same issues shown here happened: Missing battle textures. I might wanna note that laggy dungeon/crash might just be a simultaneous entirely different issue, since no one else is mentioning it. But considering both issues revolve around the 3D parts of the game, I.E. dungeon exploring and battles, I doubt it.

**Comment by hrydgard** [comment]
Laggy/crash can just be results of using the IR Interpreter, it's considerably less mature than the JIT unfortunately and has some bugs left.

As for the graphics issue.. Still baffled on what could have changed between OS versions to cause this. After my previous tests, it doesn't seem to have anything to do with the memory mirrors. Maybe an obscure texture format we are using stopped working? Would be very weird though.

**Comment by byeblack** [comment]
But Apple introduced support for jit in iOS 14.2, I think ppsspp can also be updated to make jit work better.

**Comment by byeblack** [comment]
But Apple introduced support for jit in iOS 14.2, I think ppsspp can also be updated to make jit work better.


> Laggy/crash can just be results of using the IR Interpreter, it's considerably less mature than the JIT unfortunately and has some bugs left.
> 
> As for the graphics issue.. Still baffled on what could have changed between OS versions to cause this. After my previous tests, it doesn't seem to have anything to do with the memory mirrors. Maybe an obscure texture format we are using stopped working? Would be very weird though.

**Comment by hrydgard** [comment]
Of course it can, but is this something Apple accidentally exposed and will be taken away again, or is it something permanent? Either way, someone will have to do the work to integrate it into PPSSPP. I don't have an iOS 14 device at this time.

**Comment by MCJD931** [comment]
> Laggy/crash can just be results of using the IR Interpreter, it's considerably less mature than the JIT unfortunately and has some bugs left.
> 
> As for the graphics issue.. Still baffled on what could have changed between OS versions to cause this. After my previous tests, it doesn't seem to have anything to do with the memory mirrors. Maybe an obscure texture format we are using stopped working? Would be very weird though.

i don't think it's IR since i never had any problems before i updated to ios 14, and regular interpreter also gives lag, tho no crash. but i haven't been able to test these issues in 1.10.0+ because of the syntax error issue, so it's possible that they're two different issues, and also possible the laggy/crash one was fixed in 1.10.0+, but i can't tell whether this is true or not.

**Comment by hrydgard** [comment]
Syntax error issue?

**Comment by MCJD931** [comment]
i'm talking about this one
![image](https://user-images.githubusercontent.com/74071877/98622915-757a9d80-22bf-11eb-830b-e65bd2f4fb16.png)

**Comment by MCJD931** [comment]
i know it's a different issue it's just prevented me from testing things in 1.10+

**Comment by hrydgard** [comment]
Well you haven't reported that one, how am I supposed to know about it! Do you see that in the very latest builds? I fixed a related issue recently

**Comment by MCJD931** [comment]
it's the same issue as the one you recently fixed i just haven't had the chance to go on the newest builds because i'm on ios and i have no idea how to use the latest builds on ios

**Comment by butstevetho** [comment]
> it's the same issue as the one you recently fixed i just haven't had the chance to go on the newest builds because i'm on ios and i have no idea how to use the latest builds on ios

https://p.xx.wtf has the latest builds. You'll need to use something like AltStore to install the latest ppsspp .ipa builds on a non-jailbroken device.

**Comment by firelad97** [comment]
On v1.10.3-1306-g31648acc2 using A12 chip (XR) UI textures are still missing from battles and teleporter. This makes battles unplayable as I can't see HP/SP, but there are some text when selecting commands (especially when Skill is selected and I can see descriptions for skills, but not skill names).
![image0](https://user-images.githubusercontent.com/10987201/101700390-f1950c00-3a4a-11eb-999f-9144a4c1ed30.png)

**Comment by hrydgard** [comment]
I have a repro of this now. Does not repro on M1 which surprises me - I thought that it'd have the same driver as the iphone, but apparently not. 

The iPhone fails the GPU driver test in developer tools which might or might not be related.

No idea how to approach it though, haven't learned GPU debugging with apple tools yet :) But it's a start.

It might also be that the best plan is to use  Vulkan on Metal through MoltenVK instead of using OpenGL...

**Comment by hrydgard** [comment]
More experimental results:

* Taking a savestates with the broken graphics from an iPhone and rendering it on a Mac (or any other device) results in correct rendering. This means that textures have NOT been corrupted inside PSP RAM, at least.
* The broken graphics are drawn in a very simple way using alpha blending. Not even using stencil testing, so the above GPU driver bug result is probably irrelevant, and cached textures in iOS memory are somehow broken.
* Crisis Core does indeed not play video right. I get the same curious blocks of color but it's flickering according to the brightness of the video???? Feels more and more like texture upload going deeply wrong somehow but why the gradient?

This is so weird.

**Comment by stattix** [comment]
I honestly don’t know anything about these issues, but I was curious and found this info on another repo that may or may not help you guys in the right direction: 

“ It's broken on iOS due to the way the protected RAM exception handlers work there. It works on a thread basis and it's only covering exceptions for the emulation thread, not the GS thread. The GS threads tries to read stuff inside a location in RAM that has a protected section. The exception is raised, but it cannot be handled.

It's not super hard to fix, but I just gotta think of a nice way of doing it.” - jpd002

**Comment by hrydgard** [comment]
No, I don't think that's related unfortunately.

**Comment by hrydgard** [comment]
Finally found it. It's the "flat" modifier on shader in/out values. This seems to be completely broken in the iOS OpenGL ES driver.

Most games will function correctly without it, so I might just disable it on iOS for now...

**Comment by junyang95** [comment]
> Finally found it. It's the "flat" modifier on shader in/out values. This seems to be completely broken in the iOS OpenGL ES driver.
> 
> Most games will function correctly without it, so I might just disable it on iOS for now...

You are the best! Have you applied the disable and committed in the current repo?

**Comment by hrydgard** [comment]
No, I have not. I will soon.

**Comment by hrydgard** [comment]
@junyang95 workaround has been merged into master now.

**Comment by junyang95** [comment]
@hrydgard Appreciate!!

**Comment by yoshisuga** [comment]
Thank you @hrydgard ! Crisis Core does show the movies correctly now!

And here I was thinking that it was the ffmpeg library that was the issue - I'm glad I was completely off!

Thanks again!

**Comment by firelad97** [comment]
@hrydgard That update seemingly had removed the app folder normally accessible vila Files app. The only way to access it now is from a jailbroken device. Should there be a separate issue for that?

**Comment by hrydgard** [comment]
Nothing in that change has anything to do with folders. No idea what you mean

**Comment by DamnBoi706** [comment]
Can you give the ipa of that update I want to try right now see if it fix my issue?

**Comment by hrydgard** [comment]
https://p.xx.wtf/ by W.MS has fresh builds.

**Comment by hrydgard** [comment]
Closing since there's nothing more here to do - it's worked around in current PPSSPP releases and the bug has been reported to Apple. When they've fixed it, we can conditionally remove the workaround.
