### ISSUE TITLE
Final fantasy type-0 in cutscane OpenGL

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#14388]
### What happens?
Final fantasy type 0 bug face in cutscane
OpenGL
![Screenshot_20210417-222232](https://user-images.githubusercontent.com/78854859/115118219-5ac5f680-9fcc-11eb-9f0b-b0dff5a5788b.png)
![Screenshot_20210417-222236](https://user-images.githubusercontent.com/78854859/115118238-6b766c80-9fcc-11eb-89d3-48555d634422.png)
Vulkan
![Screenshot_20210417-222333](https://user-images.githubusercontent.com/78854859/115118277-99f44780-9fcc-11eb-91fe-7177ddfff5ac.png)
![Screenshot_20210417-222341](https://user-images.githubusercontent.com/78854859/115118287-a1b3ec00-9fcc-11eb-890c-d3ee3ba67f73.png)
for final fantasy type-0 I got a decrease in fps for vulkan.
#### What graphics card (GPU) or mobile phone model?
![Screenshot_20210417-223510](https://user-images.githubusercontent.com/78854859/115118413-3a4a6c00-9fcd-11eb-93a0-76cf7706c07f.png)
![Screenshot_20210417-223457](https://user-images.githubusercontent.com/78854859/115118419-3cacc600-9fcd-11eb-9245-7fb5bde40dfc.png)
![Screenshot_20210417-223446](https://user-images.githubusercontent.com/78854859/115118422-3dddf300-9fcd-11eb-9922-5146f72e9935.png)

#### Checklist

 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [x] Try resetting settings or older versions and include if the issue is related.
 - [x] Include logs or screenshots of issue.

**Comment by Panderner** [comment]
@IrfanH495 GE Dump?

**Comment by IrfanH495** [comment]
GE Dump
[recording (1).zip](https://github.com/hrydgard/ppsspp/files/6329652/recording.1.zip)

**Comment by Gamemulatorer** [comment]
I can't load your ge dump using ppsspp v1.11.3 playstore

**Comment by Gamemulatorer** [comment]
Ok I finally reproduce this on latest build of ppsspp
Only happen on OpenGL not in Vulkan my phone is Redmi Note 9 MTK CPU & Mali GPU
![Screenshot_2021-05-02-15-16-23-532_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116805489-88c54200-ab59-11eb-9a0c-df8cee441520.jpg)

**Comment by Panderner** [comment]
I tested for my Android phone (POCO M3) and my Windows PC

Android OpenGL: 
![IMG_20210502_154521](https://user-images.githubusercontent.com/37503397/116806463-be6d2980-ab5f-11eb-9c41-a91ac7cd82ad.jpg)

Windows OpenGL:
![Screenshot](https://user-images.githubusercontent.com/37503397/116806477-d2b12680-ab5f-11eb-9167-b8b4449c94a2.png)

**Comment by unknownbrackets** [comment]
She starts being drawn around 221/1015, but my top suspect for this artifacting is around 875/1015 where some bloom like thing happens.  More bloom at 949/1015.

It draws a shape to the bloom target at 96/1016, and this seems to make a reappearance as alpha/stencil at 875/1015, which might be unimportant or not.

The blending at 875/1015 is MAX(dst, src), but we support that on GLES3.

The later bloom finishes at 956/1015 and looks like this, which is suspiciously similar to the artifacting:
![Grayscale bloom of character](https://user-images.githubusercontent.com/191233/116822765-97016700-ab35-11eb-9171-5ea52faad13f.png)

It is drawn back to the screen at 957/1015, using texture map + standardalpha blend, and depal.  Depal is:
 * CLUT16, with a CLUT that's a linear ramp from 0->15 from transparent to opaque white, then random colors which are clearly uninvolved.
 * CLUT index & 0x0F (confirming only 0-15 are used.)
 * CLUT4444 and texture is also 4444.
 * No shifts or otherwise.

Given that we should be taking `int(color.r * 15.99) & 0x0F` (maybe we could fast path this), and it happens either using shader depal or a depal'd texture.

Maybe this will finally motivate me to add GE stepping to the web debugger so I can debug this on my phone...

-[Unknown]

**Comment by LunaMoo** [comment]
You could try https://github.com/hrydgard/ppsspp/issues/6349#issuecomment-280330408 this cheat, if it removes the layer, it's probably the blurr that's also buggy on PC(althrough on PC's it's only noticeably broken for Emina scenes).

**Comment by IrfanH495** [comment]
> You could try [#6349 (comment)](https://github.com/hrydgard/ppsspp/issues/6349#issuecomment-280330408) this cheat, if it removes the layer, it's probably the blurr that's also buggy on PC(althrough on PC's it's only noticeably broken for Emina scenes).

I tried, but it still happens.
that's a very good cheat.
cheat On
![Screenshot_20210503-041825](https://user-images.githubusercontent.com/78854859/116828234-97e2d900-abc7-11eb-981e-dfc92b963d36.png)
cheat Off
![Screenshot_20210503-041910](https://user-images.githubusercontent.com/78854859/116828259-c06ad300-abc7-11eb-9943-2a1fd97cd22b.png)

**Comment by Gamemulatorer** [comment]
Try to enable disable slower effects @IrfanH495

***Disable Slower Effects*** OFF
![Screenshot_2022-04-15-23-05-52-909_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/163587253-ea504c0d-1cb8-4d03-9059-e0efbb6cf11e.jpg)

***Disable Slower Effects*** ON
![Screenshot_2022-04-15-23-05-43-402_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/163587299-d05d8506-2bb6-400a-93a0-8fe9e58e4690.jpg)

**Comment by Gamemulatorer** [comment]
@IrfanH495 no feedback outdated?

**Comment by Gamemulatorer** [comment]
@IrfanH495 no feedback outdated?

**Comment by IrfanH495** [comment]
> Try to enable disable slower effects @IrfanH495
> 
> _**Disable Slower Effects**_ OFF ![Screenshot_2022-04-15-23-05-52-909_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/163587253-ea504c0d-1cb8-4d03-9059-e0efbb6cf11e.jpg)
> 
> _**Disable Slower Effects**_ ON ![Screenshot_2022-04-15-23-05-43-402_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/163587299-d05d8506-2bb6-400a-93a0-8fe9e58e4690.jpg)

thanks it's fixed now

**Comment by hrydgard** [comment]
Hm, if it looks right with "Disable slower effects ON", then there's still some sort of bug.

**Comment by IrfanH495** [comment]
Samsung m20
Exynos 7904
Mali-G71
Opengl
Disable Slower Effects OFF
![Screenshot_20220821-182558_PPSSPP](https://user-images.githubusercontent.com/78854859/185804820-7b0568ed-ba5c-4584-b02b-b84c5da54cfc.jpg)
![Screenshot_20220821-182610_PPSSPP](https://user-images.githubusercontent.com/78854859/185804890-8441d7a2-2dbc-443c-b328-2ba42d940d51.jpg)

**Comment by unknownbrackets** [comment]
Very possible that the recent depal refactorings have improved this.  Is anyone still seeing this on Adreno?

-[Unknown]

**Comment by IrfanH495** [comment]
> Samsung m20 Exynos 7904 Mali-G71 Opengl Disable Slower Effects OFF ![Screenshot_20220821-182558_PPSSPP](https://user-images.githubusercontent.com/78854859/185804820-7b0568ed-ba5c-4584-b02b-b84c5da54cfc.jpg) ![Screenshot_20220821-182610_PPSSPP](https://user-images.githubusercontent.com/78854859/185804890-8441d7a2-2dbc-443c-b328-2ba42d940d51.jpg)

i will try it on adreno later

**Comment by IrfanH495** [comment]
Sharp sh04H adreno 530
I think it's fixed
Disable Slower Effects OFF
![IMG-20220822-WA0000](https://user-images.githubusercontent.com/78854859/185810172-23581af3-2335-4397-aa7f-1fd0b887f79c.jpg)
![20220822_034132](https://user-images.githubusercontent.com/78854859/185810205-5634ac7c-3071-4807-b228-b8c09927a1aa.jpg)
thanks it's fixed now

**Comment by unknownbrackets** [comment]
Great, thanks for confirming.

-[Unknown]
