### ISSUE TITLE
Subtitle speed problem + sound cut and speed up of intro and some videos in Silent Hill Origins

### ISSUE THREAD

**Issue by Mart1997** [hrydgard/ppsspp#15786]
### Game or games this happens in

6F0A8145 - Silent Hill Origins

### What area of the game / PPSSPP

This version of the game in Spanish, takes time in which the subtitles of the game videos are usually advanced, although it is solved by increasing the brightness in the game options before starting the game, although the brightness bar does not represent operation but when performing This procedure lowers the brightness of the game, but corrects the problem with the speed of the subtitles.
The problem that arose in this version is that in the intro it reaches a certain point and the sound is cut off and it starts to fast forward without any explanation and it has been happening to me in several titles since version 1.13.1 came out in PlayStore, it would be great if you can fix this problem.

Video link (playing the subtitle speed bug + the new bug mentioned): https://youtu.be/7J9B_FdVxCw

### What should happen

For this type of situation, the intro or videos of the game should play without having to speed up and not lose the sound.

### Platform

Android

### Mobile phone model or graphics card

Moto One Fusion 

### PPSSPP version affected

v1.13.1

### Last working version

v1.12.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Would you be able to test some builds in between 1.12 and 1.13, to try to narrow down a possible range of commits that could have broken it?

You can get APKs here: https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by Mart1997** [comment]
@hrydgard Hello, I have tested several versions, including the oldest, unfortunately the video of the game at a certain moment begins to advance quickly and without sound and from what I realized, it may be due to the Android version (at the moment in my device has android version 12), since before it had version 1.12.3 and this behavior did not happen, it turns out that I tried the same version and now the video of the game is without sound and fast.
I tried the available compilation v1.13.2-1304-g16f93a268 and the same result, the good thing is that the game graphic problem was solved, including an increase in performance in the parts affected by the graphic error :D.
-Device used for testing: Nokia 6.1 (2018) with official LineageOS 19.1 (Android 12).
best regards

**Comment by hrydgard** [comment]
Hm, that's quite interesting, might have something to do with the recent ffmpeg problem and workaround somehow. Thanks for reporting, will have to investigate.

**Comment by Mart1997** [comment]
@hrydgard Thank you very much for responding, for what I have realized that at the moment the video of the game is played, it has the respective acceleration of the subtitles, but the normal video and audio speed until reaching the part of the dialog where the trucker approaches silent hill and in part where the signal interference is generated and is also represented in the video, right there a micro lag occurs, which causes a mini image crash and later the visual content is advanced x2 without sound, and it is very likely that the new version of android is generating this problem, before in android version 10 (emulator version 1.12.3) the same crash occurred but the video and audio were still normal (it could be that the video it is partitioned into two parts, and just at that moment it goes to the second file, this error is generated, which is very likely to be caused by the current android version mentioned)
- and the curious thing is that the same problem happens to other games, but there are few affected games, I don't remember the other game that I have run in the emulator that also has a behavior similar to this game (in video advance x2 without audio) .
I hope this information will be of help to you, Kind regards

**Comment by DarkLinkRT** [comment]
it happens in Windows 11 too :(

**Comment by LucioMJ99** [comment]
Hi, this problem still persist in the Spanish version of the iso

**Comment by ddtankbr23** [comment]
The problem continues on my Tecno spark 10c android 12

**Comment by Ottocon91** [comment]
I have the same issue with the german version of the game. But if i change the language to english, the intro works fine.

**Comment by lambdakilo** [comment]
Same problem here on en-us Windows 11 and English ppsspp 1.19.3
