### ISSUE TITLE
Spider-man 3 crashing

### ISSUE THREAD

**Issue by telanus** [hrydgard/ppsspp#15825]
### Game or games this happens in

ULUS-10317 Spider-man 3

### What area of the game / PPSSPP

When you beat u enemies in crime spree, ppsspp will crash with the following screen:

![Screenshot_20220810_105626](https://user-images.githubusercontent.com/19357986/183864439-ec89c590-7c01-49f3-a735-d82c54ed45a6.png)

### What should happen

It shouldn't crash

### Logs

50:42:531 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2672 sceKernelWaitThreadEnd - bad thread 363
50:42:563 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2672 sceKernelWaitThreadEnd - bad thread 360
50:43:515 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2672 sceKernelWaitThreadEnd - bad thread 373
50:43:531 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2672 sceKernelWaitThreadEnd - bad thread 370
50:45:036 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2672 sceKernelWaitThreadEnd - bad thread 383
50:45:050 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2672 sceKernelWaitThreadEnd - bad thread 380
56:15:250 user_main    E[MEMMAP]: Core/MemFault.cpp:184 Bad execution access detected, halting: 00000000 (last known pc 00000000, host: 0x7f0c00000000)
Segmentation fault (core dumped)

### Platform

Linux / BSD

### Mobile phone model or graphics card

Geforce GT630

### PPSSPP version affected

V1.13.1-247-g3edaeae81

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
It's possible this is related to #10196, although I think that was arm32 only or something.

It's likely that there's a problem with your disc.  Please rip a clean one and double check the CRC.  Looking at reports for this game, there are several different CRCs which is usually a sign that there are people using bad or hacked copies of the disc, which may not run properly.

https://report.ppsspp.org/game/ULUS10317_1.02

-[Unknown]

**Comment by telanus** [comment]
I doubt it's something to do with the dump, as it's listed on the report as working by some (798e7d3f)

But build this and it does not crash: https://github.com/hrydgard/ppsspp/commit/dab36b4e91e8bc8697affb30a9ffaa8077e5cf8c . will try later to see where it starts o break (If my weekend ends up the way I plan it.

**Comment by telanus** [comment]
@unknownbrackets I tested a bit more. Seems between commits 6fb5d82fe (no crash) and 1f71a69be (crashes) the problem starts to manifest.

**Comment by telanus** [comment]
tested this with v1.14-2-g23ca9f629, andthis still happen with the USA disc. And yes the Disc is the same this one: http://redump.org/disc/30102/ so shouldn't be a problem 

![Screenshot_20221215_221638](https://user-images.githubusercontent.com/19357986/207959757-54f37f8d-601f-421e-845c-b2eba8c0d570.png)

**Comment by telanus** [comment]
OK tested the Euro release and it also crashes as soon as spidey's hit.

This happens to be left on the terminal:

```
28:48:574 user_main    E[MEMMAP]: Core/MemFault.cpp:219 Bad memory access detected! 00000000 (0x7fda00000000) Stopping emulation. Info:
088129bc_z_un_08812968
movss xmm7, dword [rbx+rax]

double free or corruption (out)
Aborted (core dumped)
```

**Comment by telanus** [comment]
@unknownbrackets 

I tested it with Retroarch and the same thing happens there:

```
[libretro ERROR] [MEMMAP] Bad memory access detected! 00000020 (0x7ff200000020) Stopping emulation. Info:
0881e650_z_un_0881e4a0
movss [rbx+r10+0x20], xmm14
```
if I use a locally build core. While using one that comes from Retroarch gives:

`[libretro ERROR] [MEMMAP] Bad execution access detected, halting: 0000000a (last known pc 0000000a, host: 0x7f8f0000000a)`

**Comment by unknownbrackets** [comment]
Sorry I think I didn't see the previous note.

It sounds like if c3ecd41e2cf3c510e4ddc7a62a2c02ea2fe9e2a5 worked fine, this would be caused by #15372.  Does the previous commit work fine for both US and EU, or are they separate issues?

In PPSSPP proper, if you go to Settings -> Tools -> Developer tools -> JIT debug tools, and check the "ALU" box, does the problem go away?  This will make emulation a bit slower but may help narrow it down.

If not, does changing Settings -> Tools -> Developer tools -> CPU core to "IR interpreter" instead of "Dynarec (JIT)" prevent the crash?  This will be even slower, but again would help confirm.

Especially if disabling ALU helps, what specific CPU do you have?  The output of `cat /proc/cpuinfo` would be most helpful.

That change just makes it use BMI2 in some cases, but maybe we're somehow misdetecting your CPU's support for BMI2 and emitting bad instructions for it.

-[Unknown]

**Comment by Gamemulatorer** [comment]
This still crashing on armv7 phone.

***Interpreter***
![Screenshot_2023-03-14-00-09-58](https://user-images.githubusercontent.com/37603562/224762231-0a016baf-435f-4e15-b9cf-ed77fa6328cf.png)

***Dynarec JIT***
![Screenshot_2023-03-14-00-04-42](https://user-images.githubusercontent.com/37603562/224762316-a82110b8-ee91-4ae7-8330-a9e4bcfce7af.png)

IR Interpreter crashing me out the emulator with bluescreen.

**Comment by telanus** [comment]
Looks lie it was resolved recently, We build https://github.com/hrydgard/ppsspp/commit/b4c61acbf39e09779179e3a264f354712e82e54f and we didn't experience any crashes in the 20 minutes we played

**Comment by hrydgard** [comment]
Hm, I've though this one was resolved before, so I'll await more reports :)

**Comment by hrydgard** [comment]
Haven't gotten new reports of this recently, so I suppose the reports of it being fixed somehow may be accurate. Closing.

**Comment by amadib** [comment]
![alt|500](https://github.com/user-attachments/assets/027844e7-091b-4cfd-a0e3-29dc801fc4da)

![alt|500](https://github.com/user-attachments/assets/9c4ca85d-df95-4352-945b-295d71898928)


![alt|500](https://github.com/user-attachments/assets/f663f4b0-d8b7-4653-9636-a322c186a868)

I'm seeing the same issue running metal gear solid peace walker in chapter 2 on the boss fight each time I try to fire a FIM-43. It happens regardless of the backend selected. I tried the steps above including disabling cheats.

**Comment by hrydgard** [comment]
Hm, Metal Gear would be a separate issue. Please create a new issue report or find one that already mentions it and comment there.

**Comment by ozkantuzemen** [comment]
Using Odin Portal snd Odin 2 Pro, just tested with the latest build. Issue persists. As soon as Spiderman hits the enemies from the door game crashes. That doesn't happen on Windows version with the same game file.

**Comment by mohamedomarrenna** [comment]
i opend it and it be black secren and the game off please help

**Comment by mdkifayat304825** [comment]
Hi. I'm also facing the same problem.
