### ISSUE TITLE
Ridge Racer: Headlight and sun glares not rendering, lighting issues

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16083]
EDIT: Glares solved now, just the dark car lightning left to fix
EDIT2: Vertical lens flare line solved as well.

There are reports that it does work on some old versions on AMD only, which is very strange.

[Ridge Racer lens flare UCES00002_0002.zip](https://github.com/hrydgard/ppsspp/files/9628909/Ridge.Racer.lens.flare.UCES00002_0002.zip)

It does work in the software renderer, although for whatever reason it's kinda glitching a bit from frame to frame (something is not deterministic, or we get some accidental feedback effect?)

https://user-images.githubusercontent.com/130929/191835425-f284d189-2966-4c2a-ba43-8929614bf575.mp4

In the hardware renderer, no flares:

![image](https://user-images.githubusercontent.com/130929/191835593-962787a4-ddee-4723-a620-dd60a50f10ee.png)

It seems to be doing some actually not that complicated trickery. There's a strange draw that gathers a whole bunch of pixels (768 vertices making up 128 little rectangles) into a 1x1 render target at 0x041fff00 and adds them up using stencil (step 1301):

![image](https://user-images.githubusercontent.com/130929/191835931-5e56f995-ffa4-477e-8075-397eb31f7d63.png)

Stencil does end up as 255 but alpha stays at 0, so something is not going quite right there with our stencil operation substitution.

![image](https://user-images.githubusercontent.com/130929/191837413-06665903-2ee0-4c99-87c7-db476f3d2da2.png)

We're using dualsrc blend and writing alpha into Src1:
```
    fragColor0 = vec4(v.xyz, 0.0039220000617206096649169921875);
    fragColor1 = vec4(0.0, 0.0, 0.0, v.w);
```
~~But the alpha part of the blend equation doesn't read from it, only the color? That seems wrong.~~

Wait, no, it's the 0.00392 we want (increment by 1/255, if the pixel is not discarded, alpha test is happening). ~~But it's ONE instead of SRC_ALPHA in Alpha Src in the equation, that does seem wrong.~~ Wait I'm confusing myself, we do want ONE * 0.00392.. Hm. No it does actually seem to accumulate OK?? Hm.

Then it textures from the 1x1, rendering the highlight as a simple mesh, step 1302 (and oh, it seems it goes wrong here - the framebuffer/texture matching misses it, and creates an empty 1x1 texture instead):

![image](https://user-images.githubusercontent.com/130929/191837251-8a38883c-a053-4bae-a6f4-e6bb7d2b114e.png)

It does do CLUT-from-framebuffer later in the frame but that's just for the speedometer, the lights are simpler.

**Comment by hrydgard** [comment]
Ok, that wasn't so hard, fix coming up.

https://user-images.githubusercontent.com/130929/191841577-da751dd1-6c69-4b8b-9028-77337b3e20a6.mp4

**Comment by unknownbrackets** [comment]
Some interesting things about this frame dump:

The correct rendering on the PSP has better shading:
![#16083_UCES00002_ridge_racer_lens_flare](https://user-images.githubusercontent.com/191233/191880912-7fffe98f-496f-496a-9ed4-e54237212767.png)

Compared to the current rendering in Vulkan (I'm not sure about the top left, it's only happening in headless):
![#16083_UCES00002_ridge_racer_lens_flare_vulkan](https://user-images.githubusercontent.com/191233/191881297-3d052f79-4241-4ca0-b6e7-987fc1e38536.png)

Also as you can see from the PSP frame dump, somehow the CLUT was not captured.  It knows it's a target, but somehow it's not getting rendered properly (even on a PSP), probably some issue with the dump machinery... well, forcing it to use the CLUT from the framedump gives this:
![#16083_UCES00002_ridge_racer_lens_flare](https://user-images.githubusercontent.com/191233/191881656-48f049a8-4f0f-46a3-894f-41bf79665814.png)

Software also gets the lighting wrong, outside the weird flickering:
![#16083_UCES00002_ridge_racer_lens_flare_softgpu](https://user-images.githubusercontent.com/191233/191881852-4ad0ceb1-5bb1-4ed7-aa09-57fe49bf7df3.png)

The texture filtering looks more accurate, which is nice, but the lighting is just as wrong (some in the background as well.)  Of course, there's also the weird flickering... gotta see what's going on there.

-[Unknown]

**Comment by unknownbrackets** [comment]
Filtering prims to 1-1345 is fine, but 1-1346 reproduces it so it must be caused somehow by that draw.

The draw in question is a bloom, simple 58x32 draw from 8888 to the screen, using dither, alpha blend, and color test.  Color test is simply != zero, and blend is fixed one + one (so the color test is pointless, maybe I should optimize it out...)  Dither seems inoffensive as well.

The bloom temporary is created at 1334/1438, so my guess is that's where things are going wrong.  It copies in strips 128 wide from 5551 481x272 -> 8888 241x137.  It then self-renders that down from 241x136 -> 121x68, also it rectangle strips.  And then further from 120x68 -> 60x34, again self-render.  From here, it does a no-texture reverse subtract blend, to get the bright parts.  The another self-render, this time blending at offsets with a fixed + fixed blend of about 51% + 51%, to blur it.

If I flush each of those using the GE debugger, there's no weird flickering, so it's definitely some hazard/threading issue... forcing 1339 and 1342 to use 1 thread makes the issue go away.  What's weird is, both ought to have naturally decided on 1 thread since they're clearly render-to-self.

Aha, it's because it just flushed in this scenario, due to the pending overlap.

-[Unknown]

**Comment by combo-pizza** [comment]
The headlights flicker on a real psp, at least i recall seeing it at the beginning of another track

**Comment by combo-pizza** [comment]
I mixed up the headlight flickering with something else in the game. But the headlights do come on when you're in tunnels too, on some car models the speedometer changes color to indicated your headlights are on which is a nice touch.

![image](https://user-images.githubusercontent.com/95991264/192063292-3295ecc5-a2c6-4ca6-bc81-711e884e5270.png)

**Comment by Back2Life888** [comment]
Speaking of headlight glares, in one of the Android builds, the headlight glare only renders on one headlight as if the other one is broken and smashed. I dunno how to explain it and I got no screenshots of it.

**Comment by hrydgard** [comment]
That's weird, huh. Will try.

Regarding the dark car lighting issue, it's using specular lighting, but not seeing much of it. Might simply be something wrong with our lighting equations, although they have been through quite a lot of testing... It does apply an environment map right afterwards, but it's quite dark and does not seem to be enough to explain the lighting difference, even if blended wrongly somehow.

**Comment by Back2Life888** [comment]
![broken ligt](https://user-images.githubusercontent.com/76780043/192101628-b38e6494-7525-461b-b953-3e9cbf061a20.png)
Managed to dig up an old screenshot of the singular headlight bug. It occurred on Android. I didn't experience this on other platforms.

**Comment by hrydgard** [comment]
That's quite curious, does it happen with any car and track (at night), or some specific combination?

**Comment by Back2Life888** [comment]
> That's quite curious, does it happen with any car and track (at night), or some specific combination?

It doesn't need a specific combination. It just has to be either night or in a tunnel where the headlight is enabled.

**Comment by unknownbrackets** [comment]
Just a note: filtering the framedump to 1 - 1000 on a PSP produces this:
![#16083_UCES00002_ridge_racer_lens_flare-1000](https://user-images.githubusercontent.com/191233/192130216-38239678-d4f9-47f7-8a66-5700f620fc60.png)

Compare to:
![Partially rendered scene with darker car](https://user-images.githubusercontent.com/191233/192130257-54319060-b661-462d-9652-1222a9650c2d.png)

The important thing here is that the lighting is already correct for the parts drawn so far, which does indicate that it's not the tex matrix later at 1080/1438.

Also, if I force the specular coefficient (rewriting any 0x5B418000 command to 0x5B42C600) higher to 99 on the PSP, it is indeed darker:
![#16083_UCES00002_ridge_racer_lens_flare-speccoef99](https://user-images.githubusercontent.com/191233/192130542-83a42f7c-03dc-42b8-8e88-cc9f3e412a94.png)

Interestingly, there's still some specular, even at such a high power, but it's much darker.  Conversely, if I force PPSSPP's specular down to 0.3f, I get this (not sure what's wrong with the normalized value, it seems to work for me...):
![Mostly bright looking car](https://user-images.githubusercontent.com/191233/192130658-e0ec0189-cdb3-4b62-b9f1-65dbd717d7a0.png)

Even this is wrong, I wonder if it could somehow be that the "toViewer" value is actually wrong?  The PSP lighting looks better than this (or than your screenshot), at least as far as how it's shaded compared to the headlights.

If I set the coefficient that low on the PSP, it's a ton brighter:
![#16083_UCES00002_ridge_racer_lens_flare-speccoef0.3](https://user-images.githubusercontent.com/191233/192130721-29ed4caa-4608-4c20-bb9a-e48797a963dc.png)

-[Unknown]

**Comment by hrydgard** [comment]
Oh, interesting. But if you look at the little air intakes or whatever, looks like the correct light is coming from a different direction? There's a shine to it that's just not there with hacked specular:

![image](https://user-images.githubusercontent.com/130929/192131240-dd01a90e-b2ee-4637-80ff-335affe53ee9.png)

So maybe it's more than just the coef that's off.

As for the toViewer thing, I figured that one out back in the day using the light demo from the PSPSDK, IIRC, it makes it match.

**Comment by hrydgard** [comment]
I've managed to get a reliable repro, of the glitched sun sprite problem. I can only get it to happen on Android so far. Bayonet car (3rd, class 1) on Sunset Drive, on Pocophone F1, Ridge Racer 1 EUR.

Unfortunately, can't replicate it on PC, strangely enough... I can see an additional texture being invalidated and decoded every frame when looking at the sun though.

**Comment by hrydgard** [comment]
There is a second CLUT effect going on with the sun, similar to the highlights. I've caught it in a capture now.

It again textures from the framebuffer and accumulates the results into a single pixel at 041fc000. Then it textures from 041fc000, drawing to the first 256 pixels of the top line of an 8888 render target at 0418c650, creating an alpha gradient from 0-255, which is presumably intended for use as a CLUT next. RGB are black or nearly so across the whole gradient.

This is then loaded as a dynamic CLUT, and used with this strangely tall source texture, which contains a quarter of some flare shape at the bottom right:

![image](https://user-images.githubusercontent.com/130929/194605512-2ad74acb-e099-4387-b7c1-49b0d3941375.png)

Weirdly, the output of that depal operation is 100% black though. Not sure what's going wrong...

It seems to fail differently on PC and Android...

**Comment by hrydgard** [comment]
Hm, I discovered that the lens flare actually works occasionally on Sunset Drive, and the depal seems to miss a pixel of the texture.

I think I'm gonna make it so that if the detected depal bounds are very close to covering the whole texture, then just cover it all. Likely no savings anyway from a smaller rect in that case.

**Comment by hrydgard** [comment]
I'm gonna call this case closed for now, I think.

**Comment by unknownbrackets** [comment]
I think we can keep it closed, but the lighting issue on the vehicle itself is still not resolved, right?

-[Unknown]

**Comment by hrydgard** [comment]
Oh, true. I'm gonna make a new issue for that one, not tagged with 1.14.

**Comment by Back2Life888** [comment]
The corrupted sun glare is still not fixed but somehow, its now more subtle than usual. Its now a very translucent vertical bar which you could see better if you switch to the back camera. Its a tad bit more subtle in the bumper camera, almost undetectable.

**Comment by hrydgard** [comment]
Well at least it's better, but sure, wanna fix it all. Got a screenshot of what you're seeing?

**Comment by Back2Life888** [comment]
![glare](https://user-images.githubusercontent.com/76780043/195982049-cc7b311f-88bb-498b-a413-9026da09523f.png)
The glare is now a vertical bar as I said. But at least it doesn't obstruct your view anymore.

**Comment by hrydgard** [comment]
OK. I think we're just still a pixel off or so on the detected render area, which we use to limit the area we do "depal" (lookup in palette texture). I'll try to fix it up tomorrow.

**Comment by Back2Life888** [comment]
Sun glare vertical bar is still there btw. Headlight glare also still doesn't properly render on Android. HOWEVER, the Angelus from RR1 has it's lights render fine. Probably cause it only has 1 headlight so only one glare gets rendered for it. As for the other cars, they still have fucked up headlight rendering.

**Comment by antoniodesousa** [comment]
I have the same issue when using the Vulkan backend.

![PPSSPP Gold v1 15 14_05_2023 14_06_30](https://github.com/hrydgard/ppsspp/assets/10920974/39a6ea09-904d-4f62-9a46-8b5842df9959)
![PPSSPP Gold v1 15 14_05_2023 14_17_48](https://github.com/hrydgard/ppsspp/assets/10920974/bd74ffb8-bb6b-4fde-a618-37f4e92da479)

I tried v1.15.3, v1.14.4 and the latest dev build [v1.15.3-26-g55c1c48d6](https://github.com/hrydgard/ppsspp/commit/55c1c48d605d2b27a92002b16657860e319d35ff)
All have the same problem.

CPU: Ryzen 6900hx
GPU: Radeon 680m
OS: Windows 11
Graphics driver: Adrenalin 23.4.3

**Comment by Back2Life888** [comment]
![ULUS10001_1 00_0](https://github.com/hrydgard/ppsspp/assets/76780043/d7f46764-417f-4d6b-8a11-728489426c31)

On Android hardware on a build from yesterday. Just leaving this screenshot with the screwed up headlight glare in here

**Comment by Back2Life888** [comment]
Unrelated but after updating my PPSSPP client, the audio is high pitched now. Weird.

**Comment by hrydgard** [comment]
I can't reproduce the vertical bar in sun glares.

The missing second headlight does reproduce on devices without support for dual source blending. Very unclear how that affects things, but I can get it to repro even on PC if I forcibly disable the feature!

Anyway, I'm leaving fixing the second headlight to the next version, now that I've figured out the reason why compatibility differs.

**Comment by antoniodesousa** [comment]
I can still reproduce the vertical line in sun glares using the latest version 1.16.6. Even though I have a different GPU.

![001](https://github.com/hrydgard/ppsspp/assets/10920974/640e4bca-6ddb-41d3-bc93-01709abe26ea)
![002](https://github.com/hrydgard/ppsspp/assets/10920974/7e8f9569-83ae-4c28-9b69-8661c5c5eed0)

Here's my settings file:
[ppsspp.zip](https://github.com/hrydgard/ppsspp/files/13789355/ppsspp.zip)

CPU: Ryzen 6900HX
GPU: Radeon RX 6600M
OS: Windows 11 23H2
Graphics driver: Adrenalin 23.12.1

**Comment by hrydgard** [comment]
ok, then we still need to look at that one too.. I do have a radeon now so once I get around to it, will test on that.

**Comment by hrydgard** [comment]
@antoniodesousa  I seem to visually detect the use of texture upscaling in your screenshot - do you get the line if you disable it?

**Comment by antoniodesousa** [comment]
Hi @hrydgard , I just tested it without the texture upscaling but it made no difference. The issue only happens with the Vulkan backend. And most likely only to AMD GPUs. I use the Vulkan backend because:

- It has by far the best performance compared to the other backends
- It supports MSAA antialiasing, which greatly improves the overall picture quality
- It supports TextMMPX, which greatly reduces the black lines between the tiles when upscaling the native resolution (most notably Ridge Racer and Outrun 2006) while maintaining the overall picture quality. To me, it actually looks even better than the original

**Comment by hrydgard** [comment]
ok, thanks for your input! I'll investigate more in the near future.

**Comment by Back2Life888** [comment]
![Capture](https://github.com/hrydgard/ppsspp/assets/76780043/e7370df1-b65f-439b-b801-a842cc412025)

Sun glares are still broken. Also, you can see the bug better on Ocean Bay Forward (the track in this img)

**Comment by hrydgard** [comment]
@Back2Life888 just to clarify, in your screenshot, the broken part is the weird vertical line in the right half of the image, right, nothing else in addition to that?

will investigate soon-ish. And thanks for the tip about which track to try.

**Comment by Back2Life888** [comment]
![IMG_20240104_012343](https://github.com/hrydgard/ppsspp/assets/76780043/d4c96d6f-152d-4a31-a2ff-a83945a5551c)

Here. I encircled it to make things a bit easier.

**Comment by hrydgard** [comment]
Yup, got it.

**Comment by Back2Life888** [comment]
> OK. I think we're just still a pixel off or so on the detected render area, which we use to limit the area we do "depal" (lookup in palette texture). I'll try to fix it up tomorrow.

Also, you said this about the sun glare being a pixel off and you fixing it tomorrow only for nothing to happen for almost half a month after you sent this message. Did anything happen with this or this pixel being off isn't the reason for the bug?

**Comment by Back2Life888** [comment]
Updated to 1.17 and the sun glare is fixed for me
Not sure whether it still ocurrs to others

**Comment by hrydgard** [comment]
Ah good, thanks for reporting!

**Comment by Back2Life888** [comment]
Also regarding the lighting with the original PSP Hardware, I looked at some footage of the game running in the original PSP hardware and it looks like the headlight glares are actually rendering shaders on the body of the car. Maybe the headlight glare doesn't render that shader in PPSSPP which is why the cars are darker in the PPSSPP hardware. That's just my guess though.

**Comment by hrydgard** [comment]
I was gonna say that we have a different issue about those lighting problems, but no, it's in this one:

https://github.com/hrydgard/ppsspp/issues/16083#issuecomment-1255739342

So I was wrong to close this, I thought this was mainly about the flares, which are solved (although require the "dual src blending" feature to function correctly).

Reopening for that lighting problem.

**Comment by antoniodesousa** [comment]
Updated to 1.17.1 and the sun glare is not fixed for me... at least no completely.

This release improve it a lot but not completely fixed it. Now I get the vertical line randomly. Sometimes appears, other times there's no line at all during the whole race. Other times the vertical line appears segmented or just part of it shows up on the screen. Best track to test this is BASIC 01 -> Crimsonrock Pass.

Anyways, much better now for sure.

![PPSSPP Gold v1 17 1 - ULUS10001 _ RIDGE RACER 03_04_2024 15_32_14](https://github.com/hrydgard/ppsspp/assets/10920974/e1251684-9340-4025-ab22-dd44898e8153)

**Comment by 71knight** [comment]
Yes and I would like to add that the sun glare vertical line still happens on opengl and vulcan on my 2020 Moto g power smartphone running Android 10.  I am using the most recent build of ppsspp.

**Comment by hrydgard** [comment]
Yeah, I know about the vertical line. I'll get around to looking into it one of these days, lots to do...

**Comment by IrnMonkey** [comment]
The issue with vertical line still present in v.1.19.1. It something do with texture filtering - when it set to "nearest", line is gone.

**Comment by hrydgard** [comment]
Nice find, that might help fixing it. Though if it's a resolution dependent thing (does it happen at 1x?), the solution might be more of a hack than a fix.

**Comment by IrnMonkey** [comment]
Still present at 1x resolution (tested on Windows and Linux (Steam Deck) with Vulkan renderer). I may also add that the vertical line appears when there is a sun flare on a stage, may be it somehow related. And, if I may, one more thing about RR2 issues (just love that game so much) - with reverberation on (audio backend is set to "auto") the sound becomes scratchy (you may hear it when driving thru tunnels).

**Comment by hrydgard** [comment]
Yeah, the vertical line is an artifact on the edge of the big lens flare sprite itself, unclear why though.

**Comment by antoniodesousa** [comment]
The line is still present on my end as well. Although, it doesn't always appears or it only shows partially. Very weird. 1x upscale doesn't fix the line. Only changing the filtering to `Nearest` doesn't show the line. But then all the graphics show very pixelated.

![Image](https://github.com/user-attachments/assets/84bb3fac-d686-4f87-97b1-1d34b847f5d2)

![Image](https://github.com/user-attachments/assets/ab5a6a94-1cf1-4983-b91b-16859a86901a)

![Image](https://github.com/user-attachments/assets/ee49a3a8-0b6f-44c5-bbd4-53a031d3dda5)

**Comment by SecularSteve** [comment]
> The line is still present on my end as well. Although, it doesn't always appears or it only shows partially. Very weird. 1x upscale doesn't fix the line. Only changing the filtering to `Nearest` doesn't show the line. But then all the graphics show very pixelated.
> 
> ![Image](https://github.com/user-attachments/assets/84bb3fac-d686-4f87-97b1-1d34b847f5d2)
> 
> ![Image](https://github.com/user-attachments/assets/ab5a6a94-1cf1-4983-b91b-16859a86901a)
> 
> ![Image](https://github.com/user-attachments/assets/ee49a3a8-0b6f-44c5-bbd4-53a031d3dda5)

Ditto here.

Testing it on the Steam Deck OLED
Version 1.20.3

Along with a few texture misalignments, including tiny white lines beneath the text/fonts, and a black line on the title screen.

**Comment by hrydgard** [comment]
#21825 fixes the vertical line.

**Comment by hrydgard** [comment]
The only thing left is issues that can only be fixed by full emulation of dual source blending. That itself is really a separate problem, so I'm closing this now.
