### ISSUE TITLE
Chicken flickering / teleporting around

### ISSUE THREAD

**Issue by justafella** [hrydgard/ppsspp#18203]
### Game or games this happens in

ULUS-10458 - Harvest Moon: Hero of Leaf Valley

### What area of the game / PPSSPP

Inside the chicken coop, whenever chicks or chickens move.

### What should happen

No flicker in movement. It's been a long time since I last used PPSSPP, but this is definitely a bug. It never happenend at least until version 1.13. I'll try to pin down the last working version later on my pc. I made a sreenrecord of the issue. 
https://drive.google.com/file/d/12XSn86QQJJdnJk4oNjCat1oqwY8X_NiH/view?usp=drivesdk

### Platform

Android

### Mobile phone model or graphics card

Xiaomi Redmi 9 (M2004J19C)

### PPSSPP version affected

1.16.3

### Last working version

1.13

### Graphics backend (3D API)

Vulkan

### Checklist

- [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [x] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
This looks like a CPU emulation bug.

Does it make a difference if you, as CPU Core in Settings/Tools/Developer Settings, pick the Interpreter or IR Interpreter, or even IR JIt options?

**Comment by justafella** [comment]
It did. Both Interpreter options fixed de issue (with no slowdowns, if it
matters)

Em sáb., 23 de set. de 2023 14:16, Henrik Rydgård ***@***.***>
escreveu:

**Comment by hrydgard** [comment]
Okay, that is very interesting then!

One more thing you can play with - in Developer Tools, we also have "Jit Debug tools", where you can turn off parts of the JIT by checking boxes. So, switch back to JIT, and then see if any particular box there fixes it when it alone is checked.  Likely an FPU or VFPU one...

**Comment by justafella** [comment]
Tried all of them, one by one: no fix
All of them, at the same time: no fix
All of FPU only: no fix
All of VFPU only: no fix
Tried some other stuff at developer options, but nothing besides using
Interpreter fixes anything so Far
I still intend to verify if Windows version has the same issue and narrow
down what was the last working version, If it helps

Em sáb., 23 de set. de 2023 14:46, Henrik Rydgård ***@***.***>
escreveu:

**Comment by hrydgard** [comment]
Huh, that is .. even more surprising! Something really odd going on here.. Thank you for testing.

**Comment by unknownbrackets** [comment]
It would be interesting if this wasn't a problem in the IR-based jits.

-[Unknown]

**Comment by justafella** [comment]
Took some time to test versions, but way down to version v1.14.4-331 the
error exists. This version is the very bottom entry in the build list.

Em dom., 24 de set. de 2023 01:14, Unknown W. Brackets <
***@***.***> escreveu:

**Comment by hrydgard** [comment]
That's good to confirm it's not something recent. Thanks for testing!

**Comment by justafella** [comment]
Just now I realized you asked for a save state. I did one. There are 2 chickens outside with normal behavior, and 1 inside the chicken coop, where it bugs. I haven't tried to bring one of them inside other places, but I remember, while taking part-time job for Ronald, that his chickens bug inside his coop too.
[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/12709173/PPSSPP_STATE.zip)

**Comment by justafella** [comment]
Forgot to mention that Windows versions have no issues

**Comment by justafella** [comment]
I have another report. This time I will not open a new topic because I think It is the same problem. This time, at Horse Races, horses teleport over the fence, out of the track and get stuck there. Changing CPU Core to any Interpreter fixes it at cost of FPS. I have a screenrecord and a save state at the event. I am currently at Summer's Horse Races, but it happened at Spring's too. The game runs at 15 FPS on races, but I think it is by design since it has a timer that counts seconds normally.

**Comment by unknownbrackets** [comment]
The chicken thing does not seem to occur with the new IR based jit (#18229), the chicken seemed to move naturally.  Performance was about the same as jit on my device.

-[Unknown]

**Comment by justafella** [comment]
I played with 1.16.4 recently. Really looks like chicken bug is gone, at
least most of the time. I'll pay more attention next time. I remember still
seeing some flicker, but so slightly it looks normal like when I used to
play on 1.13 back then. I thought the horse is suffering the same bug
because it looks like the same behavior (teleport/flicker) is getting it
beyond the fence, and it is fixed the same way (changing CPU Core)

Em ter., 26 de set. de 2023 21:56, Unknown W. Brackets <
***@***.***> escreveu:

**Comment by unknownbrackets** [comment]
Sorry for saying it in a confusing way.  There's a new experimental jit that you can't use yet in any stable version.  It doesn't have this bug.  I still see the bug in the latest stable versions with the "old" (current) jit.  #18249 should fix that.

I didn't check the horse but it's probably the same issue.

-[Unknown]

**Comment by justafella** [comment]
Oh I get it now. I'll get the latest Android release on buildbot and see
what happens.

Em ter., 26 de set. de 2023 23:15, Unknown W. Brackets <
***@***.***> escreveu:

**Comment by justafella** [comment]
Everything worked perfectly fine on the latest build. I tested horse races multiple times and it runs just perfect. Chickens inside the coop are behaving perfectly normal too. Everything fixed! Thank you so much!

**Comment by hrydgard** [comment]
thanks for confirming!
