### ISSUE TITLE
Ys: The Oath in Felghana Crashes when Saving system data

### ISSUE THREAD

**Issue by KenFraserYT** [hrydgard/ppsspp#19315]
### Game or games this happens in

ULUS- 10558: Ys: The Oath in Felghana

### What area of the game / PPSSPP

When creating or updating save data through the in-game save point, the system will crash as the game saves the system data and the save file becomes corrupted.

### What should happen

The game should save and player should be able to resume play.

### Platform

Linux / BSD

### Mobile device model or graphics card (GPU)

NVIDIA RTX 3060 12GB

### PPSSPP version affected

v1.17.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by anr2me** [comment]
Does an old version of PPSSPP also crashed? or this crash only happened on newer version?

**Comment by anr2me** [comment]
Doesn't seems to happen on Windows using PPSSPP v1.17.1-823 using savedata from https://gamefaqs.gamespot.com/psp/980502-ys-the-oath-in-felghana/saves (the one said "no cheats used")
I can load and save without issue.

PS: i hate games where the story can't be skipped :( not designed for replayability in mind i guess

**Comment by KenFraserYT** [comment]
Attached the save file that gets generated before the program crashes. I'm using the Flatpak of PPSSPP on Linux Mint.
If I reopen the game I can load the save but any future save the program will still crash.
First occurred at the first available save point.

[Saves.zip](https://github.com/user-attachments/files/16119405/Saves.zip)

**Comment by anr2me** [comment]
> Attached the save file that gets generated before the program crashes. I'm using the Flatpak of PPSSPP on Linux Mint. If I reopen the game I can load the save but any future save the program will still crash. First occurred at the first available save point.
> 
> [Saves.zip](https://github.com/user-attachments/files/16119405/Saves.zip)

That savedata is already corrupted
![image](https://github.com/hrydgard/ppsspp/assets/7974720/f3c127ec-211e-4afb-ad09-81c234cd6259)

You should provide a savedata that can be loaded successfully so we can try saving it.

May be the flatpak version of PPSSPP is outdated, since there have been many crash fix since 1.17.1 release version.
You should try using the [latest linux artifact](https://github.com/hrydgard/ppsspp/actions/runs/9822339095/artifacts/1674857353) to see whther this issue have been fixed or not on dev build

**Comment by KenFraserYT** [comment]
As stated previous; and in the initial error report: This save file is what is generated at every save. It corrupts every single time as the program crashes so there is no way for me to create a savefile that isn't corrupted.
But as also stated above, it can be loaded, from the load option in the main menu, just the system data is corrupted. But the program will still crash again at the next save attempt.

Building the latest dev build does not solve the issue still being on the current Flatpak release, which is currently the latest release on all distros.

**Comment by anr2me** [comment]
I triedd using the "Load" option from Main menu
![image](https://github.com/hrydgard/ppsspp/assets/7974720/d6342ac4-a108-46a2-b53f-6d9d1601c62f)

but it can't be loaded
![image](https://github.com/hrydgard/ppsspp/assets/7974720/e5b490d7-31a6-4e53-bc2c-31533eaa3e81)


However, if i answered "Yes" here (when i tried to go back to main menu after failed to load)
![image](https://github.com/hrydgard/ppsspp/assets/7974720/c736661f-c808-4267-b75c-e2457bcbf99c)
It will get me to this location in game:
![image](https://github.com/hrydgard/ppsspp/assets/7974720/2dd0a6fe-4572-4db7-9da7-2d49db80944f)
And when i tried to Save it, it works fine, i can save it successfully
![image](https://github.com/hrydgard/ppsspp/assets/7974720/90b36f24-5fde-427f-b14a-6f178c38a2a7)
It can also be loaded successfully later.

**Comment by anr2me** [comment]
Btw, have you tried changing the "I/O timing method" to see whether it have any difference?

**Comment by hrydgard** [comment]
Hm, I'm wondering if this is related to:

- #13781 ..

**Comment by anr2me** [comment]
> Hm, I'm wondering if this is related to:
> 
>     * [Silent Hill - Shattered Memories - Memory Stick Not Inserted issue #13781](https://github.com/hrydgard/ppsspp/issues/13781) ..

It could be, since it only happened on non-Windows.
May be related to the mtime thing mentiond by unknownbrackets, i wondered whether your recent fix on the sceIoGetStat mtime fixes this or not.

**Comment by hrydgard** [comment]
It didn't fix silent hill, it'll only fix games that go inspect files using sceIoGetStat.

Still no clue what's wrong with Silent Hill ...

**Comment by hrydgard** [comment]
How is this in a fresh build, by the way, rather than 1.17.1?

There have been a few fixes since then which might have taken care of this.

"Building the latest dev build does not solve the issue still being on the current Flatpak release, which is currently the latest release on all distros."  << Well, if the latest dev build DOES work with it, then there's nothing to do here except wait for the new release, which will happen in September.

**Comment by sum2012** [comment]
This is first save point of ppsspp save status
[PPSSPP_STATE.zip](https://github.com/user-attachments/files/16362377/PPSSPP_STATE.zip)

**Comment by sum2012** [comment]
I test in android , v1.17-1-935-gc9b22df725 no problem in creating\update game save.
Can we close the issue ?

**Comment by hrydgard** [comment]
Yes, it does seem that it's fixed indeed.

So let's close it, of course do re-open if it appears again in a new release.
