### ISSUE TITLE
Dante's Inferno weird colors around the fire.

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6332]
![142](https://cloud.githubusercontent.com/assets/3481559/3281114/99e1bc44-f495-11e3-9869-aa0275536b2d.png)

psp
![201406150843_002](https://cloud.githubusercontent.com/assets/3481559/3281115/99e4f418-f495-11e3-885d-60f5a62f25a8.png)

Ge debugger
![01](https://cloud.githubusercontent.com/assets/3481559/3281124/b84ebd6c-f495-11e3-877f-fec91286cf6b.png)

**Comment by unknownbrackets** [comment]
I think this was a flat shading issue.  Is it solved now?

-[Unknown]

**Comment by daniel229** [comment]
No,it's still buggy.

**Comment by brujo5** [comment]
still slow as hell in my phone. For example god of war run much better than this.

**Comment by daniel229** [comment]
Still no change.
![01](https://cloud.githubusercontent.com/assets/3481559/6407017/7207aa64-be73-11e4-850e-72f337b710ef.png)

Update GE debugger.
![02](https://cloud.githubusercontent.com/assets/3481559/6407023/813cb8e4-be73-11e4-84b8-85ef7f3b4570.png)

more tabs
https://gist.github.com/daniel229/d6e4204599dff08cca59

**Comment by ppmeis** [comment]
Tested in latest build. Issue still present:
![image](https://cloud.githubusercontent.com/assets/4381277/8890107/bae07ab8-32f4-11e5-8e09-f772946cf958.png)

**Comment by ppmeis** [comment]
Tested with latest build. Same status.

**Comment by unknownbrackets** [comment]
Darn, I was hoping #8240 would've helped.  Does it use any CLUT address starting with 0x04... when drawing the fire?  It may draw the fire in several primitives.

-[Unknown]

**Comment by daniel229** [comment]
I don't see any CLUT address starting with 0x04 in texture tab.

Gedebugger from the new build.
![01](https://cloud.githubusercontent.com/assets/3481559/11947938/a380f7e2-a8a8-11e5-88d4-fbedc2cbfeba.png)
https://gist.github.com/daniel229/7f4ad0ba67eee0a68604

**Comment by unknownbrackets** [comment]
It's not using flat shading, pixel masking, or logic ops.  The blending mode is a very simple saturating add...

There are two texture levels, there.  Does "Level +" show a texture that looks different than a smaller version of the original texture?  It is using interesting mipmap data:

Tex level/bias	fc0002 (slope per JPCSP, bias=-0.25)
Tex lod slope	3d8917 (0.0669)

-[Unknown]

**Comment by daniel229** [comment]
Yeah,it has a smaller version.
![03](https://cloud.githubusercontent.com/assets/3481559/11949212/9e4d99d8-a8b7-11e5-90b9-bd71c71fb292.png)

**Comment by daniel229** [comment]
It seems just smaller
![01](https://cloud.githubusercontent.com/assets/3481559/11949283/63a7fa52-a8b8-11e5-9290-0d566a8c133d.png)
![02](https://cloud.githubusercontent.com/assets/3481559/11949284/63aa7174-a8b8-11e5-891f-7ec3fa71504f.png)

**Comment by daniel229** [comment]
Great,fixed in https://github.com/hrydgard/ppsspp/pull/8742
![01](https://cloud.githubusercontent.com/assets/3481559/15364630/bf863828-1d4f-11e6-8697-3baea5568995.png)

**Comment by unknownbrackets** [comment]
I guess it was using prefixes on the color conversion ops.  The IR work sure has been valuable at getting us to re-examine some CPU bugs.

-[Unknown]

**Comment by nfjorgebueno** [comment]
the same problems in the latest versions of ppsspp 1.2.2. I try everything

**Comment by unknownbrackets** [comment]
Once v1.2.2 is released, all its bugs will be its bugs.  We don't hack into people's computers and replace what v1.2.2 was.

This is fixed, but it'll be in v1.3.0 or whatever future release.

-[Unknown]

**Comment by nfjorgebueno** [comment]
he did not understand very well, all I can say is that I have the original Windows 10, 64 bit-and version of the emulator  is
ppsspp-v1.2.2-875-g028e98a
