### ISSUE TITLE
LEGO HARRY POTTER - YEARS 1-4 (ULES01351): Problems in the MAIN MENU to return from the credit in the game

### ISSUE THREAD

**Issue by kirous** [hrydgard/ppsspp#6702]
Here the main menu is displayed:

![01](https://cloud.githubusercontent.com/assets/5083411/3867945/016472b4-2018-11e4-80d2-bee3c6ad2056.jpg)

After entering credits and return it back to the main menu is displayed as follows, and you can not see the other options

![02](https://cloud.githubusercontent.com/assets/5083411/3867947/2ae540a0-2018-11e4-8534-0ce8d06f5a1f.png)

Is improved again when the game starts and again set out the main menu 

Nor is not improved MODE "READ TO MEMORY FRAMEBUFFER (CPU)" and "MEMORY TO READ FRAMEBUFFER (GPU)" 

Another is the dialog box that the characters speak, blink some time. But if the game is OK.

**Comment by daniel229** [comment]
Fixed in https://github.com/hrydgard/ppsspp/pull/7074 .

**Comment by unknownbrackets** [comment]
Blinking dialog may be vertex cache or etc.

If that pull fixed anything it probably means it's still broken in interp?

-[Unknown]

**Comment by daniel229** [comment]
Yes,still broken in interp

**Comment by daniel229** [comment]
The blinking dialog also is fixed.

**Comment by unknownbrackets** [comment]
Sounds like everything is fixed, except interp?  Or does interp now work?

-[Unknown]

**Comment by daniel229** [comment]
No,it doesn't.

**Comment by unknownbrackets** [comment]
Does this still happen?

If yes, there's now (in latest git) a way to turn on and off jit features.  It might help to toggle these and confirm which part causes jit to behave the same (wrong) as interpreter.

It'd also be useful to know if ir interpreter shares the same bug.

-[Unknown]

**Comment by benderscruffy** [comment]
using v1.9.3-167-gb2dd3c7e1
still happens using interpreter and ir interpreter

**Comment by unknownbrackets** [comment]
I think rounding is the main area that both interp and ir interp remain wrong compared to jit.

-[Unknown]

**Comment by Panderner** [comment]
The interpreter and ir interpreter menu bugs from the credits are fixed in latest build but no feedback?

**Comment by takeshineale128** [comment]
this issue is now fixed with latest build (v1.10.3-769-g350cb11f9) on opengl and vulkan backends. tested on android 10 phone
