### ISSUE TITLE
FF4 CC issues related to spline/bezier after #7107

### ISSUE THREAD

**Issue by pal1000** [hrydgard/ppsspp#7111]
1. Barrier effect around leading character on save point notification is missing (update of #4234):<br>
Affected backends: both;<br>
Affected spline/bezier quality levels: All<br>
Affected games in collection: Original and Interlude only;<br>
![savepoint_barrier_effect_missing_original_interlude_onnotify_lq_hq](https://cloud.githubusercontent.com/assets/1138235/5224984/f0096392-76e5-11e4-8a1a-fb8f2d13495e.jpg)
2. Thundaga massive slowdown (#7107 regressions)<br>
It was partially analyzed in #7107.<br>
Affected backends: All;<br>
Affected spline/bezier quality level: High;<br>
Affected games in collection: All
![thundaga_massive_slowdown_hq_only](https://cloud.githubusercontent.com/assets/1138235/5225370/6e1e2974-76ec-11e4-9b29-1e80733c422d.jpg)
Game save data: http://pal1000.3x.ro/shared/bugreports/ppsspp/issue-7111/SAVEDATA.zip
Original game:
File 2 is closest to Mist Dragon;
File 4 is over a dungeon save point.
Interlude: Saved in front of Tower of Babil: Final dungeon (clear data);
After Years:
Files 1-6 are clear data. File 5 seams closest to a dungeon save point.

**Comment by unknownbrackets** [comment]
How is this now?  I think the savepoints are resolved, is the only thing left the performance?

-[Unknown]

**Comment by pal1000** [comment]
No change at all. Tested with v0.9.9.1-1442-g 534bf6d

**Comment by hrydgard** [comment]
No change, relative to what? What problems still remain?

**Comment by pal1000** [comment]
No change relative to my previous post.
Issues remaining: 
1. Barrier effect around leading character on save point is missing, but only when save point notification is displayed,e.g. that message that says: "This specially protected zone allows you to pitch Tents, rest in Cottages, and save your progress.". As soon as it's closed the barrier effect appears immediately. It only happens on Original and Interlude games from collection.
2. Massive slowdown when Thundaga spell is cast by either side. Since #7107.

**Comment by unknownbrackets** [comment]
It's really been too long since I actually played FF4... I'm feeling stupid, but how do I get that "specially protected" message to show?

How much does #7513 improve Thundaga for you?

-[Unknown]

**Comment by pal1000** [comment]
#7513 improves the spline speed significantly. It only dropped to around 82% on Intel Core i3-3220/Intel HD Graphics 2500. Still need to test on the far weaker Intel Core i3-2375M/ntel HD Graphics 3000. 

Regarding the save point notification here how to reproduce it:
A.  If you saved via dungeon save point
-after loading leave the room with the save point;
-then come back in it and step on save point again;
The message appears automatically. 
B. If you didn't save via dungeon save point.
Just step on closest one. The message appears automatically.

**Comment by unknownbrackets** [comment]
I've updated it.  I'm hoping the i3-3220 will be able to run it okay now.  Pretty much have no nope for the i3-2375M, at least not on high quality.  How is medium there?

Thanks, that makes sense - I'll look at the save point a bit later.

-[Unknown]

**Comment by unknownbrackets** [comment]
Are you sure it's supposed to draw it then?  I tried in interlude and it's not even trying to draw any bezier/spline while that notification is open.  I can try it later on a PSP.

-[Unknown]

**Comment by pal1000** [comment]
The latest update improves it even further. Around 92% on i3-3220. I think it is exactly like it was before #7107.

Regarding the missing barrier effect, my PSP bricked a long time ago before I could test this, but I felt this is odd.
It very well may be an in-game bug. I am pretty sure devs from Square Enix intended to have that effect on all games in collection.

**Comment by unknownbrackets** [comment]
Sorry, I said interlude but I meant original.  The effect shows after the dialog clears, so it wouldn't be strange if the PSP did the same.  It works the same in interlude, though.

Haven't tested on a real PSP yet, need to copy over a save or something...

-[Unknown]

**Comment by daniel229** [comment]
PSP is not having the Barrier.
![201502271038_001](https://cloud.githubusercontent.com/assets/3481559/6406542/33ad9f22-be6d-11e4-92b8-920b8189a236.png)

**Comment by unknownbrackets** [comment]
Thanks for checking.  So yeah, this works the same as it does on a PSP anyway.

I think we should consider this resolved now that performance has recovered.  I'm sure there's more we can do, but I think the game is pretty playable now.

-[Unknown]
