### ISSUE TITLE
Thrillville Off The Rails Graphics' issues

### ISSUE THREAD

**Issue by GuilhermeGS2** [hrydgard/ppsspp#7459]
Hey devs, I'm here to report an issue, my game Thrillville Off The Rails isn't playable anymore since v0.9.8-1268-g2a3626d, that was the last build which the game is playable. I reported it in the game thread, but I think hardly some dev will read, so I'm creating a new one. The alteration made after v0.9.8-1268-g2a3626d is:

Merge: 2a3626d 19f35bbMerge pull request #6362 from unknownbrackets/gpu-minorUpload stencil/color on FBO create, clear depth/stencil to 0, fix software transform

This problem began with v0.9.8-1275-g413704f and is here till today. So if you guys could fix this game, would make me glad. Maybe this fix some other games as well.

How it's:

http://i58.tinypic.com/2ev88br.png

How it should be:

http://i57.tinypic.com/2h3ojkp.png

**Comment by GuilhermeGS2** [comment]
Can somebody reply at least?

**Comment by Margen67** [comment]
This still happens as of https://github.com/hrydgard/ppsspp/commit/22cef33a18aea3ed297a823de59cf7f01ef48bb4 and in the original/first game as well.

**Comment by GuilhermeGB19** [comment]
So, what about this? Someone interested in work on this?

There's another issue too, when the game was working, it worked only when buffer rendering was disabled, because we have graphics issue with buffer rendering. 

Buffer rendering on:

http://i66.tinypic.com/2m2a045.jpg

Buffer rendering off:

http://i67.tinypic.com/68h7ht.jpg

And this is how it looks after v0.9.8-1268:

http://i66.tinypic.com/102o4sx.jpg

**Comment by GuilhermeGS2** [comment]
Looks like you devs are focusing in graphic issue, so could you take a look at this one? Tell something you need and I'll provide. This game brings me nostalgia from my childhood, it would be nice to play on PPSSPP.

I used GE debugger and the Step Draw button, I noticed only few first drawings are shown, the HUD and the logo are the only last drawings that are executed.

**Comment by hrydgard** [comment]
Oh yeah, forgot about this one. It's failing to clear, and suddenly I understand why:

![clear](https://user-images.githubusercontent.com/130929/33217461-63576920-d138-11e7-8641-3e89fd023bf2.png)

@unknownbrackets  I guess we better try to test and implement that suspected immediate draw stuff...

**Comment by hrydgard** [comment]
pretty clear that f0, f1, f2 are x, y, z.  Z looks fine for a clear, but X and Y are a bit odd. They're symmetrical - the first X is 0x8000-0xF00 and the second X is 0x8000+0xF00.  Same with Y, 0x8000-0x880 and 0x8000+0x880. 

As for f6 and f7... f6 is probably the color, black. f7? 6ff and 7ff, very odd.

**Comment by GuilhermeGS2** [comment]
Thank you for taking a look at this. Tell if can help with something.

**Comment by hrydgard** [comment]
Fixed now.

**Comment by GuilhermeGS2** [comment]
The issue hasn't been fixed yet. :/

**Comment by hrydgard** [comment]
What? Are you sure you're trying the latest build? Which region of the game?

**Comment by GuilhermeGS2** [comment]
Thrillville and Thrillville Off The Rails are different games, I just tested the original and really is working, but the second game is still the same.

**Comment by hrydgard** [comment]
Aha, I might have found the problem. Any skipped frame will break the code that fixes this, like unthrottle or any frameskip setting... Fixing that.

**Comment by hrydgard** [comment]
@GuilhermeGS2  new build is up.

**Comment by GuilhermeGS2** [comment]
Finally, it's working. Thank you very much! :D
