### ISSUE TITLE
PPSSPP 1.1 release - what to fix before?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#7783]
I think it's soon time to push out another official release. The emulator seems to be in a fairly stable state, there are a couple of important features I want to get in first though.

* ~~Ability to delete save state~~
* ~~Enable the homebrew "store", even if it's still a bit ugly~~
* ~~Non-"fast memory" on 64-bit ARM is broken~~
* ~~#7234~~
* ~~Homebrew states naming : #7795~~
* ~~UI text regression : #7884~~
* ~~#7974 (Breath of Fire regression)~~
* ~~#7939~~ (not a bug)
* ~~#7967~~  (fixed, awaiting tests)
* ~~#7991~~
* ~~#7957~~ (fullscreen crash)
* ~~#8001~~
* ~~#8002~~
* #7863 (GTA loading delays)
* PSPKVM?

As usual, of course, add any bad regressions to this thread. That is, things that used to work, but don't anymore.

**Comment by vsub** [comment]
For regression...at least here,the game will ALWAYS crash when you start a new game and go talk to the principal and when he say
"Ah,Killian.Just the person I wanted to see."
if you press X to continue,ppsspp will either freeze or crash.

 v1.0-83-g1ecfd6c is the last working version

**Comment by Bigpet** [comment]
@vsub you should probably mention which game you are talking about and if you have already opened an issue mention the issue number

**Comment by vsub** [comment]
Sorry about that...I'm talking about Crimson Gem Saga and as I said v1.0-83-g1ecfd6c is the last working version and I tried a lot of different newer revs including the latest 1.0.1-551 x86(default settings)

**Comment by unknownbrackets** [comment]
For context: http://forums.ppsspp.org/showthread.php?tid=1243&pid=106178#pid106178

I reproduced this issue with replacements off, but it seems mostly triggered by the Jak & Daxter changes.  Also, I was able to get it to work even with the latest changes.  So it's a timing issue and not 100% of the time, which makes being sure it was caused by anything annoyingly hard.

-[Unknown]

**Comment by vnctdj** [comment]
Ah, the homebrew store :)
It makes me think of an issue...
When we save a state in a game, PPSSPP creates 2 files (a .jpg file and a .ppst file) which are named as the following : `"UMD serial" + "_#"`.
Given that each game has an unique UMD serial, there is no problem :)
But homebrews don't have an UMD serial, therefore when you save a state with homebrew *example1* PPSSPP names the 2 files `"_#"`. And when you save a state with homebrew *example2*, PPSSPP also names the 2 files `"_#"`.
It means that all homebrews will share the same states, which is incoherent...
We have to solve this issue : how should we name the 2 files created when we save a state in a homebrew ?

**Comment by asbel123** [comment]
and new version of ppsspp is 64 support for new  andriod phone update too please i have to use fast mermoy on samsung galaxy s6 edge without fastmermory made graphcis problem u cant see the game. please fix it for new version. i will be happy ur emulator is a best now.

**Comment by hrydgard** [comment]
Yes, ARM64 support is working and will be in 1.1.

What game are you talking about with graphics problems?

**Comment by ppssppios** [comment]
Please, please fix this issue https://github.com/hrydgard/ppsspp/issues/7302 before the 1.1 release

I think i,ve tested every build since early January, it still crashes.

**Comment by asbel123** [comment]
look final fantasy 7 crisis core and kingdom hearts birth by sleep without fast mermory on samsung galaxy s6 edge u get green screen and when i turn it on fast mermory fix the graphics problem on 3d games no 2d game problem just 3d game issues. i think 64 bit issues on new phones

**Comment by hrydgard** [comment]
Oh, right, indeed non-fast memory is broken on 64-bit. Thanks, I'll add it to the list.

**Comment by FibYar** [comment]
It would be great if you could fix "Rewrite". It was broken in 0.9.8:
https://github.com/hrydgard/ppsspp/issues/6981

**Comment by ofry** [comment]
Maybe fix "sceAtrac" issue in Silverfall?

https://github.com/hrydgard/ppsspp/issues/7708
https://github.com/hrydgard/ppsspp/issues/7709

**Comment by ofry** [comment]
And maybe add xBRZ 1.3 ?

#7651

**Comment by jbeich** [comment]
Nominating #7717 as more distros start to use GCC 5.x by default. It should probably be done after update in #7651 to more easily replace with upstream fix.

**Comment by twinaphex** [comment]
PPSSPP has been broken for a few months now on Linux (compiler: GCC).

http://pastie.org/10218708

I think this was pointed out in a separate issue but it was never addressed.

**Comment by ernestbone** [comment]
how about implementing "tunneling all communications through a single port"

**Comment by unknownbrackets** [comment]
> how about implementing "tunneling all communications through a single port"

That's not a regression.  This isn't about "hey what features do you want to make PPSSPP v1.1 take 3 more months to come out for?" but instead, "what had been broken since v1.0.1?"

> PPSSPP has been broken for a few months now on Linux (compiler: GCC).

This doesn't seem to be the case.  Every commit is built on Linux via travis.  I would be getting an email for every merge at least for the past few months if it had not been building on Linux for the past few months.

Rather, something specific to your gcc version or build configuration has not been building for the past few months.

I think PPSSPP already contains most of xBRZ 1.3 (including the alpha performance stuff, which I think was the code I wrote?)

-[Unknown]

**Comment by Fadi5555** [comment]
@hrydgard 
Please add support for 64 bit for me iOS devices like iPhone 5s or up, iPad air/2
Also if you could support OpenGL 3.0 because the new iOS devices use it. I mean to take a big advantage of it.

Also if you could enable to use homebrews specially (pspkvm)
Final if you could use wifi feature to install pspinstaller (this is the best store to download homebrews)

This all my wishes. Best of luck.

**Comment by hrydgard** [comment]
@Fadi5555 Already using some ES 3.0 features on iOS. I'm planning a larger rewrite of the GPU code which might allow further speedups on both ES 3 and newer APIs like Vulkan/DX12/Metal but that's further into the future than 1.1...

pspkvm is a curious case that needs more investigation.

I'll enable the builtin little app store for installing some homebrew apps, and I'll have a look at what PSPinstaller does later..

**Comment by Fadi5555** [comment]
@hrydgard thank you so much for all what have you said.
Yeah if you make a fully use OpenGL 3.0 (with metal for 64-bit devices) I'm really sure you'll get a massive benefits of it.
After that everything will perform like never before. (It'll be FANTASTIC).

About pspkvm this is my hope to run it.
It brings Nokia Java games on your idevice. I hope you could fix pspkvm issue soon
Also I thin if could run pspinstaller it'll be good for installing homebrews
It's super easy to use.

**Comment by twinaphex** [comment]
@unknownbrackets - 

https://github.com/hrydgard/ppsspp/issues/7717

I get the exact same errors when trying to compile xbrz as detailed here. This issue hasn't been closed yet hence it should still be an ongoing issue.

**Comment by enomat** [comment]
You should fix this bug before the next PPSSPP release:
https://github.com/hrydgard/ppsspp/issues/7774

It shouldn't be much work to fix it, because the multithreaded feature works well. Except that one bug when the multithreaded feature doesn't have any effect if it's enabled when you start the game.

**Comment by LunaMoo** [comment]
Any new thoughts about the somewhat ancient regression discussed in https://github.com/hrydgard/ppsspp/commit/4561440df795e80dcd217d5b72c0fe183cd8f234 ?
Known issues caused by it/fixed by re-adding 2 mentioned lines:
#1782
#5999

**Comment by unknownbrackets** [comment]
Those changes still fixed games also.  Unpausing the list on stall address change doesn't reproduce.  Those games have lived with being broken and imho they should be able to live longer until a correct solution has been found, rather than breaking other games by adding back the incorrect behavior.

AFAICT, updating the stall address just.. updates the stall address.  It doesn't change the list state at all.  The assumption those lines of code had was that updating the stall address maybe implied that the list ought to automatically be resumed also.  This isn't correct and it's not how games use it either.

What's happening here is that the list isn't being unpaused by something, and this random place where the list was being unpaused happened to "work around that".  We could also put "chaos list unpauses" in other places in the code (maybe in audio mixing, sounds like a good place?) and that would also "fix" this bug.  It would be no more correct, however, and no less likely to break other games.

-[Unknown]

**Comment by LunaMoo** [comment]
Ha! I had a feeling that if I missuse the word "fix" I might get a lecture:X.(and yet I still did it;c)
 So this was not a regression, might as well be another timing issue which japanese games are already famous from.

**Comment by hrydgard** [comment]
@unknownbrackets There is also the uncomfortable possibility that the display list unpausing behaviour has changed between firmware versions, too, but I don't know if we have seen any correlation between what behaviour the game "needs" and with the firmware version they request.

**Comment by unknownbrackets** [comment]
Yeah, I agree, that could definitely be involved here.  But I do know that someone from uofw told me that the stall addr update function appeared to be handwritten in assembly and was quite simple.  The tests I've run against it have never shown it specifically doing anything with list state.

-[Unknown]

**Comment by Fadi5555** [comment]
Please can you fix a real light of skin and the flashlight in game? The game is tomb raider legend

This is a image for that issue
![image](https://cloud.githubusercontent.com/assets/10546081/8097431/d2f96f2e-0fea-11e5-9e56-cb347b269c29.jpg)

Also in game the flashlight doesn't light in the right way.

To be honest I faced this problem only on my iPad air 2 unlike the previous iPads and iPhones as well.

Please fix this graphic issue before release the v1.1 of ppsspp

**Comment by vsub** [comment]
The Savedata management feature looks cool but I have some suggestions:
1.In the Save State tab,show the save state preview image(I think it's either a but or the feature is not added)...you see the preview when you click on the file but there is no image like when you are just looking at all of the save games

2.If I understand the code correctly,I see that you are reading the game images to get data.
That's not really needed because all the info is in the PARAM.SFO file in the save folder

Save Type at 0x110
Save Description at 0x1230
Game ID at 0x510
Game Name at 0x12B0

3.Again about the Save State tab.
Display the game name and add the save state slot after it rather than using the file name(you can add the file name in the right side or in the preview window)
Add info about which ppspp version was used to create the save state...the info about it is in the save state at 0x10

**Comment by Fadi5555** [comment]
@hrydgard I hope you could fix pspkvm issue before release the ppsspp v1.1
Because this is very important to us to work. And you said you'll find a solution for freeze issue

Other thing there is a problem with save in silent hill shattered memories.
It says the memory is not inserted even if I want to sow the subtitle it's show the memory is not inserted.

This is an image for this issue
![image](https://cloud.githubusercontent.com/assets/10546081/8142143/bb6cf72a-117c-11e5-894c-54eccbb202bc.jpg)
![image](https://cloud.githubusercontent.com/assets/10546081/8142144/bbc232da-117c-11e5-8a10-965384709c30.jpg)

**Comment by sum2012** [comment]
@hrydgard 
Need fix graphic issue of #7234

**Comment by hrydgard** [comment]
@sum2012 thanks for the reminder, I have some ideas about that one.. added it to the list.

**Comment by ppmeis** [comment]
It's only an idea, but we could add load game to memory for Android devices with 4GB RAM? Also I notice there's a lot of graphics bugs with Intel Z3580/Z3560 CPU's, but I don't have time to report them.

**Comment by unknownbrackets** [comment]
It's much more likely that the PowerVR GPU is the reason for the graphics issues rather than the Intel CPU.

Most Android devices have flash storage.  While preloading might improve raw load speed, it's pretty much equal time, and it's going to be faster than a PSP could've loaded data anyway.  Android devices aren't typically going to have the latency delays that you see with mechanical disks.

FWIW, you can also use "Host" IO timing.  If you find this makes the game load more smoothly, then preloading may help (by moving the loading time to the start.)  If it doesn't impact smoothness at all, the issue probably isn't IO.

-[Unknown]

**Comment by GamerzHell9137** [comment]
Any reason why we have the " Cache full ISO in RAM " feature?

**Comment by GamerzHell9137** [comment]
Any reason why we have the " Cache full ISO to RAM " feature?

And i know its off topic but is PPSSPP gonna get UPnP Support?

**Comment by unknownbrackets** [comment]
Well, if you're using a mechanical disk on a desktop, and you allow your disk to spin down, caching to RAM can make sense.

UPnP is not a regression and is off topic here.

-[Unknown]

**Comment by LionMagnus** [comment]
@hrydgard #5999 I found a old version that someone changed/hack that works with Armored Core games http://forums.ppsspp.org/showthread.php?tid=2965&pid=108005#pid108005 , only problem is the blackbox on boosters which was a common issue before, that means potentially you can fix the issue of freezing on all Armored Core series on psp? If so PLEASE do! As a die-hard AC fan, that would be a dream come true

**Comment by sum2012** [comment]
@LionMagnus it is me,
It is the old code change
https://github.com/sum2012/ppsspp/commit/212230ebe2aa5eb5b80edbdd72c7dc67c5acfd1c
I don't know that how to hack in new version

**Comment by Fadi5555** [comment]
@hrydgard hi there.
I just wanna ask you if there any progress of running (pspkvm) on iOS.
Because someone is called @coolmisty45 said he could run pspkvm on his android version of ppsspp

Also if ther any solution for rolling issue on tomb raider?

**Comment by Fadi5555** [comment]
Please can you add pspkvm on homebrew store on ppsspp

I'm pretty sure if you add it. It will run normally.
The pspinstaller has pspkvm on its store but unfortunately pspinstaller doesn't run on ppsspp.

Add it here on the list of ppsspp homebrew store
![image](https://cloud.githubusercontent.com/assets/10546081/8627762/f8167eaa-2755-11e5-980f-2f89022d8c3e.jpg)

**Comment by hrydgard** [comment]
pspkvm is broken in current versions for tricky reasons, and adding it to the homebrew store won't help, only fixing the bug. I obviously won't add it until it runs..

**Comment by Fadi5555** [comment]
@hrydgard thank you so much for replying.
Well I gonna tell you something important.
First of all I have a psp so time ago I downloaded pspkvm So it never run like ppsspp I tri many times but still not working.
One day I downloaded pspkvm from my psp through pspinstaller. I take from unsigned apps.
And then it finally run.

So I have a hope if we could run pspinstaller or put (unsigned pspkvm) and put it on ppsspp homebrew store. I have a feeling it's gonna run great.

Just give it a try there is nothing to lose.
Again thanks a lot for all you have done to make this project looks great.

**Comment by xperia64** [comment]
Is LamecraftMod working for anyone? On the latest Windows (x64) and Android versions it crashes PPSSPP itself whenever it tries to generate terrain. Also happens with the interpreter. There are a lot of log messages like these:
```
07-14 13:42:05.747: E/NativeApp(26696): 42:05:747 user_main    E[FileSys]: FileSystems/MetaFileSystem.cpp:116 RealPath: inPath "Assets/Sounds/ambient/track1.bgm" is relative, but current directory "umd0:" is all prefix and no path. Using "/" as path for current directory.
```

**Comment by vnctdj** [comment]
@hrydgard 
A reminder about 2 relevant issues, as they are not on the list of the first post :
- Homebrew states naming : https://github.com/hrydgard/ppsspp/issues/7795
- UI text regression : https://github.com/hrydgard/ppsspp/issues/7884

**Comment by hrydgard** [comment]
@vnctdj , thanks, copied to the first post. 

BTW, I got inspired and am busy with a total rethink of how PPSSPP draws stuff, which might hopefully improve performance considerably, so the new release is on hold for a little bit, but I'll have to get to it soon.. will take too long to get my new GPU code ready to make it to this release.

**Comment by vnctdj** [comment]
Oh, I guess it explains why no commit has been pushed to master since one week :)
It sounds really interesting !

**Comment by sum2012** [comment]
@hrydgard Please don't forget update README.md

**Comment by GamerzHell9137** [comment]
https://github.com/hrydgard/ppsspp/issues/7886

Still an issue.

**Comment by asbel123** [comment]
hygard can u do pppsspp gold version add cw cheats db for andriod version beacuse drastic ds did that for andriod its sell crazy for google play please only 1.1 version ppssspp gold.

**Comment by LunaMoo** [comment]
@asbel123 I'm not against cheats, heck I make a lot of them by myself, but that would be really bad idea for a simple reason - we don't have a single database created specially for ppsspp with only tested cheats and maintained to reflect code changes that affect addresses. You could start a thread in the forums to collect working cheats from people who safely played with them and build such database, but for now there's really nothing that could be safely shipped with ppsspp.

 Adding any of those big databases flying around the net and even shared on ppsspp forums would just cause an outbreak of people submitting issues caused by cheats, since they include lots of cheats which would be broken even on psp by bad conversions from other formats, incorrectly assigned versions etc. there's 0 quality control there, just mass copy&paste:|. That get's worse with ppsspp since it's not perfect yet and in many popular games memory differs from actual psp ~ which pretty much for affected titles breaks all simple cheats that use static addresses.

**Comment by hrydgard** [comment]
Alright, getting back to this. Been doing some UI bug fixing today ( @GamerzHell9137 will be happy), will see if I can find a workaround for  #7863 (GTA music issue) later this week, then will start to wrap this up.

**Comment by Fadi5555** [comment]
Hi @hrydgard.
Could you fix the fake light of tomb raider legend? See above the two pictures of it. You will see the different between them.
Other thing did you fix the (pspkvm) freezing?
Thanks again for your hard work.

**Comment by vnctdj** [comment]
@hrydgard, just a reminder.
A regression to add to the list of the first post :
- Texture glitch in CGI video : https://github.com/hrydgard/ppsspp/issues/7939

**Comment by daniel229** [comment]
How about the Depth range hack?

**Comment by sergiobenrocha2** [comment]
SDL build broken on ARM (again?) #7969

**Comment by GamerzHell9137** [comment]
This should be fixed too https://github.com/hrydgard/ppsspp/issues/7957

**Comment by sum2012** [comment]
Fix Windows XP compatibility #7967

**Comment by LunaMoo** [comment]
Not much of an blocking issue not so new either althrough not long ago it was asked a few times in the forums ~ so are there any plans for postprocessing shaders in D3D backend?
I guess shaders themselves could be translated by defining data types and common functions from one to another, for example:

    #if HLSL
        (...)
        #define vec2 float2
        #define mix(x,y,s) lerp(x,y,s)
        (...)
    #endif


etc., but there's probably much more stuff left to do.

~ Which might not be worth doing, since for the most part it's used by people with very weak/outdated hardware that couldn't run too many shaders without affecting performance anyway. Maybe we should just disable the option for postprocessing shaders in that backend before 1.1 release.

**Comment by sergiobenrocha2** [comment]
version string corrupted, #7991

**Comment by sergiobenrocha2** [comment]
#7730 still happens. If I load only one game, it forgets in the next time. I had to open 2 games to appears at least one in the recent files.

**Comment by sum2012** [comment]
@hrydgard 
Can merge #7965 ?

**Comment by hrydgard** [comment]
@sum2012  I will take a look soon. It may need some changes.

**Comment by vnctdj** [comment]
@hrydgard 
You forgot to add this, as [I wrote earlier](https://github.com/hrydgard/ppsspp/issues/7783#issuecomment-138392581) : 
> A regression to add to the list of the first post :
> - Texture glitch in CGI video : https://github.com/hrydgard/ppsspp/issues/7939

**Comment by sum2012** [comment]
@hrydgard OK

**Comment by vnctdj** [comment]
@hrydgard 
Unfortunately, recent changes have caused 2 new issues : 
-  Broken translations : #8001 
- Auto rendering resolution is broken : #8002

**Comment by sum2012** [comment]
@hrydgard add #8003

**Comment by sum2012** [comment]
Can this issue can close ?
Or used for for v1.1.1

**Comment by unknownbrackets** [comment]
I'm going to close it.  If we want one for 1.1.1 we can open one, but I think we've largely fixed the things we want fixed in that release (barring new regressions.)

-[Unknown]
