### ISSUE TITLE
Full screen mode not working in PPSSPP 1.1.0 Ubuntu x64

### ISSUE THREAD

**Issue by shankeyb** [hrydgard/ppsspp#8032]
I recently installed PPSSPP 1.1.0 everything is working fine except the full screen mode whenever i enable the full screen mode nothing happens.  please fix it as soon as possible. earlier version of ppsspp has no issue of full screen mode.

Due to this full screen issue i had to increased screen size to 3x due to which i am getting cracking sound as well as lower fps.  Please fix this bug below i have attached the screenshot of fullscreen bug.
![issue](https://cloud.githubusercontent.com/assets/14998229/10311529/c45f1596-6c64-11e5-866f-d478c8871655.png)

Thank-you

**Comment by sergiobenrocha2** [comment]
It's working here, if I double click in the window.

**Comment by shankeyb** [comment]
I have tried everything but it still doesn’t works at all. i am unable to play games at full screen mode and i had also tried this in Ubuntu 15.04x64 its also having the same issue. I don’t know why it doesn’t works.

Whenever i double click the window it enables the title menu in ppsspp window. here is the another screenshot.
![issue23](https://cloud.githubusercontent.com/assets/14998229/10335507/d5a47134-6d0e-11e5-9519-3af4aeb103fa.png)

**Comment by sergiobenrocha2** [comment]
I'm testing it on Xfce, I guess it's Unity problem?

**Comment by shankeyb** [comment]
@sergiobenrocha2 I don’t know about that..maybe u r right..but i just want to fix it is there is any working method for it??? 

@hrydgard please go through this. its an active issue fullscreen issue of ppsspp 1.1.0

**Comment by sergiobenrocha2** [comment]
I can confirm the issue on Ubuntu 14.04.1. You can launch it with:

```
ppsspp --fullscreen
```

You can change the desktop entry with the menulibre app.

You can also use another desktop like Xfce or use the sdl version (ppsspp-sdl) which launches in fullscreen by default.

**Comment by sergiobenrocha2** [comment]
Just a side note: 1.0.1 was using Qt 4 in the PPA, 1.1 is using Qt 5. Maybe is it related?

If it's Qt fault, maybe it's fixed in later ubuntu versions such 15.04 or 15.10

**Comment by sergiobenrocha2** [comment]
Weird, if I launch with --fullscreen, the double click works...

**Comment by shankeyb** [comment]
You are the man!!!  Thank-you so much It works!! with the fullscreen command...But when i disable fullsceen by double click on fullscreen then renable it by same. Its showing me half screen output. i have posted the screenshot. but atleast my full screen works.
![new iss](https://cloud.githubusercontent.com/assets/14998229/10357935/b1a66c14-6da5-11e5-8f08-8fa42d5ab820.png)


And if there is a Qt fault then its not yet fixed in ubuntu 15.04 cz its also having same full screen issue.  i don’t know about 15.10 may be its fixed.

**Comment by unknownbrackets** [comment]
Does this work in the latest release of Ubuntu?

Does the screen stretch properly after toggle, or is it still broken as above?

-[Unknown]

**Comment by sergiobenrocha2** [comment]
@shankeyb could you test it?

**Comment by shankeyb** [comment]
I haven't tested it in latest release i will test it in 16.04 but..Its Still Broken, all i need 2 do is to tap ESC key 2 times to make it full screen output and i have tested it in ubuntu 15.04 too but its still having same issue after so many updates.

**Comment by sergiobenrocha2** [comment]
Still happens on 1.2.1. I'll work around it with --fullscreen in the *.desktop file of the deb packages.

**Comment by JoseBarakat** [comment]
**PPSSPP 1.2.2**
Fullscreen mode works, but something's failing.

How to Reproduce:
- Open ppsspp-sdl (either from the terminal or from its own launcher icon)
- Select and start a game (in fullscreen mode, this is important)
- Play for a while and press [Esc] to return to PPSSPP menu.
- Now in the menu, mouse pointer can move but it is unable to perform click actions. Desktop freezes. 

Expected:
- Menu working fine in fullscreen mode without freezing system.

NOTE: Windowed mode works excellent in any resolution/size.

```
Phoronix Test Suite v6.4.0
Interactive Benchmarking
System Software / Hardware Information

Hardware:
Processor: Intel Core i3-3110M @ 2.40GHz (4 Cores), Motherboard: LENOVO, Chipset: Intel 3rd Gen Core DRAM, Memory: 6144MB, Disk: 500GB Seagate ST500LT012-9WS14, Graphics: Intel HD 4000 (1000MHz), Audio: Conexant CX20757, Network: Qualcomm Atheros QCA8172 Fast + Qualcomm Atheros AR9485 Wireless

Software:
OS: Ubuntu 16.04, Kernel: 4.3.0-040300-generic (x86_64), Desktop: Unity 7.4.0, Display Server: X Server 1.18.3, Display Driver: intel 2.99.917, OpenGL: 3.3 Mesa 12.1.0-devel (git-7295428 2016-07-03 xenial-oibaf-ppa), Vulkan: 1.0.8, Compiler: GCC 5.4.0 20160609, File-System: ext4, Screen Resolution: 1366x768
```
<br>
Terminal Output:
```
~$ ppsspp-sdl -d --log=/[hidden-path-to-file]/ppsspp-sdl-test.txt
OpenGL 2.0 or higher.
W: file_util.cpp:178: IsDirectory: stat failed on /usr/games/assets/lang/en_US.ini
W: file_util.cpp:178: IsDirectory: stat failed on /usr/games/lang/en_US.ini
56:01:389 Core/Config.cpp:935 I[LOAD]: Loading controller config: /home/jose/.config/ppsspp/PSP/SYSTEM/controls.ini
Pixels: 960 x 544
Virtual pixels: 960 x 544
I: gpu_features.cpp:123: GPU Vendor : Intel Open Source Technology Center ; renderer: Mesa DRI Intel(R) Ivybridge Mobile  version str: 3.0 Mesa 12.1.0-devel (git-7295428 2016-07-03 xenial-oibaf-ppa) ; GLSL version str: 1.30
E: PCMain.cpp:648: Output audio samples: 1024 (requested: 2048)
58:09:182 Core/Config.cpp:1017 I[LOAD]: Config saved: /home/jose/.config/ppsspp/PSP/SYSTEM/ppsspp.ini
58:09:183 Core/Config.cpp:1030 I[LOAD]: Controller config saved: /home/jose/.config/ppsspp/PSP/SYSTEM/controls.ini
I: prioritizedworkqueue.cpp:33: Flushed 0 un-executed tasks
58:09:188 Core/Config.cpp:1017 I[LOAD]: Config saved: /home/jose/.config/ppsspp/PSP/SYSTEM/ppsspp.ini
58:09:188 Core/Config.cpp:1030 I[LOAD]: Controller config saved: /home/jose/.config/ppsspp/PSP/SYSTEM/controls.ini
I: NativeApp.cpp:949: NativeShutdown called
```
Note PPA `git-7295428 2016-07-03 xenial-oibaf-ppa` in line 8 for Intel graphic drivers.

**Comment by unknownbrackets** [comment]
#11163 may help the Qt stuff, although I'm not sure if it's specific to a certain window manager.  The Qt documentation actually explicitly says that full screen just doesn't work on some window managers because they don't always *support* apps going into full screen.

I couldn't reproduce any issues with SDL full screen on a Mac - but made some tweaks.  Would be good to retest that in the latest PPSSPP version.  Does it still happen?

-[Unknown]

**Comment by TehPlayer14** [comment]
How about latest version?

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
