### ISSUE TITLE
D3D11 - Glitches

### ISSUE THREAD

**Issue by DonelBueno** [hrydgard/ppsspp#9361]
The new backend is great, but it still has some issues. These are the ones I could find:

Burnout Legends - Broken sun effect

![ppssppwindows64 2017-02-25 18-01-21-38](https://cloud.githubusercontent.com/assets/4239694/23340499/fdc9f282-fc15-11e6-94aa-402ff8ceaaaf.png)

Gran Turismo - Incorrect Skybox (only happens with Texture Scaling enabled)

Incorrect
![ppssppwindows64 2017-02-25 18-09-58-15](https://cloud.githubusercontent.com/assets/4239694/23340504/0cdafbd6-fc16-11e6-8840-93e36fb20060.png)

Correct:
![ppssppwindows64 2017-02-25 18-13-52-22](https://cloud.githubusercontent.com/assets/4239694/23340505/0cdb4154-fc16-11e6-8bb3-a52462700ab7.png)

They all work fine on D3D9 and OpenGL.

System Specs:

Windows 10 Pro 64 bits
i7 980x @ 4.04 GHz
GTX 770 2GB
12 GB DDR3

**Comment by hrydgard** [comment]
One more is depth buffer trouble in Pursuit Force. Apart from that and these it's nearly caught up indeed it seems...

**Comment by Zetchzie** [comment]
Ive run into a few errors myself but ill give d11 some time before i post them

**Comment by hrydgard** [comment]
If you have obvious ones, feel free to post some screenshots.

**Comment by Zetchzie** [comment]
Im not sure if they are since im a basic user. but Silent hill shattered memories has issues in the flashlight that are more pronounced in d11 and spongebob yellow avenger has completely blacked out almost like in my earlier post before i got a new computer

**Comment by Zetchzie** [comment]
DX11
![ulus10450_00000](https://cloud.githubusercontent.com/assets/15071652/23343189/7d260dee-fc35-11e6-86b0-ee79aee28ae3.jpg)
DX11
![ules00280_00000](https://cloud.githubusercontent.com/assets/15071652/23343190/80b04f9c-fc35-11e6-9fb2-aa1b084a4229.jpg)
OGL
![ulus10450_00001](https://cloud.githubusercontent.com/assets/15071652/23343211/cdb02a60-fc35-11e6-952d-3eb716d37ee4.jpg)
OGL
![ules00280_00003](https://cloud.githubusercontent.com/assets/15071652/23343216/da28941c-fc35-11e6-99b4-45de7c970fc9.jpg)

**Comment by hrydgard** [comment]
Thanks, good reports.

**Comment by Zetchzie** [comment]
Little note though DX9 is pretty much the same as OGL in my tests so I didnt bother with screens for it

**Comment by moura464** [comment]
![ulus10025_00003](https://cloud.githubusercontent.com/assets/22099440/23379668/9532e1a0-fd16-11e6-8a44-8964f349bddb.jpg)

**Comment by hrydgard** [comment]
That fixed Pursuit Force at least, maybe some more of the issues?

**Comment by tywald** [comment]
Sometimes when you start Monster Hunter games it looks like this:

![gffgfjhjty](https://cloud.githubusercontent.com/assets/10337060/23589085/85e9aac0-01c7-11e7-8f21-d70bd316491f.png)
![yhrthtfghh](https://cloud.githubusercontent.com/assets/10337060/23589083/85e2c1e2-01c7-11e7-848e-29dad68b93ff.png)
![fwsfgrehe](https://cloud.githubusercontent.com/assets/10337060/23589084/85e474ba-01c7-11e7-879e-0384db2c7d10.png)

Default settings, apart from changing backend to D3D11 of course.

**Comment by DonelBueno** [comment]
@hrydgard, that's not Pursuit Force, it's Burnout Legends. The new commits make the game much worse =/

**Comment by hrydgard** [comment]
Really? Hmm..

**Comment by hrydgard** [comment]
Hm, Pursuit Force indeed still has some glitches. And burnout legends indeed has broken. Digging into it soon.

**Comment by DonelBueno** [comment]
Oh, I got your first comment in this ticket wrong, sorry for the confusion.

**Comment by hrydgard** [comment]
Commit 116edcb77a4114e5a00dfdfc12345fee8d0ea408 seems to have broken things, hm..

**Comment by hrydgard** [comment]
That takes care of the random missing geometry bugs that recently showed up. Silly typo..

**Comment by hrydgard** [comment]
Can everyone try again with the latest fix? Pretty sure the Monster Hunter glitch is gone now.

**Comment by tywald** [comment]
@hrydgard yep, Monster Hunter games have been fixed.

**Comment by Zetchzie** [comment]
![ulus10450_00002](https://cloud.githubusercontent.com/assets/15071652/23593305/2a08088c-01db-11e7-8dc4-f2ff7ffbf3b6.jpg)
Well this is using the latest build and this happens now and spongebob still broken

**Comment by DonelBueno** [comment]
This one only happens with Texture Scaling Enabled:

https://cloud.githubusercontent.com/assets/4239694/23340504/0cdafbd6-fc16-11e6-8840-93e36fb20060.png

**Comment by Zetchzie** [comment]
Flashlight is fixed in v1.3-819-gca85716
![ulus10450_00003](https://cloud.githubusercontent.com/assets/15071652/23708201/28f267b2-03e3-11e7-890b-7b82b5187947.jpg)
But now the phone is broke lol
![ulus10450_00004](https://cloud.githubusercontent.com/assets/15071652/23708263/5bf4e9be-03e3-11e7-89b0-f17ec8ff1251.jpg)
Spongebob still have same error a earlier

**Comment by hrydgard** [comment]
@DonelBueno thanks! 

Strange stuff with Silent Hill..

**Comment by Zetchzie** [comment]
@hrydgard  I see what you did there lol

**Comment by hrydgard** [comment]
Burnout should be completely fixed now.

**Comment by unknownbrackets** [comment]
Incorrect octopus colors - like in #8252.  They are both the same color.  Should mean something wrong with DownloadFramebufferForClut.

-[Unknown]

**Comment by DonelBueno** [comment]
Burnout Legends confirmed fixed, even at higher resolutions =)

Great work!

**Comment by Zetchzie** [comment]
Flashlight broke again in v1.3-1030 but the cellphone works again lol
![ulus10450_00005](https://cloud.githubusercontent.com/assets/15071652/24135587/123d8210-0de1-11e7-8488-8ab838143e0e.jpg)

**Comment by hrydgard** [comment]
I'm pushing remaining issues here to 1.5. The huge majority of games seem to work well with D3D11, with very good performance.

**Comment by DonelBueno** [comment]
So only Spongebob and Silent Hill left?

**Comment by unknownbrackets** [comment]
Very possibly may be caused by depth and stencil being copied at the same time when depth-reuse is being semi-detected.

-[Unknown]

**Comment by hrydgard** [comment]
Remaining glitches are not really unique to D3D11 but more general issues. Anyway, keeping open but bumping to 1.6.

**Comment by unknownbrackets** [comment]
Should we close this yet?  If it will just get bumped to every release until all renderers are perfect in all games, and all other bugs are fixed... then it's probably not useful on its own.

-[Unknown]
