### ISSUE TITLE
None of my homebrews work anymore

### ISSUE THREAD

**Issue by 240-185** [hrydgard/ppsspp#9590]
All my PSP homebrews have been coded with OSLib Mod V2. They were working fine under PPSSPP v1.3 and its different automated builds.

Now they make v1.4 crash, or there are numerous problems with text rendering, regardless of the back-end rendering selected. Nice regressions we have there!

**Comment by hrydgard** [comment]
Nice tone you have there! We can't possibly test everything in every release.

One thing, make sure you don't have the initially released version of 1.4 on Android, that one is broken (is missing a font file) and you need to update.

Please upload or link to one of your homebrews so we can try them, that's the only way this will get fixed, if it's not that.

**Comment by 240-185** [comment]
I'm using the Windows version and I just overwrite the files. I reverted back to v1.3-303 as this is one of the last versions that run my homebrews.

Now, here are some of my productions:

Released:
Alice in Pasta Crocket: http://wololo.net/downloads/index.php/download/8183
COGEEP : http://wololo.net/downloads/index.php/download/8387

Unreleased, unfinished but functional:
120BPM crumbs: http://www.latelier240.fr/Vrac/psp/120bpm_crumbs.zip
Homebrew imitating ZX Spectrum graphical limitations: http://www.latelier240.fr/Vrac/psp/speccy_engine.zip
→ All these homebrews crash right at start with v1.4. Something that is somehow related with loading the graphics or the music in .XM format.

Last but not least, some homebrew whose purpose is to display lots of text: http://www.latelier240.fr/Vrac/psp/ImprovHelper.zip
→ The text does not display at all. The brownish rectangle in the main menu does not even display with DirectX 9 or DirectX 11. Maybe something having to do with the size of the texture of the font (all the glyphs are contained in an .OFT file and then the library picks the right one inside when drawing text)

Source code of OSLib mod V2 as their (messy) source code heavily relies on this library: https://github.com/dogo/oslibmodv2

**Comment by LunaMoo** [comment]
Worked fine* here at least the stuff from two first links using ogl on windows.
(*to be fair I ctrl+w pretty quickly after getting "in-game", if there's something I value psp for, it's definitely not it's weird homebrew;p)

 I noticed with the second "game" you're providing a copy of ppsspp, but keeping game folder in ppsspp root directory - I didn't even bothered to check what ppsspp version is there as pretty sure with that finding I found why it doesn't work and have a solution:
 Place your homebrew under "memstick\PSP\GAME\".

 That's all there is to it, in the past there was a bug which allowed some of it to work from outside of the memstick, but it was fixed and buggy behaviour will not return.

**Comment by 240-185** [comment]
OK, this may explain everything. Thanks for that clarification.
I had to admit that I always launched the Eboots from my Eclipse workspace folder.

**Comment by 240-185** [comment]
Reopening this issue after have moved into \memstick\psp\game
They still crash the emulator.

**Comment by hrydgard** [comment]
Huh, curiously when running a release mode PPSSPP, I got this in Pasta: 

![emulators](https://cloud.githubusercontent.com/assets/130929/25062035/f8a3e69a-21c3-11e7-9add-d8235f12ff1c.JPG)

**Comment by hrydgard** [comment]
OK, more investigation :) I accidentally had the software renderer enabled. That made those start up. With D3D11, there's only a black screen. It may be that the games are drawing but it's not showing up...

**Comment by 240-185** [comment]
Yes, the glitches are intentional :D
As for the Mr. Mackey picture, I coded a lousy way to detect if PPSSPP or a PSVita running ARK are used by trying to open the directory "flash1:/". For Pasta Crocket, if there's no flash1, then a heart attack is triggered.

This is easy to circumvent for PPSSPP, though.

**Comment by 240-185** [comment]
An update regarding this issue:

I downloaded v1.4-134 (amd64) and I noticed that PPSSPP crashes when I try to load an EBOOT.PBP via the browser windows under Windows. But when I try to reload the homebrew via the "Homebrews & Demos" tab, it loads perfectly fine.

**Comment by hrydgard** [comment]
Is that even if the file is located in the memstick folder, where Homebrews & Demos loads from?

**Comment by 240-185** [comment]
I copied the homebrew into the memstick folder, so, yes.

**Comment by tilkinsc** [comment]
Hmm I think this might be because it has to be in a folder too, for example
PSP/GAME/GAME_FOLDER/*

**Comment by 240-185** [comment]
Well, it was fixed in PPSSPP v1.5 and the homebrews ran flawlessly, even when launched from my Eclipse workspace folder.

**Comment by hrydgard** [comment]
OK then, I guess we can close this.

**Comment by unknownbrackets** [comment]
Right - probably #9790 helped.

-[Unknown]
