### ISSUE TITLE
Assassin's Creed Bloodlines PPSPP issue

### ISSUE THREAD

**Issue by blazingkyuubii** [hrydgard/ppsspp#9643]
Hello, I just downloaded PPSPP on my mobile and downloaded this AC game. I opened it and the intro goes well. 

When the intro ended, I started it, but I only see my functioning character but not the background. I only see a light blue screen with some geometric and mathematic animations in it.

**Comment by Levan7** [comment]
You are playing the tutorial level aren't you ?

**Comment by blazingkyuubii** [comment]
Yes I am.

**Comment by Levan7** [comment]
Well the tutorial level should look like that, take a look here 
https://youtu.be/JokKHCwP4DU?t=1m56s

**Comment by blazingkyuubii** [comment]
I do hear the robot's voice but the background is completely the blue screen, I can't see those camera thing, high profile, those controls settings etc.. Do I need to turn something on for that?

**Comment by blazingkyuubii** [comment]
Update: I passed the tutorial through watching the video you gave me then going back to game vice versa, and I went to the game.

(while at the tutorial)I tried checking the settings and lowered the render, the resolution etc.. and it pretty made my laggy gameplay smooth, then just what i've said i finishrd the tutorial with the video.

(at the game) The gameplay became shi*** lag again so I checked the Mode option to see what that is and changed the settings to see what happens, I went back to the game and saw the missing "camera thing, high profile, those controls settings etc." but the screen went black. I changed to other settings and the screen went completely black without those with "camera thing..." (i forgot what to call them lol) so I changed it back to its default setting and it's still black asf.

 I turned on the FPS display and it shows 9/30fps so I'm thinking this is because of my phone's lack of (probably) requirements to play the game (probably PPSPP as well). I have a 2gb ram (actually just 1.93) and sometimes it goes down to 1.1?+ or 0.??.

**Comment by Levan7** [comment]
Well i don't know about settings and fps but i checked it on my phone and latest svn build sims to render everything correctly.
![screenshot_20170426-212809](https://cloud.githubusercontent.com/assets/5770076/25447874/d52b4f7a-2ac7-11e7-858b-b61876eaed1e.png)
![screenshot_20170426-212838](https://cloud.githubusercontent.com/assets/5770076/25447875/d531fbb8-2ac7-11e7-97b4-b15db13e8d2c.png)

**Comment by blazingkyuubii** [comment]
Dayum, that's unfortunate, anyway let me show you what it looks like.

Btw, I tested it again and the tutorial became laggy but the sound isn't. 


![screenshot_2017-04-27-11-12-46](https://cloud.githubusercontent.com/assets/28000565/25466417/2fd199d4-2b3b-11e7-9a6e-8fa7298b36dd.png)
![screenshot_2017-04-27-11-12-52](https://cloud.githubusercontent.com/assets/28000565/25466436/437cc184-2b3b-11e7-9496-1f715fb68bd5.png)
![screenshot_2017-04-27-11-12-59](https://cloud.githubusercontent.com/assets/28000565/25466446/50576832-2b3b-11e7-80da-0958d1b0fed9.png)
![screenshot_2017-04-27-11-13-11](https://cloud.githubusercontent.com/assets/28000565/25466453/5ac8f1e6-2b3b-11e7-839c-3d5dd6a9a7b7.png)
![screenshot_2017-04-27-11-13-15](https://cloud.githubusercontent.com/assets/28000565/25466460/63d47de6-2b3b-11e7-96a6-bed93b884e48.png)

My settings is probably like the poorest one, idk im not sure, but it's like 360p on youtube lol

![screenshot_2017-04-27-11-15-05](https://cloud.githubusercontent.com/assets/28000565/25466489/9320490e-2b3b-11e7-9265-9461a4cf7cf3.png)

Here's what I've been talking about the tutorial, yesterday I played it smoothly with my settings but now the gameplay became laggy except for the sound. Look at the FPS, it's like playing GTA SA with an old Windows Computer lol 

![screenshot_2017-04-27-11-15-31](https://cloud.githubusercontent.com/assets/28000565/25466525/c5afe438-2b3b-11e7-940b-f9e54b02d926.png)

Here's the part when I change ny Mode settings and when I turn it back to it's previous settings, it turns completely black.

I hope I can find a solution or this or maybe recommend me a good game that doesn't use up too much of perfect resolution lmao or that works with any phone, and where can I find a better place to download games?

**Comment by unknownbrackets** [comment]
I recommend turning on Mipmapping and Hardware transform.  Both features should improve performance and improve accuracy compared to a real PSP.

Unfortunately, it's possible the frameskipping - in some cases - may cause some effects to render incorrectly.  Have you tried to see if the graphics are correct with frameskipping off?  I realize it may be too slow, but it'd still help to understand if frameskipping is related to the graphics issue or not.

Lastly - try this on the latest git build (not from the Play store - on the PPSSPP downloads page.)  We've fixed an issue with changing between rendering modes while in game.

-[Unknown]

**Comment by blazingkyuubii** [comment]
Hello, I downloaded the one from PPSPP, turned on everything you've said and set my frameskip to 1 (i forgot to turn off the frameskip) and it was playing smoothly again. Now my problem is back with the instructions thing, I mean I don't have those things on my last screenshot those blue things. It's also running smoothly on the real game (not tutorial). I can't see the instructions so I don't know how to pass the level.

**Comment by blazingkyuubii** [comment]
Update: Turned off the frameskipping and it was smooooother than frameskip:1, but the character/s act too slowly esp on the real level. So I prefer the frameskip:1 

I tried to turn on the Mode again (the first option) and the last screenshot happened to me again lol it went black except the instructions are there.

**Comment by blazingkyuubii** [comment]
Hello there, so I checked out Naruto Ninja Heroes and downloaded it. Everything except when battles aren't laggy. Even the sound. Also happens with AC.

 I turned on and set to Frameskip:3 NNH to avoic hearing the cracky sound and of course it's laggy, I switched back to FS:1 and the sound was cracky and still laggy(gameplay). I turned off the FS and it was definitely laggy even the sounds. 

Sighs, having such an opportunity to bring back my childhood games but then having this issue is kinda unfortunate lol

**Comment by unknownbrackets** [comment]
You can and should purchase the games you want to play - many are available used for low prices.  Anyone who tells you used games are basically the same as piracy failed their economics course.

Your device is probably just not powerful enough to run PSP games at full speed.  PPSSPP can run well on many modern phones... but it still requires the more powerful range of phones.  RAM isn't the most important thing - CPU speed matters a lot too.  And so does what GPU the phone has.

-[Unknown]

**Comment by blazingkyuubii** [comment]
May I see the system requirements for PPSPP from Minimum to Maximum?

**Comment by blazingkyuubii** [comment]
Heya, I'vr decided to install an app to check the phone's specs. My phone isn't a well known product internationally but it is locally known here in PH. (P.S im not really sure about these things but the CPUs on the first pic sometimes stops [probably 4-5 of them] but sometimes they're all filled with the same MHz.)

Um, I guess, what do you think?

![screenshot_2017-04-27-22-29-53](https://cloud.githubusercontent.com/assets/28000565/25488461/a6a26d96-2b99-11e7-989a-ac1ae32406ae.png)
![screenshot_2017-04-27-22-30-02](https://cloud.githubusercontent.com/assets/28000565/25488472/ad1ff328-2b99-11e7-9376-1ffbd2a9bfda.png)
![screenshot_2017-04-27-22-30-05](https://cloud.githubusercontent.com/assets/28000565/25488479/b651577a-2b99-11e7-9ad9-c1b5635f818a.png)

**Comment by unknownbrackets** [comment]
Yeah, unfortunately 1.36 Ghz is probably too low to get great performance in many games.  The number of cores doesn't help much with PSP emulation.

That company's Cosmos Three (2.1 Ghz + Mali-T880) or possibly Desire R8 (although it's only 1.5 Ghz, it has a much better GPU than the Flare XL) would have a better chance.  Unfortunately, I can't say for sure if they'd run full speed, especially the Desire.

-[Unknown]

**Comment by blazingkyuubii** [comment]
That's a shame lmao can you just recommend me an emulator with great games (except GBA), I want to play even without an internet connection. Just something to play probably while on the road to avoid being bored while doing nothing. Pretty please lol
